### ISSUE TITLE
1.0.13 Testing

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/commons-in-a-box#113]
@boonebgorges (or anyone else watching this repo) - I've attached a beta version of v1.0.13 for internal testing - [CBOX v1.0.13-beta1.zip](https://github.com/cuny-academic-commons/commons-in-a-box/files/528420/cbox-1.0.13-beta1.zip)

It bundles BP Group Email Subscription and CBOX Theme into the ZIP because I haven't tagged either of those items yet.

Pending any bug reports, we can tag those versions when we're ready to.

**Comment by christianwach** [comment]
Apart from the usual slew of `PHP Deprecated`, `PHP Strict Standards` and `PHP Notice` entries in the log file from activating the theme, I have seen nothing amiss since activating this on my localhost single site, multisite and multi-network installs. Fresh installs and upgrades have all gone smoothly. Thanks @r-a-y 👍

**Comment by r-a-y** [comment]
> Apart from the usual slew of PHP Deprecated, PHP Strict Standards and PHP Notice entries in the log file from activating the theme

I'm thinking maybe we should start suppressing the `cbox-theme` notices as they are pretty annoying for those with `WP_DEBUG` turned on.

**Comment by christianwach** [comment]
An adapted version of [your mu-plugin](https://gist.github.com/r-a-y/bab85fc47fa0357a8100) is part of my default install on anything other than localhost development sites. Most of the notices seem to originate in the Infinity Engine, which - as I understand it - is more tricky to fix than the 'pure' CBOX code, so I'd support your suggestion.

**Comment by boonebgorges** [comment]
> I'm thinking maybe we should start suppressing the cbox-theme notices as they are pretty annoying for those with WP_DEBUG turned on.

+1 #115 

Things are looking good in my testing! Let's talk on our call today about next steps and release timeline.

**Comment by r-a-y** [comment]
During today's dev call, we discussed how it might be an issue if we suppressed notices for foreign installs.

I haven't found any research confirming that PHP notices are localized (should always be in English), so we should be good to proceed.

Here's the closest article I could find about this:
http://stackoverflow.com/questions/11556375/is-there-a-way-to-localize-phps-error-output

**Comment by christianwach** [comment]
@r-a-y Here's a sample straight out of my logs:

> [11-Oct-2016 21:29:51 UTC] PHP Notice:  bbp_setup_current_user wurde <strong>fehlerhaft aufgerufen</strong>. Der aktuelle User wurde initialisiert ohne Gebrauch von $wp->init(). Weitere Informationen: <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> (engl.) (Diese Meldung wurde in Version 2.3 hinzugefügt.) in /xxx/public_html/wp-includes/functions.php on line 3996
> [11-Oct-2016 21:29:51 UTC] PHP Notice:  bp_setup_current_user wurde <strong>fehlerhaft aufgerufen</strong>. Der aktuelle Benutzer wird ohne Verwendung von $wp->init() initialisiert. Weitere Informationen: <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> (engl.) (Diese Meldung wurde in Version 1.7 hinzugefügt.) in /xxx/public_html/wp-includes/functions.php on line 3996

**Comment by r-a-y** [comment]
I'm not concerned with WordPress notice messages generated by plugins.  We only want to suppress PHP notices like `Strict Standards` or by checking the file creating the notices.

My [notice overrider](https://gist.github.com/r-a-y/bab85fc47fa0357a8100) doesn't check for localized strings.

**Comment by boonebgorges** [comment]
Thank you, @r-a-y!

I'd like to hand this over to our team for testing, but I wanted to check with you first. Do you want to give them a prepackaged zip (maybe the very one you generated before), or do you want to tag the constituent plugins first?

**Comment by r-a-y** [comment]
@boonebgorges - Let's pass them a prepackaged ZIP.

I've updated the beta ZIP with all the latest fixes as of today - [CBOX 1.0.13-beta1.zip](https://github.com/cuny-academic-commons/commons-in-a-box/files/528420/cbox-1.0.13-beta1.zip)

**Comment by boonebgorges** [comment]
Thanks, @r-a-y!

**Comment by r-a-y** [comment]
@boonebgorges - GES wasn't updated to use v3.7.0 in v1.0.13.

I guess we can make this part of v1.0.14.

**Comment by boonebgorges** [comment]
![facepalm](https://cloud.githubusercontent.com/assets/246627/19671474/996aef8c-9a34-11e6-86c9-a2c8574cdd41.jpg)

**Comment by r-a-y** [comment]
Closing this as we released v1.0.13 awhile back.
