### ISSUE TITLE
Support `network` flag to determine if a CBOX plugin should be network-activated

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/commons-in-a-box#117]
Currently, CBOX network-activates all its dependent plugins.

This has resulted in some issues where it is undesirable for certain plugins to be active across the entire network such as bbPress (see #105),

To remedy this, the `CBOX_Plugins::register_plugin()` method should fully support the `network` flag and refactor the codebase to make this happen.

One problem I'm running into is a UX issue on the CBOX Plugins Dashboard.  Since all CBOX plugins are already network-active before this refactor, what happens when we decide to set a plugin like bbPress to `network = false`?

Currently, this would mean that the green checkmark would be displayed on the CBOX Plugins Dashboard since `is_plugin_active()` is `true` if the plugin is either network-active or active on the main site.  I feel like in this case, we should display an inline notice saying something to the effect of `It looks like bbPress is network-active, however CBOX recommends only activating bbPress on the main site.  Feel free to network-deactivate bbPress`.  What does everyone think?

Also, what do we do for people upgrading to the newest version of CBOX where we have set the `network` flag to false for various plugins where these plugins were previously `true`?  Do we force network-deactivate the plugin and then activate the plugin on the root blog?  This seems like overstepping our boundaries.  Perhaps the proposed inline notice is enough?

@boonebgorges could use your feedback here.

----

TODO:
- [ ] Add table row notice if plugin is network-activated, but our plugin spec is set to `network = false`
- [x] Handle admin bar menu registration for plugins set to `network = false`, but require some shim code to work properly on multisite installs (BuddyPress Docs, bbPress). (See commit 3713f32)
- [x] Handle notification formatting for plugins set to `network = false`, but require some shim code to work properly on multisite installs (only looks like this applies to bbPress - see commit 9858001).

**Comment by christianwach** [comment]
FWIW @r-a-y I've found that it's *only* bbPress that people don't want network active - and usually because they are confused at the visibility of the bbPress CPTs on sub-site wp-admin pages.

**Comment by r-a-y** [comment]
Thanks for the reply, @christianwach.

We have plans to support more plugins and different configurations, so this wouldn't be just specific to bbPress.

**Comment by christianwach** [comment]
@r-a-y Understood, just relaying feedback from the people I know who use CBOX.

In terms of UX, perhaps there needs to be a new "Plugin Review" screen? I suspect the tricky bit would be explaining its function to relatively non-technical people.

**Comment by r-a-y** [comment]
In addition to bbPress, I can also see the following plugins being set to `network = false`:

- BP Group Announcements
- BuddyPress Docs
- BuddyPress Docs Wiki add-on
- BuddyPress Reply By Email
- Custom Profile Filters for BuddyPress
- External Group Blogs
- Invite Anyone

bbPress and BuddyPress Docs would need some extra code to set their respective WP admin bar menus when not on the main site though.  This could probably be added to CBOX as a code snippet.

**Comment by boonebgorges** [comment]
>  I feel like in this case, we should display an inline notice saying something to the effect of It looks like bbPress is network-active, however CBOX recommends only activating bbPress on the main site. Feel free to network-deactivate bbPress. What does everyone think

This sounds like the right path. I wouldn't want to automatically modify people's configurations (ie by network-deactivating bbPress and reactivating it on the main site), even if we thought we were "fixing" something.

> bbPress and BuddyPress Docs would need some extra code to set their respective WP admin bar menus when not on the main site though. This could probably be added to CBOX as a code snippet.

Good point. (See also the notification-formatting issue we've discussed in the context of bbPress.) Some of the plugins you've listed might have `Network: true` in their headers - I can't recall. If so, it can generally be removed - feel free to send PRs.

**Comment by boonebgorges** [comment]
@r-a-y I'm moving this out of the milestone, with the understanding that one of the todos above still remains. Feel free to close if that item's no longer relevant, or if it's already done. Thanks!

**Comment by r-a-y** [comment]
@boonebgorges - For the remaining item in this ticket, I wanted to add a table row notice if a plugin is network-activated, but our CBOX plugin spec says that it shouldn't be.  See commit 587fc1c.

This is what it looks like:

![network-activate-notice](https://user-images.githubusercontent.com/505921/63414673-dc2a4780-c3eb-11e9-8775-c0a63f99d4b5.png)

Clicking on the `Change` link will network-deactivate the plugin in question, while also enabling it on the main site if needed.  Feel free to change the copy for the table row notice to something more palatable.

**Comment by boonebgorges** [comment]
This looks great! Thanks, @r-a-y .
