### ISSUE TITLE
Package: OpenLab

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/commons-in-a-box#120]
We are going to be adding a new package for v1.1.0, based on a collaboration with City Tech and inspired by their [OpenLab](https://openlab.citytech.cuny.edu/) site.

This issue is to track the development of this package.

For more info on what a package is, see #119.

**TODO:**
- [x] Categorize plugins into two sections -- Community Features and Member Site Plugins. (See commits d4a2d55, e026a5d)
- [ ] Update `documentation_url` for BP Event Organiser

**Comment by r-a-y** [comment]
@boonebgorges - Can you provide a link to the Braille plugin as mentioned in the plugin manifest?

I'm not sure if the one on the wp.org repo is the right one:
https://wordpress.org/plugins/braille/

**Comment by mkgold** [comment]
Hi Ray -- I believe that is the correct Braille plugin.

**Comment by boonebgorges** [comment]
Yeah, that's it, @r-a-y.

Sorry for the lack of response! GitHub has been randomly eating my email responses for the last month or two. Maybe they should switch to RBE.

**Comment by r-a-y** [comment]
Thanks for confirming, @mkgold and @boonebgorges.

About packaging the OL theme and the CBOX-OL Core plugin for testing, since both plugins are private on Github, I'll need to bundle them into the CBOX plugin for now.

@boonebgorges - I think what I'll do is attach a ZIP file of the plugin to this ticket (or on Basecamp) and update it every once in a while when we need to get the team to test out functionality.  The reason for this is I'd rather not add binaries to the Git repo.  I guess the alternative is to add them into a separate branch if we needed to.  Once we do this, we'll also need to ensure that the OL theme and the OL core plugin version numbers are bumped.

**Comment by mkgold** [comment]
Hi @r-a-y & @boonebgorges -- FYI, I've confirmed with the plugin creator that this is the latest version. He recognizes that it needs an update and is checking with his team to see how much work that would be; I may help with the costs to get it up to date.
