### ISSUE TITLE
openlab package should require multisite

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#122]
There should be some sort of mechanism for a package to declare that it requires Multisite, and the openlab package should have it set to `true`.

This flag will presumably have a couple of effects:

- On the package-picker panel, prevent selecting a MS-required site when MS is disabled. Perhaps the option could be greyed out, or perhaps you could be given a notice as part of the "Are you sure?" dialog you see after clicking Install. Either way, we should link to resources that explain how to install Multisite - I don't think we want to mess with doing this ourselves (in many cases, it won't be possible anyway due to filesystem permissions)
- When an MS-required package has been selected and installed, have some sort of failsafe mechanism to ensure that MS is running before loading the system. This would be just in case the user has disabled multisite for some reason. Though, now that I think about it, I'm not sure we really need anything here: either way, the end result would be more-or-less complete disabling of the site, so we may as well let it fatal. What do you think?

**Comment by boonebgorges** [comment]
Related: #117

**Comment by r-a-y** [comment]
Is there a reason why the OpenLab package should be a multisite-only package?

Is it because of the portfolios feature requiring a sub-site?  If so, would it be possible to load the portfolios feature conditionally if multisite is enabled?

**Comment by boonebgorges** [comment]
It's not just portfolios. Most groups have linked sites, a fact that a 
lot of the UI depends on.

Beyond the technical aspects, I think the OpenLab team sees Site 
functionality as central to the experience of using the OpenLab as a 
teaching platform.

If you think it's difficult or unwise for a package to *require* 
multisite, it's probably not too technically difficult to uncouple (or 
at least wrap in is_multisite()) the MS-dependent parts. The 
documentation/install process would then strongly suggest MS for the 
best experience, rather than requiring it.

**Comment by r-a-y** [comment]
It's not too technically demanding to make a package MS-only, I just thought it would be nice because not all sites will use multisite.

Have you discussed this with the team for feedback?  I'll do whatever is decided.

**Comment by mkgold** [comment]
FWIW, I think that multisite is a basic part of the model. I would suggest that we require MS unless someone can think of a compelling use case for a single-blog version

**Comment by boonebgorges** [comment]
Yeah, I think we discussed it as a team in an earlier stage, and we 
decided that it'd be easier to support (documentation, training, etc) if 
we required Multisite - no need to say "the following is only relevant 
if MS", etc. Given the centrality of multisite to the teaching model, 
it's not worth the effort to fragment the support.

**Comment by r-a-y** [comment]
I've added the ability for packages to determine if they can only active on multisite installs in commit 31cd800.

This is what it looks like:

![Screenshot of network-only package](https://cloud.githubusercontent.com/assets/505921/25055413/867b3d40-2117-11e7-803e-3a971cb3a14d.png)
