### ISSUE TITLE
WP-CLI updater

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#129]
As part of a conversation we're having with Reclaim Hosting about having a semi-automated install/update process for WP + CBOX, the idea came up of a CBOX-specific update command. This command would allow the admin (or a bash script) to process updates for all CBOX-controlled plugins and themes, without having to use the WP Dashboard UI. It seems to me like it'd be a useful feature even independent of Reclaim/Installatron integration.

@r-a-y Can you take a moment to think about how hard this would be? I'm thinking it'd look something like this:
- User calls `wp cbox update` or something like that
- Our CLI method pulls up a list of available plugin + theme updates, using the same internal methods currently used for showing the "You have pending upgrades" admin notice
- We then run the updates, either using some internal WP functionality (I'm unsure how hard that'd be) or perhaps by using `WP_CLI::runcommand( 'plugin update' )` https://make.wordpress.org/cli/handbook/internal-api/wp-cli-runcommand/. See eg https://github.com/cuny-academic-commons/wp-cli-cac/blob/5a9f8f364daab5722ed204637b7a5d82e1722f67/wp-cli-cac.php#L172

I'm happy to collaborate on this, but I wanted to get your initial reaction first, especially since you'll have a quick idea of how easy it'll be to pull up the list of available updates. Thanks!

**Comment by r-a-y** [comment]
I'll look into it.  Makes sense that there should be a WP-CLI module for CBOX.

Might have to refactor some code in order to make this work.

I'll see if I can glean anything from `wp plugin update --all`, which is something that is similar to what we need.  That, plus the theme update.

**Comment by boonebgorges** [comment]
Excellent, thanks! The main thing here is to get a list of available updates - we can copy from wp-cli-cac or somewhere else for most of the other logic.

**Comment by boonebgorges** [comment]
I've been playing with this over the last few days, and it's really awesome - thank you for your work on it!!

**Comment by r-a-y** [comment]
I think I've done what I wanted to do as far as `wp cbox update` command is concerned.

I still want to get a `wp cbox install` command in sometime during the beta period or afterwards.  I'll see what I can do. See #142.
