### ISSUE TITLE
commonsinabox.org "Who is currently using CBOX?" FAQ update

### ISSUE THREAD

**Issue by modelm** [cuny-academic-commons/commons-in-a-box#130]
http://commonsinabox.org/documentation/faq has some out-of-date info. I propose changing the following:

> Who is currently using CBOX?
> For an example of Commons In A Box, check out the CUNY Academic Commons.  In January, 2013 the MLA Commons will officially launch, and be the second Commons In A Box installation. ...
> 

To:

> Who is currently using CBOX?
> For an example of Commons In A Box, check out the [CUNY Academic Commons](http://commons.gc.cuny.edu/).  In 2013 the [MLA Commons](https://mla.hcommons.org) officially launched as the second Commons In A Box installation.  It has since become one of several society networks in the largest CBOX install to date, [Humanities Commons](https://hcommons.org). ...

If there is a better place to report this, or if I can offer something more useful like a PR, please let me know.

**Comment by boonebgorges** [comment]
@vothsco Could you take care of this please?

**Comment by r-a-y** [comment]
Looks like this change was made on cbox.org.  Going to close this out!
