### ISSUE TITLE
Strategy for including cbox-openlab-core

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#131]
Hi @r-a-y - Wondering whether you have thoughts about how best to include the `cbox-openlab-core` plugin. 

Presumably, the `openlab-theme` theme will work just like the existing `cbox-theme`. When packaging for release, the zip will be pulled from GitHub. When installing, it'll be put in place during the theme install step of CBOX installation.

The `cbox-openlab-core` plugin is different because it's required for `openlab-theme` to work. I built it that way mostly for separation of concerns - it does stuff mostly related to back-end management (creation of group and member types, and so on) that is not related to the theme. But `openlab-theme` won't run without it - it'll fatal. I see a couple options:

1. Convert the plugin to a library that will be included in `openlab-theme`. How this works during development/packaging is up in the air (we could keep it as a separate repo if convenient, and pull it together at build time). But it would mean that it's included in `openlab-theme` in the distribution. Advantage is that there's no dependency issues. Disadvantage is that the functionality can't be used by other themes in the future.

2. Make `cbox-openlab-core` a Required plugin for the `openlab` package.

Seems like 2 is probably the right way forward, but you're the expert :-D

**Comment by r-a-y** [comment]
Sorry for the late reply!

> 2. Make cbox-openlab-core a Required plugin for the openlab package.

I actually prefer this second option.  This was always my original intention.

The reason why I haven't registered `cbox-openlab-core` as a plugin for `openlab` yet is the Github repo for `cbox-openlab-core` is private (as is `openlab-theme`) and we need a public link for the openlab package to install via URL.

If we need to package something for internal testing, then we can zip up the contents of `cbox-openlab-core` and I can add the local ZIP filepath to the openlab package plugin list.

I haven't really followed the development between `cbox-openlab-core` and `openlab-theme`, so you know the internals better than anyone.  If you think option 1 is the way to go, it does add some work as you mentioned, but if this is better for the maintainability over the longhaul then let's go with that.

If you want me to take a look at the repos more closely, let me know and I can provide some feedback if that helps at all.

**Comment by boonebgorges** [comment]
Thanks very much for the thoughts, @r-a-y. I'm going to go ahead and open up both the openlab-theme and cbox-openlab-core repos. Could you please do the necessary work to integrate them into the installation process? I have a feeling there will be problems related to load order - there may be fatal errors, and there may be problems with the network-active cbox-openlab-core running its installation routine before openlab-theme is active on the main site - but I'll be able to work my way through these more clearly after I see how they're pulled in by the installation routine.

**Comment by boonebgorges** [comment]
(if it wasn't clear, I'm agreeing that we should go with option 2 :) )

**Comment by r-a-y** [comment]
> I'm thinking increasingly that option 1 may be the way to go at first. I know for a fact that openlab-theme won't run without cbox-openlab-core. But it's also likely that cbox-openlab-core requires openlab-theme - I'm not 100% sure, but I know that I haven't been very careful to keep things separate.

I'm currently looking into this and you are correct that `cbox-openlab-core` requires `openlab-theme` during the OL installation process.

I'm going to send some PRs your way so CBOX doesn't fatal during the install phase.  But before I do, I need to compare what a typical OpenLab site is supposed to look and function like vs. what I'm currently getting.

Can you set me up with an account on the openlabdev testing site?  I don't believe I have an account on there.

The installation problem is similar in some respects to the issue with the GES email post type not being installed correctly during CBOX install:
https://github.com/cuny-academic-commons/commons-in-a-box/issues/133

I now understand why WordPress does not auto-activate plugins directly after bulk-installation due to some plugins needing to run an installation routine before another's!

**Comment by boonebgorges** [comment]
> I now understand why WordPress does not auto-activate plugins directly after bulk-installation due to some plugins needing to run an installation routine before another's!

Those who don't know history are doomed to repeat it. :pulling_hair_out:

I've just created an account for you on openlabdev.commonsinabox.org. Let me know if you didn't get the credential-reset email.

Thanks in advance for any PRs. It's likely that the `Install` class will need to be fired on the first pageload *after* activation, but anything you can do to alleviate the situation - without going crazy in my tangled code! - would be welcome.

**Comment by r-a-y** [comment]
Most of the work for this was done in this ticket - https://github.com/cuny-academic-commons/cbox-openlab-core/pull/1

Going to close this one out.
