### ISSUE TITLE
Accessibility review

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#134]
See cuny-academic-commons/openlab-theme#168, etc. Would be nice to be passing a basic WAVE review.

**Comment by r-a-y** [comment]
Are we only concerned about fixing WAVE errors?  Or do we want to fix both errors and alerts?  I would say we should only fix errors.

**Comment by boonebgorges** [comment]
Yeah, just errors. There are probably many dozens of alerts. Errors are generally missing form labels, or missing alt attributes, things that are probably easyish to fix :)

**Comment by boonebgorges** [comment]
Sweet! The dashboard interface could probably use a review too (which is more in the context of this repo) but it's less critical.

**Comment by boonebgorges** [comment]
Let's do a review of Dashboard interfaces for 1.2 if possible.

**Comment by boonebgorges** [comment]
I've taken a pass through the CBOX-OL panels and pushed up a number of fixes.

There are still some contrast issues, but they're not totally straightforward to solve. A good deal of them have to do with inactive/disabled buttons, but even WP core UI generates WAVE errors in these cases, so it wasn't obvious how to adapt.

**Comment by boonebgorges** [comment]
Let's call this good for 1.2.0. We can do another round for the next release if need be.
