### ISSUE TITLE
Nouveau considerations

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#135]
When we pin BP 3.0+, we will need to be sure that cbox-theme properly announces that it requires bp-legacy, not bp-nouveau. I'm not totally sure how this will work, given that cbox-theme doesn't use theme compatibility (I'm not even sure whether this makes a difference). In any case, we could either make the template-pack requirement part of the cbox "package" manifest somehow, or just have a routine that runs during installation that sets the template-pack in the database. (The latter is obviously easier.) ccing @r-a-y for any thoughts.

**Comment by r-a-y** [comment]
I think we don't have to worry about this.

When we made the change in `cbox-theme` to bypass BP's theme compatbility in BP v1.7, that should be enough:
https://github.com/cuny-academic-commons/cbox-theme/commit/c5942c5dfc654b32d722ff72b96c672cd765fc8d

When we bypass BP theme compatibility, this should stop bp-legacy and bp-nouveau from loading, but, you're right to be extra cautious!

**Comment by boonebgorges** [comment]
Gotcha, I think you're right! Thanks for bringing some sanity to bear :-D

**Comment by boonebgorges** [comment]
This did turn out to be an issue in openlab-theme - see https://github.com/cuny-academic-commons/openlab-theme/issues/237. Still not an issue here, I think, because we don't use theme compat.
