### ISSUE TITLE
RBE bump?

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#137]
Do we need an RBE bump? No problem if it's not necessary - it's just been a while.

**Comment by r-a-y** [comment]
I'll bump RBE, but I'll be doing this later tonight.

Are we starting testing tomorrow?  If so, I should be ready by then.

**Comment by r-a-y** [comment]
Added in commit 696ef6e.

**Comment by boonebgorges** [comment]
Thank you!!
