### ISSUE TITLE
Landing page/URL for after automatic install

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#138]
This is specifically for Reclaim Hosting, but could be more general. After an automated installation of WP + CBOX (ie, not through the WP Dashboard), a system like cPanel may want to send the user to a wp-admin URL that will initiate the CBOX installation routine (starting with the package picker). Do we already have a URL that will trigger this? If not, could we have a URL parameter or something?

**Comment by r-a-y** [comment]
The package picker URL is the same as the CBOX admin dashboard - `/wp-admin/network/admin.php?page=cbox`

Assuming that we want sites to use CBOX-OL, we'll also need to ensure that the WP site is set up as a network install to fulfill the CBOX-OL requirement.

Do we want the site admin to pick the package, or do we want it to default to CBOX-OL?  If we want it to go straight to CBOX-OL, we'd need to set a marker in the DB.

**Comment by boonebgorges** [comment]
> The package picker URL is the same as the CBOX admin dashboard - /wp-admin/network/admin.php?page=cbox

Great, this is perfect.

> Assuming that we want sites to use CBOX-OL, we'll also need to ensure that the WP site is set up as a network install to fulfill the CBOX-OL requirement.

Yes, this'll be on the host. I've already let Reclaim know about requirements.

> Do we want the site admin to pick the package, or do we want it to default to CBOX-OL? If we want it to go straight to CBOX-OL, we'd need to set a marker in the DB via some URL parameter.

Nah, for now we are sending them to the picker, and they can decide.

Thanks for the quick response! I think nothing else is required here.
