### ISSUE TITLE
PHP 7.2 deprecated functions

### ISSUE THREAD

**Issue by bdolor** [cuny-academic-commons/commons-in-a-box#141]
In a PHP 7.2 environment, on initial plugin load, php issues warnings about deprecated `create_function()` functions. 

- https://github.com/cuny-academic-commons/commons-in-a-box/blob/master/loader.php#L125
- https://github.com/cuny-academic-commons/commons-in-a-box/blob/master/loader.php#L126

![image](https://user-images.githubusercontent.com/2048170/41127857-12b3389c-6a61-11e8-9b83-b0678c55716e.png)

ref: https://secure.php.net/manual/en/migration72.deprecated.php#migration72.deprecated.create_function-function

**Comment by r-a-y** [comment]
This is fixed in our developmental version of CBOX v1.1.0, but I've just backported the fix to `1.0.x` branch in commit d121994.

Expect this in our next maintenance release for CBOX v1.0.x in the next month or so.
