### ISSUE TITLE
Installation > Recommended Plugin Installation Step

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#145]
If users uncheck "Events" because they don't want to install it, the text on the button says "Install".  It should say "Continue".  This is a small bug, but I'm reporting it so we don't lose track.   cc: @charliemedwards

Thanks!

<img width="1271" alt="eventsunchecked" src="https://user-images.githubusercontent.com/7189824/45920968-57047e80-be7a-11e8-8e83-eb7254ef41e2.png">

**Comment by r-a-y** [comment]
Thanks for the report, @bree-z.  Should be fixed as of commit 0c8479c.

@boonebgorges - Can you pull this latest change when you have the chance?

**Comment by boonebgorges** [comment]
Done.

**Comment by r-a-y** [comment]
Closing this one out.
