### ISSUE TITLE
Plugin version updates for 1.1.0

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#149]
I'll use this thread to track plugin version updates for 1.1.0

**Comment by boonebgorges** [comment]
@r-a-y Is RBE ready for a bump? If so, could you do it?

**Comment by boonebgorges** [comment]
I've finished this review and will leave the ticket open for the RBE question.

**Comment by r-a-y** [comment]
I'll bump RBE tonight.

**Comment by boonebgorges** [comment]
Thanks, Ray!

I'm going to leave this ticket open as a reminder to bump our subpackages (`openlab-theme` etc) as part of the release.
