### ISSUE TITLE
"You can manage your CBOX plugins" notice shouldn't show for non-super-admins on subsites

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#152]
From https://github.com/cuny-academic-commons/openlab-theme/issues/276#issuecomment-432447816:

> One last thing is that now when I go to the plugins list on a subsite when logged in as a regular non-superadmin member (e.g. http://openlabdev.commonsinabox.org/writing-politics-sp2018-pol345/wp-admin/plugins.php logged in as testfaculty, the admin for that subsite), I see a message at the top that probably shouldn't be there:

The capability linked to this message should be the same as the capability required to view the commons-in-a-box admin tools - so `manage_network_plugins` (I think?) instead of `activate_plugins`. Not sure how easy or wide-reaching a change this is - if it's simple, feel free to move back to an earlier milestone.

**Comment by r-a-y** [comment]
Argh, not sure why I never caught this issue before!  Fixed in commit dcf1374.

Thanks @bree-z for uncovering this bug.

**Comment by boonebgorges** [comment]
Thanks, @r-a-y !
