### ISSUE TITLE
Step 3 in group creation doesn't display invitation interface

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#161]
Hi Boone - This is another user-reported bug, but I wasn't able to reproduce it on openlabdev.commonsinabox.org.  Let me know if there's another way I can help troubleshoot, but below I'm posting the screenshots he included in his report for step 3 and then what he sees after clicking 'Finish' in step 3.  I asked if there are other user accounts on the site, and he said that there are about a half dozen users, mostly super admins.  His post is here: https://commonsinabox.org/groups/openlab-help-support/forum/topic/create-clone-course-or-other-group-types-error-on-step-3/ 

![step3](https://user-images.githubusercontent.com/7189824/49550815-e8509200-f8ba-11e8-9471-04c5b67678d1.png)

![after_step3](https://user-images.githubusercontent.com/7189824/49550894-277ee300-f8bb-11e8-9179-f094b4827ecd.png)

**Comment by boonebgorges** [comment]
Thanks, Bree. I'm going to shut this ticket until there's reason to believe it's a bug. I'll respond on the thread.
