### ISSUE TITLE
File upload warning message

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#165]
A user [has reported](https://commonsinabox.org/groups/openlab-help-support/forum/topic/warning-on-group-file-upload-page/) the following warning message when uploading files.  It looks like he is able to successfully upload the file. 

Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/themes/openlab-theme/buddypress/groups/single/documents.php on line 14

The screenshot he included is attached, and he says: "The console in this case is only showing a couple of JQMIGRATE warnings that actually appear on every page."

I'm not able to reproduce this on openlabdev.commonsinabox.org.  I'm able to upload files without a problem and don't see any warning messages.  

![cboxolfileuploaderrors](https://user-images.githubusercontent.com/7189824/50189695-543bed00-02f4-11e9-909e-fcac62a87ef2.png)

**Comment by boonebgorges** [comment]
Thanks for the ticket. I've fixed the error in the commit referenced above.
