### ISSUE TITLE
`menu_items` filter can be broken by notoptions

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#166]
This is a hairy bug, but the gist is that the filter at https://github.com/cuny-academic-commons/commons-in-a-box/blob/d9447ab90abc89bf94a39427f542459d5184ac00/includes/openlab/openlab.php#L83 doesn't apply properly in all cases, causing the Plugins menu to disappear for non-super-admins.

A bit more detail, as far as I understand it:
- The first time `current_user_can( 'activate_plugins' )` is called, it calls `get_site_option( 'menu_items' )`. If no value is found in the DB, it's added to `$notoptions` by `get_network_option()` and then run through the `site_option_menu_items` filter, which CBOX catches.
- The second time it's called, `get_network_option()` finds the option name in `$notoptions`, so it it returns the *default* value (which is an empty array in this case) *without running the `site_option_menu_items` filter. As such, CBOX doesn't filter it.

This could wreak havoc in various ways.

I've monkey-patched my installation to add the exact same filter to `default_site_option_menu_items`. This ensures that CBOX always filters the value. It's not terribly elegant, but this is largely a problem of the filter architecture of `get_network_option()` - not something we can easily fix.

@r-a-y Could you please weigh in on whether you think it's an acceptable solution?

**Comment by r-a-y** [comment]
> I've monkey-patched my installation to add the exact same filter to default_site_option_menu_items.

Thanks for the in-depth analysis, @boonebgorges.  You're correct!  Let's apply the same callback to the `'default_site_option_menu_items'` filter.

**Comment by boonebgorges** [comment]
Thanks for reviewing, @r-a-y !

**Comment by boonebgorges** [comment]
Looks like I didn't fix this properly. I need to use the `default_site_option_menu_items` filter rather than `default_option_menu_items`.
