### ISSUE TITLE
`wp cbox update all` doesn't update some things

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#167]
It looks like `wp cbox update all` doesn't update a few things. In my case, it ignores `buddypress` and `event-organiser`. Each of these is a special kind of plugin in the CBOX architecture, so I imagine that this special status is part of the cause of the problem.

This is not urgent, but if it's an easy fix, we could put into an earlier milestone.

**Comment by r-a-y** [comment]
@boonebgorges The way the `update all` command works is defined by the package plugin manifest.

Since we haven't bumped `buddypress` or `event-organiser` yet, then the `update all` command thinks everything is fine.  Once we bump the versions, you should be able to use the command as stated.

You can also update manually by using the regular `wp plugin update buddypress` WP-CLI command.

**Comment by boonebgorges** [comment]
I think that 28d2945 was the problem - regular plugins were updating OK, but the "dependencies" weren't - they were generating an invalid wp-cli command `wp update buddypress` or something like that (I think missing the `plugin` part of the command). Thanks for having a quick look!

**Comment by boonebgorges** [comment]
Related, I don't think that `wp cbox status` shows available BuddyPress updates. Definitely not critical, but if it can be resolved as part of this, it might be nice.

**Comment by r-a-y** [comment]
> Related, I don't think that wp cbox status shows available BuddyPress updates.

It should once the package plugin manifests are updated.  `wp cbox status` shows the update depending on the package, so make sure both package plugin manifests are updated.

Let me know if that doesn't work.

**Comment by boonebgorges** [comment]
Yeah, I think this was my mistake - I was on the wrong package :-/

**Comment by r-a-y** [comment]
No problem!  Looks like the plugins have been bumped.  Thanks!

Going to close this one out.
