### ISSUE TITLE
Grey 'My Profile' nav bar missing on group profile and other group pages 

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#170]
The grey nav bar with log in/out and My Profile links is missing on group profile and other group pages (Discussion, Docs, Files, etc).  It appears on the homepage and group directory pages.  

![myprofilenavbarhomepage](https://user-images.githubusercontent.com/7189824/52184865-fea99a00-27e6-11e9-8ead-432ed18197f4.png)

<img width="1207" alt="myprofilenavbarmissing" src="https://user-images.githubusercontent.com/7189824/52184866-fea99a00-27e6-11e9-84b5-40b828bf2e22.png">

**Comment by r-a-y** [comment]
@bree-z - I cannot duplicate this on the openlabdev site.  Can you test again?  I do see that there is a delay when the bar is displayed though.  It appears that the page needs to be fully loaded for the bar to show properly.

What browser are you testing with?

**Comment by bree-z** [comment]
Thanks, @r-a-y !  I tested and found the issue on Chrome and Firefox, but this looks fine to me now in both browsers.
