### ISSUE TITLE
Text formatting buttons don’t appear for group discussion forums

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#171]
When creating a new topic or replying to an existing topic, the buttons for formatting and styling text (e.g. bold, ital, link, etc) don’t appear.  

E.g.: https://openlabdev.commonsinabox.org/groups/writing-about-winter/forum/ 

<img width="1190" alt="discussionformattingbuttonsmissingcboxol" src="https://user-images.githubusercontent.com/7189824/52184909-69f36c00-27e7-11e9-8afd-ef20a0ed3e5d.png">

Discussion with formatting buttons:

<img width="966" alt="discussionformattingbuttonsol" src="https://user-images.githubusercontent.com/7189824/52184915-7677c480-27e7-11e9-90b8-30f783e04b6c.png">

**Comment by r-a-y** [comment]
@bree-z - I cannot duplicate this on the `openlabdev` site.  Tested with Chrome.

**Comment by bree-z** [comment]
I can no longer duplicate this one either.  Thanks!
