### ISSUE TITLE
Docs: Text in Content box is white when editing

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#172]
- When creating a new doc, I clicked in the ‘Content’ box but couldn’t see my cursor.  
- I pasted in some lorem ipsum text and some red underlines for misspelled words appeared.  I could see the text in white when I highlighted it with my cursor.  
- After clicking Save, it appeared in black.
- When I edit I see the same thing with white text.  

E.g.: https://openlabdev.commonsinabox.org/groups/writing-about-winter/docs/

<img width="1195" alt="docwhitetext" src="https://user-images.githubusercontent.com/7189824/52184995-4bda3b80-27e8-11e9-8f28-d4d9c2458a1c.png">

<img width="1228" alt="doctexthighlighted" src="https://user-images.githubusercontent.com/7189824/52184997-50065900-27e8-11e9-8498-2d5c56f20205.png">
 
After clicking Save:

<img width="1180" alt="docafterpublished" src="https://user-images.githubusercontent.com/7189824/52185001-5d234800-27e8-11e9-9050-9fc20f4a247a.png">

**Comment by r-a-y** [comment]
@bree-z - I also cannot duplicate this on the `openlabdev` site.  Tested with Chrome.

**Comment by bree-z** [comment]
Thanks, @r-a-y .  I can no longer duplicate on Chrome or Firefox!
