### ISSUE TITLE
Braille plugin: Text isn't being translated on WP subsites

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#174]
Hi Boone, 

When using the [braille] [/braille] shortcodes on a subsite, the text in between the shortcodes isn't being translated, and I just see a message that "Local translation is not supported at the moment." e.g.: https://openlabdev.commonsinabox.org/writing-about-winter/2019/02/05/braille-3/ 

Apologies if I'm just being dense about how to do this with the block editor.  I tried a few different ways, with the classic editor, as a paragraph block, and as a shortcode block, but none seem to work.

Thanks!

![screen shot 2019-02-05 at 10 41 44 am](https://user-images.githubusercontent.com/7189824/52284646-cfa03f00-2932-11e9-8a5c-e8b5e589e51d.png)

![screen shot 2019-02-05 at 10 42 19 am](https://user-images.githubusercontent.com/7189824/52284647-cfa03f00-2932-11e9-9b6f-b1964d62f6a6.png)

**Comment by boonebgorges** [comment]
This is not a problem with the block editor, but stems from the fact that the Braille plugin's settings aren't, by default, networkwide. So a proper configuration on the main site https://openlabdev.commonsinabox.org/wp-admin/options-general.php?page=edu-umd-mith-braille doesn't automatically get transferred to subsites. Could you please mirror the configuration on the subsite and verify that it fixes the issue for you?

Assuming I'm correct, I'd suggest that this is a documentation issue in the short term. In the medium term, we can explore how Braille settings might be handled more gracefully across a network, but this is something that will take some triangulation between the needs of CBOX and the needs of existing Braille plugin users.

**Comment by bree-z** [comment]
Thanks, Boone!  Yes, mirroring the configuration on the subsite fixed the issue.  

And I think adding this to our documentation makes sense.  Thanks!
