### ISSUE TITLE
cbox-theme should not reference deprecated "topic button" args

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#178]
See screenshot:
![after group creation](https://user-images.githubusercontent.com/246627/53579651-9167fb00-3b3f-11e9-8f6c-fe69ac73cebe.png)

**Comment by boonebgorges** [comment]
cc @vothsco

**Comment by r-a-y** [comment]
Thanks for the report, @vothsco.

Fixed in https://github.com/cuny-academic-commons/cbox-theme/commit/cfef0ab7ce32e329cef3eb2be80d7e5a028b5a27
