### ISSUE TITLE
wp cbox theme update unzip to wrong location

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#179]
I just experienced the following:

1. Updated `commons-in-a-box` to 1.1.1 on a site running Classic
2. Used `wp cbox theme update` to update theme (did plugins separately and worked great)
3. Theme was unzipped to `wp-content/themes/cbox-theme-1.1.1` instead of `cbox-theme`

Upgrading through the Dashboard worked fine, so I assume it's a CLI issue. I have not tried to reproduce a second time. @r-a-y Could you have a look?

**Comment by boonebgorges** [comment]
Actually, I have a revision: plugin updates don't totally work either via CLI.

It seems to be an issue with plugins/themes that are shipped as zips. Items downloaded directly from wordpress.org are properly renamed. Those coming from zips are not.

**Comment by r-a-y** [comment]
> It seems to be an issue with plugins/themes that are shipped as zips. Items downloaded directly from wordpress.org are properly renamed. Those coming from zips are not.

Ahh, gotcha!  That would make sense.  I didn't test the update command with packaged ZIP files!

I'll fix this up for 1.1.2 with the same logic used in the admin dashboard.

**Comment by r-a-y** [comment]
@boonebgorges - I've added some logic so bundled ZIP files should be renamed properly when using WP-CLI.  I've tested the changes in both WP-CLI and the admin dashboard and it looks like everything is working.

Can you verify when you have the chance?

**Comment by boonebgorges** [comment]
Thanks, Ray! I'll have a look soon.

**Comment by r-a-y** [comment]
Closing this one out as I've retested the `wp cbox update plugins` command with a packaged ZIP and updating works.
