### ISSUE TITLE
openlab-theme doesn't properly render blog posts/pages

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#183]
See report at https://github.com/cuny-academic-commons/openlab-theme/issues/285

**Comment by boonebgorges** [comment]
I've done some work to make this minimally functional. See https://openlabdev.commonsinabox.org/blog/2019/08/14/this-is-a-regular-wordpress-post/

The OpenLab itself doesn't have 100% styling coverage for this sort of thing, so I'm working with limited source material. There's no time to do a full pass on this page for the next release, but the changes I've made here will allow it to be at least usable (before it didn't work at all).

I'll start a new ticket for improving the appearance of this page.

**Comment by bree-z** [comment]
This seems fine to me.  FWIW, I did one more test here: https://openlabdev.commonsinabox.org/blog/2019/08/19/main-site-blog-post
