### ISSUE TITLE
Email notifications not being sent for new site creation

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#184]
This issue was first reported by a CBOX OpenLab admin in [this forum thread](https://commonsinabox.org/groups/openlab-help-support/forum/topic/potential-confusion-when-user-creates-public-project-and-hidden-associated-site/), and I've confirmed it on openlabdev.commonsinabox.org. 

When I create a group with an associated site, I don't get an email notification that the site was created.  I tested with a few different site privacy settings, but that doesn't seem to matter.  I get notifications for site posts and comments (including the WP comment notification).  

See, for example:

https://openlabdev.commonsinabox.org/groups/colorful-doors/

Thanks!

**Comment by boonebgorges** [comment]
> When I create a group with an associated site, I don't get an email notification that the site was created.

*I* got email notifications about these sites. In WP multisite, only the site administrator gets a notice when a new site is created. There's nothing in BP or in CBOX that would trigger an email on site creation. So I think this is an unimplemented feature rather than a bug.

**Comment by bree-z** [comment]
Aha!  Sorry for the false report.  The OpenLab has this feature enabled, so I assumed it was the default for all installations.  :)
