### ISSUE TITLE
BP Docs: new duplicate docs created after editing/saving an existing doc

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#185]
Hi Boone, 

When I edit an existing doc and then save the doc, a duplicate doc is created with -2 appended to the URL (or -3, etc, each time I edit).

* I created a new doc called 'Summer Doc': https://openlabdev.commonsinabox.org/groups/writing-about-winter/docs/summer-doc
* I then edited the doc and saved my changes.  After saving changes, the doc URL became https://openlabdev.commonsinabox.org/groups/writing-about-winter/docs/summer-doc-2 and when I view all docs I see two docs with the title 'Summer Doc'.  
* If I edit the doc again, I get a third copy: https://openlabdev.commonsinabox.org/groups/writing-about-winter/docs/summer-doc-3/

Thanks!

**Comment by boonebgorges** [comment]
I believe I've tracked this down and fixed it.

**Comment by bree-z** [comment]
This looks good, thanks!
