### ISSUE TITLE
Exclude "Group Home" link from site nav when the group is hidden

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#187]
The "Group Home" nav link should be excluded when the group is hidden (and the current user doesn't have the ability to view it). 

This will prevent users from getting a "Page not found" message when they click on the "Group Home" link in the site nav, if they're viewing a public site attached to a hidden group.

Thanks!

**Comment by boonebgorges** [comment]
Reference: https://github.com/livinglab/openlab/commit/9b1912829dd896906faa8e0daf45914b0b9d65fd

**Comment by bree-z** [comment]
This looks good, thanks!

I see the link when logged in as a member of the group, but not when I'm not logged in or not a group member.
