### ISSUE TITLE
Broken links for "Recent Docs" and "Recent Discussions"

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#189]
When a main site is installed in a directory, e.g.: https://globalx.junkanooingb.com/education the "Recent Docs" and "Recent Discussions" links on a Group Home page don't include the directory.  

The links to Docs and Discussion in the sidebar are correct, e.g., for [this course](https://globalx.junkanooingb.com/education/groups/sustainability-in-education), they are:

Docs: https://globalx.junkanooingb.com/education/groups/sustainability-in-education/docs/
Discussion: https://globalx.junkanooingb.com/education/groups/sustainability-in-education/forum/

But the "Recent" links appear to be missing the "education" directory:

Recent Docs: https://globalx.junkanooingb.com/groups/sustainability-in-education/docs/
Recent Discussions: https://globalx.junkanooingb.com/groups/sustainability-in-education/forum/

For reference: 

![RecentDocsDiscussion](https://user-images.githubusercontent.com/7189824/63289936-4a58f800-c28e-11e9-83e7-716ed9a0458d.png)

**Comment by boonebgorges** [comment]
Thanks for the detailed report! We should be able to sneak this into the current release. I've just pushed a fix.

**Comment by boonebgorges** [comment]
Actually, not sure how you're going to test this given our openlabdev site, which is not in a subdirectory. You'll have to take my word for it.
