### ISSUE TITLE
Classic: "Member Profile Default Tab" option vs. Nouveau's user front page option

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/commons-in-a-box#190]
CBOX Classic has an option under "CBOX > Settings" to set the Member Profile as the default tab.

If the CBOX Classic package is active and the site is _not_ using the CBOX Theme, that means BuddyPress theme compatibility is on and the Nouveau theme pack is enabled.

BP Nouveau has a customizer option to have a custom user front page:

![nouveau-user-front-page](https://user-images.githubusercontent.com/505921/63324066-cf87ef80-c316-11e9-80f6-6a1e5df4e7ae.png)

When this option is enabled, I think CBOX Classic shouldn't set the Profile tab as the default.

I've tentatively set this for 1.1.2 for now as I have the code ready to make this happen, but we might want to move this to 1.2.0 if this is deemed too big of a change for a maintenance release.

**Comment by boonebgorges** [comment]
Yeah, I think we should go ahead with this if it's an easy fix with no side effects.

**Comment by r-a-y** [comment]
Closing this one out.
