### ISSUE TITLE
Super admins don't see "Join," "Leave," or "Request Membership" buttons

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#193]
Hi Boone, 

This just occurred to me as a potential issue now that I've been seeing some actual CBOL-OL sites in action.  On the OpenLab, we keep our super admin accounts separate from the accounts we use for participating in groups, so it's never been a problem, but on other installs, the super admins may just have one account that they use for all activity.  

Currently, super admins don't see "Join," "Leave," or "Request Membership" buttons beneath avatars on a Group's Home page.

For example, logged in as testadmin/Tegan Adriani, I was not able to join [this public group](https://openlabdev.commonsinabox.org/groups/eng-1101-comd-1100-research-project/), except by invite, because I couldn't see a "Join" button.  Once I joined, I didn't see the "Leave" button beneath the group avatar, as shown below:

![screenshot-openlabdev commonsinabox org-2019 08 22-12_33_10](https://user-images.githubusercontent.com/7189824/63532815-8633cd80-c4d9-11e9-9a79-e0f53dc7261e.png)

**Comment by boonebgorges** [comment]
Thanks for the detailed report. For reference, this comes from a hardcoded check that hides the entire button area from admins. https://github.com/cuny-academic-commons/openlab-theme/blob/efff0326073a755aa13c77875b1fb1a868281195/buddypress/groups/single/group-home.php#L44 This should be reworked, but we'll need detailed tests for each kind of button - it's likely that each will need different treatment.

**Comment by boonebgorges** [comment]
I reviewed the buttons added here and it looks like join/leave/request is really the only relevant one, which means I don't think that any other work is required than to simply show the area for admins. I've done so and it's ready to test.

**Comment by bree-z** [comment]
This looks good, thanks!
