### ISSUE TITLE
More flexible "Group Home" nav links

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#195]
We currently add the Group Home links to site nav menus dynamically. These links can't be removed, reordered, or modified by end users. This feels limiting.

The impetus for adding the links in the first place is to reinforce the relationship between the site and the group. And we do it automatically so that the end user doesn't have to grok this relationship themselves (and navigate to the Menus section of the customizer, etc). I think we should continue to honor this motivation, but try for a more flexible system.

One idea is that, on site creation, we can populate this link as an actual nav menu item, so that later on, if the user wants to remove or change, they can do so via the normal channels. We could even make this slicker by adding 'Course Home' (group-type specific) to the Menus UI, which would make it easy for admins to re-add the item if they remove it at some point in the future. This could possibly be nested in its own 'CBOX OpenLab' section in the Menus UI. See mockup:

![Screenshot_2019-09-06_10-53-05](https://user-images.githubusercontent.com/246627/64441986-a3999780-d094-11e9-8b7a-553d2c3b1b58.png)

A different idea is to have a site-level toggle that allows site admins to disable the dynamically added Group Home nav menu item. The user could then turn it off, and then add a new nav item to replace it if they'd like. This is somewhat easier to build, but we'd need to find a place to put the toggle UI.

All of the above could also be applied to the dynamic "Home" link.

**Comment by boonebgorges** [comment]
Related: http://redmine.citytech.cuny.edu/issues/2677

I like my idea of creating proper nav items in these cases. This would give total control to site admins, and avoids the problem of designing/building a new Dashboard UI for network admins.

**Comment by boonebgorges** [comment]
See also http://redmine.citytech.cuny.edu/issues/2424

**Comment by boonebgorges** [comment]
A note that we will need some sort of migration routine or another kind of backward-compatibility tool if we go with this solution. What's proposed above would only apply to newly created sites. For existing sites, we'd either need to add the nav items in bulk, or we'd need to have some sort of internal flag that tells CBOX-OL to continue dynamically adding the items for old sites (perhaps until the next time the admin of those sites edits the nav menus, under the assumption that they could add the Profile and Home links themselves at that time).

**Comment by boonebgorges** [comment]
@Mamaduka Could you please begin looking at this? I think the main subtasks are:

1. Register a new subheader 'CBOX OpenLab' for the Menus panel
2. Register the nav menu items with WP. Here's the technique used in BP: https://buddypress.trac.wordpress.org/browser/tags/5.1.2/src/bp-core/bp-core-functions.php#L2524, https://buddypress.trac.wordpress.org/browser/tags/5.1.2/src/bp-core/bp-core-filters.php#L680, https://buddypress.trac.wordpress.org/browser/tags/5.1.2/src/bp-core/admin/bp-core-admin-functions.php#L743. We need `Home` and `group_home` links - see https://github.com/cuny-academic-commons/cbox-openlab-core/blob/master/includes/group-sites.php#L1721 for how they're defined currently. 
3. Stop forcing the items into the nav menu dynamically at https://github.com/cuny-academic-commons/cbox-openlab-core/blob/master/includes/group-sites.php#L1721
4. Think about what a post-upgrade migration routine would look like. I think it's: pull up a list of every group-site on the network, and add the default links. So the logic for add-default-nav-items-to-a-site should be broken out in such a way that it can be easily reused in the upgrade routine. (I'll open a separate ticket with questions about an upgrade routine.)
5. Think about how these new nav items fit into the clone-from-a-group-type-template logic that we currently use. Since all new sites are cloned from a template that's specific to the group site, I think that these new nav items should behave in the same way as other nav menu items: set them up the way we want them in the template site, and then they'll automatically be copied over properly during the existing nav_menu clone routines. It just needs to be thought through :-D

Thank you, and let me know if you have questions as you look through this.

**Comment by Mamaduka** [comment]
@boonebgorges maybe we can avoid post-upgrade routine and re-use the same [logic](https://github.com/cuny-academic-commons/cbox-openlab-core/blob/master/includes/group-sites.php#L1756) we have with "Home" link.

Since manually added "[ Group Home ]" nav menu items are just normal items, they will be copied to new sites. If the item doesn't exist we'll use fallback I mentioned above. What do you think?

**Comment by boonebgorges** [comment]
I'm not sure I understand the suggestion. Currently, all sites on a CBOX-OL network have a 'Home' link dynamically injected into their navigation. The proposal in this ticket is that we stop injecting this link, and instead put a proper nav link. But this nav link will only apply to not-yet-created sites; existing sites will no longer have the injected 'Home' and they also won't have the nav-menu 'Home'.

The specific code you've linked to *prevents* the injection of 'Home' when an existing 'Home' is found, but our problem here is that a site might not have 'Home' at all - not that there'll be a duplicate.

Maybe you mean something like: After 1.2.0, we can keep some dynamic logic that detects (a) whether a site was created before 1.2.0, and if so (b) whether it's missing a 'Home' link. If so, we would inject one, like we do now. Users who want to modify 'Home' on an existing site could add the nav menu item manually, at which point we'd stop injecting. (A hardcoded check for 'Home' would not work because of i18n but we could come up with something similar - to be safe, we could simply stop injecting the first time the primary nav menu is modified in any way.) This is similar in spirit to the code you've linked to, but it kinda does the opposite. Does that seem right?

Even with this suggestion, we would still need to run an upgrade routine on the *group-type template sites*, to ensure that *they* have the proper nav menu items. But this is only a small number of operations and can easily be run in the first pageload after upgrade.

**Comment by boonebgorges** [comment]
@Mamaduka There was a fix the other day on the OL related to nav items not being copied during cloning, which is sort of related to this ticket and should be merged to CBOX. Could you do that, and then add the 'Needs testing' label to this ticket?

**Comment by bree-z** [comment]
I think looks good, thanks! 

[Group Home] and Home links can be removed, added, and edited, and they are cloned properly. They're appearing correctly for new sites, as well as for older sites in all themes except Twenty Seventeen. 

I'm not sure if the Twenty Seventeen issue is related, but sites with this theme enabled don't have any menu at all, including old sites and new ones where the theme is changed from Twenty Sixteen to Twenty Seventeen.  See, for example:

https://openlabdev.commonsinabox.org/prehistoric-club/
https://openlabdev.commonsinabox.org/banitsa-fan-club/
https://openlabdev.commonsinabox.org/learningtoread/
https://openlabdev.commonsinabox.org/everest-project/
https://openlabdev.commonsinabox.org/runfar/

Thanks!

**Comment by boonebgorges** [comment]
Not sure about Twenty Seventeen. Locally I'm able to change to the Twenty Seventeen theme from Twenty Sixteen and the menus are preserved as expected. I'd suggest that it's unrelated to this current ticket, and probably linked to some specific thing about openlabdev.commonsinabox.org. In any case, debugging of specific themes is more than we can take on right now. So if you continue to experience this, perhaps you could open a new ticket and we'll look at it when we've got the time and resources.

**Comment by bree-z** [comment]
Sounds good, thanks Boone.
