### ISSUE TITLE
bbPress 2.6 issues

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/commons-in-a-box#199]
CBOX is currently on bbPress 2.5.14.

When we eventually bump our supported version to bbPress 2.6, we'll need to address some issues that will probably require hotfixes for CBOX:

- [x] Editing a forum post does not update (or create) corresponding activity item - https://bbpress.trac.wordpress.org/ticket/3328 (See commit 162f43e, df3dcd3)
- [x] Blog comment moderation settings are inherited for forum posts - https://bbpress.trac.wordpress.org/ticket/3352 (We'll probably want to at least override the comment link limit for logged-in users) (See commit 24dd367)
- [x] No template notice is displayed when a user's forum post is auto-moderated - https://bbpress.trac.wordpress.org/ticket/3353 (I can put in place a fix for BuddyPress forums, but if bbPress is used on a sub-site, I don't have a fix for that) (See commit 6353f8e)

**Comment by boonebgorges** [comment]
Thanks for your work on this!
