### ISSUE TITLE
Add to Portfolio

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#200]
The OpenLab team would like to port its 'Add to Portfolio' functionality to the CBOX-OL package.

I'll assign this ticket to @mamaduka once he's accepted my invite to the team :)

**Comment by Mamaduka** [comment]
@boonebgorges Currently, the feature is part of the [plugin](https://github.com/livinglab/openlab/tree/master/wp-content/plugins/ol-portfolio) with the "Import/Export" feature. Kinda made sense when I was building it for OpenLab.

Code is easily portable, but has following dependencies from OpenLab code:
`openlab_get_site_type()`
`openlab_get_user_portfolio_id()`
`openlab_get_site_id_by_group_id()`

Do you think we can easily replace them? I'm not familiar with CBOX codebase.

**Comment by boonebgorges** [comment]
Thanks, @Mamaduka. I forgot that the ol-portfolio tool depends at least in part on OL-specific functionality. This suggests that a wordpress.org plugin is not appropriate.

In general, I think the best strategy is to break the plugin out into its own repo; make it dependent on CBOX-OL rather than the OpenLab; and then build polyfills/filters as necessary to merge the changes back to the OpenLab.

For your specific functions:

`openlab_get_site_type()` - I don't think there's an exact function corresponding to this in CBOX. We have `cboxol_get_group_group_type()`, and we could add a `_get_site_group_type()` wrapper. Would you mind doing this and then sending a PR?

`openlab_get_user_portfolio_id()` - we have this https://github.com/cuny-academic-commons/cbox-openlab-core/blob/master/includes/portfolios.php#L32

`openlab_get_site_id_by_group_id()` - We have this one too https://github.com/cuny-academic-commons/cbox-openlab-core/blob/a45a9ad63fac3d4736c2357e88dfc0e02d9ef6fa/includes/group-sites.php#L23

Please don't hesitate to ask if you come across more instances or if you have more questions about the best way to proceed with the CBOXification of this tool :)

**Comment by Mamaduka** [comment]
Thanks for the feedback @boonebgorges.

I agree that separate repo for the OpenLab portfolio plugin makes more sense.

Will do a more thorough review tomorrow and post more questions.

**Comment by boonebgorges** [comment]
See #201 - both this feature and import/export are part of the https://github.com/livinglab/openlab-portfolio/ package.
