### ISSUE TITLE
Portfolio import/export

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#201]
The OpenLab team would like to include its custom import/export tool to CBOX-OL.

@mamaduka wrote this tool for OpenLab, and I'd like him to take the lead on porting it to the CBOX-OL package. I'm hopeful that not too many internal changes will be necessary to make it usable in CBOX: ensure i18n is done correctly, review that there's no hardcoded reference to OpenLab, maybe check for subdomain vs subdirectory issues. 

More significantly, we have to decide exactly how to include it in the package. It probably makes sense to break the plugin out into its own repo - either here or under `livinglab`? Then we can either (a) publish it in the wordpress.org repository and include it as a w.org plugin, or (b) leave it on GitHub and use our build process like we do for other GH-only plugins. See https://github.com/cuny-academic-commons/commons-in-a-box/blob/5b01636bb40e37ed693195795714928031e0d5bd/includes/openlab/plugins.php#L52 for an example.

**Comment by Mamaduka** [comment]
@boonebgorges I think `openlab-portfolio` [plugin](https://github.com/livinglab/openlab-portfolio) is ready to be added as a dependency. Should I make it a required or recommended plugin?

**Comment by boonebgorges** [comment]
Thanks! I've been reviewing the codebase and it looks like you've made most of the necessary changes. I opened a couple tickets for a few remaining items.

Let's make it required - I think it's a core piece of portfolio functionality for the OpenLab.
