### ISSUE TITLE
no ability to unban members

### ISSUE THREAD

**Issue by moui72** [cuny-academic-commons/commons-in-a-box#202]
If you kick and ban a group member, there's no interface for unbanning them.

The same is true for the OpenLab.

**Comment by boonebgorges** [comment]
This has been fixed in http://redmine.citytech.cuny.edu/issues/2438 and http://redmine.citytech.cuny.edu/issues/2478 on the OpenLab. Let's port these changes to openlab-theme as necessary.

**Comment by Mamaduka** [comment]
@boonebgorges will close this one. Both PRs are merged now.
