### ISSUE TITLE
"Additional Faculty" overhaul should be ported from OpenLab

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#207]
See cuny-academic-commons/openlab-theme#99, http://redmine.citytech.cuny.edu/issues/2019

**Comment by boonebgorges** [comment]
@Mamaduka I've added you as an Assignee here but please don't look at it until you've looked at your other tickets. The OL codebase is pretty confusing in this area, and I should probably attempt to take the first pass at merging to CBOX myself. But I might ask for your help if I get stuck :-D

**Comment by boonebgorges** [comment]
Needs discussion: The OpenLab has hardcoded that Clubs and Projects have 'Group Contacts', while Courses have 'Additional Faculty'. On CBOX-OL, we currently hardcode (more or less) that Clubs and projects get Group Contacts. We may want to rethink this a bit more holistically when merging Additional Faculty, because (presumably?) you don't want or need both field types on a given group type. Maybe a group-type setting along the lines of:

```
Optional profile fields:
[ ] Group Contact
[ ] Additional Faculty
```

with different options checked by default for different group types.

The very generic 'Optional profile fields' header would allow us to use this setting for other group-type-specific fields, like 'Course Information'. See #204.

**Comment by boonebgorges** [comment]
An update after a team discussion yesterday. Instead of my suggestion above, we'll implement a single 'Group Contact' feature that will be identical across group types, except that the user-facing strings will be customizable via the Dashboard interface on a per-group-type basis. In the default group types, Courses strings will reference 'Additional Faculty' etc, while it'll remain 'Group Contact' etc for other group types.

**Comment by boonebgorges** [comment]
I've completed a first pass at this. Here's a screenshot of the way the feature currently works, with Clubs as an example:

![Screenshot_2020-05-18_14-05-13](https://user-images.githubusercontent.com/246627/82250174-98c81f80-9910-11ea-8bb8-1944e07658d9.png)

I enabled the feature for all group types. For Portfolios, I left the same string formulation ("Portfolio Contact" etc) as above. For Courses, I went with the following:

![Screenshot_2020-05-18_14-02-10](https://user-images.githubusercontent.com/246627/82250247-b4cbc100-9910-11ea-96b6-dd582ac68961.png)

Note that the term used here - `Faculty` - is then reflected on the profile header:

![Screenshot_2020-05-18_14-06-33](https://user-images.githubusercontent.com/246627/82250286-cad98180-9910-11ea-9961-2400f75da959.png)

This is instead of the currently hardcoded `'Professors'`.

For backward compatibility, I had to change the logic of the 'Contacts' feature slightly. Now it is no longer possible to empty the field and have *no* contacts for the group. If you try to do so, then your account (that is, the account of the person changing the settings) will be the sole Group Contact.

**Comment by bree-z** [comment]
Thanks! This looks good. The only issue is that the text for Projects and Clubs references Portfolios. E.g.:

By default, you are the Project Contact. You may add or remove Project Contacts once your **portfolio** has more members.

Thanks!

**Comment by boonebgorges** [comment]
Whoops, good catch. This should now be fixed.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good for Clubs, but in Project Contact I see:

"By default, you are the Project Contact. You may add or remove Project Contacts once your Portfolio has more members."

**Comment by boonebgorges** [comment]
Thanks and sorry for missing this. It's been fixed.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good.
