### ISSUE TITLE
Fine-grained control for group-site role syncing

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#209]
Currently, CBOX-OL syncs group members to the linked site according to a hardcoded rubric that compares group and site privacy levels and makes assumptions about how they should work together. See https://github.com/cuny-academic-commons/cbox-openlab-core/blob/1c7925d9c8568f8baa518115c30cb08e9ed70073/includes/group-sites.php#L203. 

Since CBOX-OL was forked, the OpenLab has replaced this logic with a group-admin-facing set of toggles. These toggles allow the group admin to configure the site-role mappings for each group-role-type. See http://redmine.citytech.cuny.edu/issues/1392

We should port this feature to CBOX-OL. I don't believe that any Dashboard-level UI will be necessary for this. But we will need to ensure that the default settings are inherited properly, so that no migration routine is required on CBOX upgrade. This should work out of the box https://github.com/livinglab/openlab/blob/be6d985ea6c570a0a9ca9567692103ee495227d8/wp-content/plugins/wds-citytech/includes/group-blogs.php#L921 but needs testing.

**Comment by boonebgorges** [comment]
This is ready to test on openlabdev.commonsinabox.org. In particular, the team may want to review the modifications I made to the wording of the group-admin-facing UI; on the OL, we have some hardcoded references to group types, and I rephrased them to be group-type-agnostic.

**Comment by bree-z** [comment]
Thanks, Boone! The language looks good to me, and functionality also looks good.
