### ISSUE TITLE
Group (course) creation: auto-generated URLs are not prevalidated

### ISSUE THREAD

**Issue by moui72** [cuny-academic-commons/commons-in-a-box#210]
[Testing script (Courses > Line 13)](https://docs.google.com/spreadsheets/d/1KhP4nH2ha1KGmdPRbdhjCTuMXGOEYc3ZlgIqCr-cxe8/edit#gid=157387563) reads, "Users can’t choose a URL that duplicates an existing group’s URL (and it can’t be auto-generated)."

Naming a course identically to another course does autogenerate an illegal URL. It is correctly indicated as unavailable, but the testing script makes it seem like in this situation the generated URL should be pre-validated and generate a legal URL, e.g. should suggested `how-to-eat-mnms-1` instead of `how-to-eat-mnms`***.

*** = invalid, already taken
 
![screenshot-openlabdev commonsinabox org-2018 07 23-15-10-06](https://user-images.githubusercontent.com/3885628/43097660-c38ba3e6-8e8a-11e8-9438-79aa16da3cf6.png)

**Comment by boonebgorges** [comment]
@Mamaduka Could you have a look at this? As I mention above, the suggested URL for groups is generated in the browser on `blur` from the name field. https://github.com/cuny-academic-commons/openlab-theme/blob/7d2e26a2926eb1f1a96e4cfdd1b6df999e8261c7/js/group-url.js#L14 

Running an AJAX request here  before populating the URL field  will be quite slow. But perhaps we can do some combination: build a suggested name in the client as we currently do, *then* fire the request, and if the server tells us there's a conflict, it sends a unique name back to the client and we replace the suggested name with it (perhaps with an updated message explaining what happened).

Of course, we would cancel the swap-out if we detect that the user has begun typing in the URL field. (some sort of `keydown` event)

This isn't a perfect solution. But I'm guessing that in 95% of cases, the originally suggested URL will be unique. In 50% of the remaining cases, users will want to customize the URL anyway. And in many other cases, users will simply tab/click past the field and accept the swapped-out suggestion. It's only likely to be awkward for the small number of users who don't like our swapout.

**Comment by Mamaduka** [comment]
@boonebgorges auto-incremented slug number suffixes can get expensive. This works for files because dir scan is cheaper most of the time.

Maybe we can return `$found` group ID with error and use it as a suffix? This doesn't necessarily mean unique slugs but should work for 99% cases.

What do you think?

**Comment by boonebgorges** [comment]
I'd have to do some testing, but I'm guessing that the expensive part of the check is the round-trip to the server, and the loading of WordPress. The queries that we run after WP is loaded probably don't make a huge difference.

If you're concerned about BP's `groups_get_groups()` (or `BP_Groups_Group::group_exists()`, which I think BP uses internally when assigning slugs) we could have a custom database query that pulls up all slugs match `'{$user_provided_slug}%`. Then we loop through them in PHP and determine the next auto-incremented value. This is a different technique for auto-incrementing than WP uses, which I think is a `do...while` with a separate DB query each time.

**Comment by boonebgorges** [comment]
Is this ready for team testing, @Mamaduka ?

**Comment by Mamaduka** [comment]
Hi @boonebgorges,

Yes, this is ready for the team to test.

**Comment by boonebgorges** [comment]
Thanks!

**Comment by bree-z** [comment]
This looks good, thanks!
