### ISSUE TITLE
Directory filter design mods

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#211]
> "CBOX-OL / OL small adjustments with copy to improve functionality.
> - Two possibilities - (1) change to text and layout/order of filters and search (2) bigger functionality change if we allow, e.g., searching within filter results - have to redo breadcrumbs, if Ajax is involved, also requires changes
> - Small changes can be address now; bigger stuff next year."

@jennaspevack Assigning to you. Please spell out what you have in mind for this round of development.

**Comment by boonebgorges** [comment]
See http://redmine.citytech.cuny.edu/issues/2738 for a spec.

**Comment by bree-z** [comment]
Hi Boone, 

This looks good except for one small difference between CBOX OL and the OpenLab. The name of the group type appears farther over to the left on the OpenLab - it looks like it's centered on CBOX OL(?). This is very small, and fine to address in a future release. If that makes sense, I can open up a separate ticket.

Thanks!

### CBOX OL

<img width="900" alt="Screen Shot 2020-08-10 at 9 34 23 AM" src="https://user-images.githubusercontent.com/7189824/89788582-65e78f00-daed-11ea-9705-6fb99d2a7fa9.png">

#### OpenLab

<img width="898" alt="Screen Shot 2020-08-10 at 9 34 37 AM" src="https://user-images.githubusercontent.com/7189824/89788614-726be780-daed-11ea-95b3-514c632b25ef.png">

I'm not sure how much of a big deal this is

**Comment by boonebgorges** [comment]
Thanks for the screenshot, Bree. I think this was a change from the original design that took place on the OL after I'd originally ported to CBOX. I've made the change.

**Comment by bree-z** [comment]
This looks good, thanks Boone@
