### ISSUE TITLE
"Private Comments" plugin

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#212]
See http://redmine.citytech.cuny.edu/issues/2514#note-20

We want a plugin that allows logged-in users to leave Private comments on a site. 

> - It will show a 'Make my comment private' toggle/checkbox to logged-in users. We can borrow or adapt the markup/UI from WP Grade Comments for this.
> - When the box is checked, the comment will be visible only to the post author/site admin and the commenter.
> - Logged-out users can still leave comments, but they will not have the ability to make them private. See discussion above for why this is not possible.
> - Optionally, there'll be a mechanism for post author/site admin to toggle privacy for a given comment.

This would be useful on CBOX-OL specifically for portfolios, where students might want to allow faculty and other viewers to leave comments, without them being public.

Note that the functionality partly overlaps wp-grade-comments, but the differences are (a) there are no grades here, and (b) the Private toggle here is intended to be available to the end user, not just the "teacher" as in the case of wp-grade-comments.

**Comment by boonebgorges** [comment]
Just flagging that this plugin has been built and is awaiting review by the OpenLab team at http://redmine.citytech.cuny.edu/issues/2514#note-20. Once they've given the OK there, we can work on merging it here. See https://github.com/cuny-academic-commons/commons-in-a-box/pull/205 for how to add a new plugin, though this one would not be Required.

**Comment by Mamaduka** [comment]
OpenLab ticket is now resolved. I'll start working on porting the plugin here next week.

**Comment by Mamaduka** [comment]
Hello, @bree-z

I don't see any related tickets in Redmine. Is this feature ready to be shipped with CBOX-OL?

**Comment by bree-z** [comment]
Hi George, 

Yes, it's ready for CBOX OpenLab. All outstanding issues have been resolved, and it went into last week's OpenLab release. 

Thanks!

**Comment by boonebgorges** [comment]
I've finished cleaning up the plugin and the repo (very little actual work was needed), and have added it to the `openlab` package. It's ready for a look on openlabdev.commonsinabox.org, if you want to do any testing there.

**Comment by bree-z** [comment]
Thanks Boone! This looks good except for one thing:

Private comments and private replies appear in the comments feed on the group home. See, for example: https://openlabdev.commonsinabox.org/groups/cosmo-ortizs-portfolio/

<img width="1321" alt="PrivateCommentsInFeed" src="https://user-images.githubusercontent.com/7189824/127221282-1efbb7b0-5141-42b9-95dd-a43e0d074b20.png">

**Comment by boonebgorges** [comment]
Good catch - this needed a change to the theme, which I've now ported from OpenLab.

**Comment by bree-z** [comment]
This looks good, thanks!
