### ISSUE TITLE
Group search results landing page

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#213]
This is a placeholder to port http://redmine.citytech.cuny.edu/issues/2735 to this package when available.

**Comment by Mamaduka** [comment]
Hi @boonebgorges,

https://github.com/cuny-academic-commons/openlab-theme/commit/5f02fdfbdb99dd9641ac33a8804efc2a9192755f. This change breaks "My {Group Type}" pages.

**Comment by boonebgorges** [comment]
Thanks for the heads up, @Mamaduka ! Should be fixed by https://github.com/cuny-academic-commons/openlab-theme/commit/bbd2099201efc3b731bce00892b8a566196c9f25

**Comment by bree-z** [comment]
This all looks good, thanks!
