### ISSUE TITLE
Promoting another faculty member to admin of a course replaces the faculty listed as professor on profile

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#214]
* I logged in as ‘breefacultyagain’ and joined this course, created by testfaculty: https://openlabdev.commonsinabox.org/groups/spring-please/
* I then logged in as ‘testfaculty’ and promoted ‘breefacultyagain’ to admin
* ‘breefacultyagain’ (display name: Professor Bree) replaced testfaculty as the Professor listed on the profile.

Here’s the Redmine ticket where we fixed this on the OpenLab: http://redmine.citytech.cuny.edu/issues/2019

Not sure to what extent this is related to #207

**Comment by boonebgorges** [comment]
It will likely be fixed as part of #207, but it's good to have it listed separately here. Thanks!

**Comment by bree-z** [comment]
Thanks, Boone! This looks mostly good, except that now what happens is:

- Faculty A joins Faculty B's course
- Faculty B promotes Faculty A to admin
- Faculty A and Faculty B are both listed as professors, even if Faculty B hasn't added Faculty A as another faculty member to be listed on the course. 

I think what should happen (as it works on the OL), is that even if another faculty member is promoted to admin of a course, they're not listed as Faculty unless they're added via Settings > Additional Faculty.

Thanks!

**Comment by boonebgorges** [comment]
Hm, I'm not seeing this in my tests. Users only appear in the "Faculty" line on the course profile if they are explicitly added as Faculty in the group's Settings. Can you share the URL of a group that's demonstrating the problem?

**Comment by bree-z** [comment]
Sure.  I was testing in this course: https://openlabdev.commonsinabox.org/groups/ancient-political-thought/

- breefacultyaugust2020 joined
- testfaculty promoted breefacultyaugust2020 to admin

**Comment by boonebgorges** [comment]
Ah, got it. This line was rendered differently for Courses than for other group types. I've applied the changes so they're consistent across group type.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good on the Course Home, although the second admin's name still appears in the Courses  directory and search results page. See e.g.: https://openlabdev.commonsinabox.org/groups/ancient-political-thought/

Thanks!

<img width="456" alt="AdminName_Directory" src="https://user-images.githubusercontent.com/7189824/89639886-69281400-d87c-11ea-9a98-a40229ed847c.png">

<img width="894" alt="AdminName_Profile" src="https://user-images.githubusercontent.com/7189824/89639901-6f1df500-d87c-11ea-9b56-182bc28e08a3.png">

**Comment by boonebgorges** [comment]
Thanks for the screenshots. This should now be fixed.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good!
