### ISSUE TITLE
Add faculty name to metadata displayed on Course directory page

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#215]
This is a copy of http://redmine.citytech.cuny.edu/issues/2735 for the OpenLab, to add faculty name to the metadata that appears for each course on the course directory page.

**Comment by boonebgorges** [comment]
This was done in 16d65e1bc7ad704c0f40b25aadd843d9395c74a2.

**Comment by bree-z** [comment]
This looks good, thanks!
