### ISSUE TITLE
Ensure missing required plugins prompts a notice to install

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/commons-in-a-box#217]
Currently, required plugins are only installed during initial installation.

If a required plugin is deleted or if a new required plugin is added to a package manifest after initial set up (see #205), a prompt to install will not be shown.

Let's always show a notice if a required plugin is missing.

Todo:
- [x] Add missing required plugins to `wp cbox status`? (See commits 4a89e0b and f3b2c65)

**Comment by r-a-y** [comment]
@boonebgorges - `wp cbox status` and `wp cbox update plugins` are now updated to account for any missing required plugins.

If there are missing required plugins that are either not activated or installed, `wp cbox status` now displays the following:

```
$ wp cbox status
Current CBOX package: OpenLab

Current theme: CBOX OpenLab. No update available.

The following plugins are required and need to be either activated or installed:
+-------------------+---------+-----------------------+
| Plugin            | Version | Action                |
+-------------------+---------+-----------------------+
| CBOX-OpenLab Core | 1.1.2   | Requires activation   |
| OpenLab Portfolio | 1.0.0   | Requires installation |
+-------------------+---------+-----------------------+

Run "wp cbox update plugins" to update the plugins.
```

Running `wp cbox update plugins` in this instance will display the following:

```
$ wp cbox update plugins
Installing missing required plugins:
Downloading installation package from https://github.com/livinglab/openlab-portfolio/archive/1.0.0.zip...
Unpacking the package...
Installing the plugin...
Renamed Github-based project from 'openlab-portfolio-1.0.0' to 'openlab-portfolio'.
Removing the old version of the plugin...
Plugin updated successfully.
Success: Installed 1 of 1 plugins.

Activated missing required plugins: CBOX-OpenLab Core and OpenLab Portfolio.

All other active plugins are already up-to-date.
```

Let me know if you have any feedback on the flow.

**Comment by boonebgorges** [comment]
> Let me know if you have any feedback on the flow.

My feedback is that this is awesome and perfect. 

A quick question: I see that there's support in the CLI tool for Github-based stuff. I assume that there's also support for when the zip file is shipped with the distribution plugin?

**Comment by r-a-y** [comment]
ZIP installations should be fully supported since #179. Just double-checked and that is still the case :)

Going to close this out. Thanks for the sanity check!
