### ISSUE TITLE
This plugin has not been tested with your current version of WordPress

### ISSUE THREAD

**Issue by lordmatt** [cuny-academic-commons/commons-in-a-box#218]
When I view information about CBox I get this notice:

> Warning: this plugin has not been tested with your current version of WordPress.

Is it maybe time to confirm compatibility with the newest version?

**Comment by r-a-y** [comment]
We're shooting for a release sometime later in the month, so we'll bump the required versions then.

Thanks lordmatt!

**Comment by lordmatt** [comment]
Fair enough. That makes sense as a new BuddyPress (6.0.0, I think, is due out soon anyway).

**Comment by boonebgorges** [comment]
Closing this in anticipation of next week's release.
