### ISSUE TITLE
Folders for Files

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#219]
"Files" "folders" - that is, 'group-document-category' terms - are not properly copied during clone.

A pending fix for the OpenLab is at http://redmine.citytech.cuny.edu/issues/2686. It should be ported here once it's confirmed there.

**Comment by boonebgorges** [comment]
Updating this ticket to reflect that we actually don't have folders CBOX-OL  - I forgot that they were added to the OL after the fork. See http://redmine.citytech.cuny.edu/issues/2536

**Comment by boonebgorges** [comment]
I merged this feature and it's ready to test on openlabdev.org.

During the merge, I made some minor changes to the implementation, specifically around the way that the columns on the Files page are built.

Be sure to test:

- Folder creation
- Adding items to existing folders
- Navigating into a folder
- Deleting a folder

**Comment by bree-z** [comment]
Thanks Boone! The folder functionality looks good, but is it possible to make a few UI changes to match the CT OL? If not, I'll put in a ticket for a future release.

<img width="1199" alt="FileLibrary_CBOXOL" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/c0bc3aa5-f108-4b3b-b948-543878b67734">

City Tech OpenLab:

<img width="1240" alt="FileLibrary_OL" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/0348920f-c71c-49fe-84f0-b6f347b24d3f">

**Comment by boonebgorges** [comment]
These changes are ready to test.

**Comment by bree-z** [comment]
The changes all look good, thanks!

And sorry, I lost track of what I was testing. I can delete a folder by removing it from all files, but if I navigate to the folder and click the delete button, I get a popup saying "Are you sure you wish to permanently delete this folder? The files associated with this folder will not be deleted." If I click OK, it's not deleted. 

Testing in this group: https://openlabdev.commonsinabox.org/groups/omnia-peccata-paria-dicitis/documents/ 

Here's a screencast: https://screenpal.com/watch/c0iI0nVgKlu

**Comment by boonebgorges** [comment]
> And sorry, I lost track of what I was testing. I can delete a folder by removing it from all files, but if I navigate to the folder and click the delete button, I get a popup saying "Are you sure you wish to permanently delete this folder? The files associated with this folder will not be deleted." If I click OK, it's not deleted.

This should now be ready to test.

**Comment by bree-z** [comment]
This looks good, thanks!
