### ISSUE TITLE
CLI commands for data migrations

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#235]
Low priority, but it would be nice to have WP-CLI commands for handling data updates. Probably:

`$ wp cbox upgrade list`
`$ wp cbox upgrade run [name]` 

@Mamaduka If it's easy and you've finished the more pressing tasks for the release, feel free to slip this in for 1.2.0.

**Comment by Mamaduka** [comment]
I've only "Shared Cloning" with high priority, hope to finish porting today/Monday. I can continue working on upgrade task after this.

**Comment by boonebgorges** [comment]
Sounds great!

**Comment by boonebgorges** [comment]
Merged in #275.
