### ISSUE TITLE
More descriptive text on upgrades screen

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#236]
Under the progress bar on the upgrade screen, it says `Processed item with ID: 201.`. I think that `201` is just an arbitrary identifier. Maybe we could make this more descriptive, so that admins know what's going on? URLs might be appropriate, since anything we'd be processing in bulk would have a URL (group, site, member). @Mamaduka do you have thoughts about this? Maybe I'm wrong that these are arbitrary - do they need to be numeric/integers?

**Comment by Mamaduka** [comment]
I think it would be better to remove these messages. They change fast and aren't that useful.

A better alternative will be to have a proper logger class, so `Upgrades` can log meaningful messages.

I've used a similar method in "OpenLab Portfolio" [importer](https://github.com/livinglab/openlab-portfolio/blob/master/src/Import/Importer.php) and I can work on this for the next version.

**Comment by boonebgorges** [comment]
Removal sounds fine to me for now, @Mamaduka. Thanks!

**Comment by Mamaduka** [comment]
Updated the code.

**Comment by boonebgorges** [comment]
Thanks, @Mamaduka ! Let's call this good for the current release.
