### ISSUE TITLE
Dynamic group sidebar filter disabling based on group type suggestions

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#238]
See redmine.citytech.cuny.edu/issues/2788#change-19569. The new search interface #213 introduces group type toggles, but not all directory filters apply to all group types. The logic from the OL should be ported here, but there will need to be significant changes - in the form of GroupType 'supports' feature flags, I think - to account for the fact that our group types are dynamic. See especially https://github.com/livinglab/openlab/blob/1.7.x/wp-content/themes/openlab/lib/group-funcs.php#L1918. The corresponding JS is probably modular enough to be moved right over as-is.

**Comment by boonebgorges** [comment]
This is built, but it's not fully testable until badges are fully integrated. On Badges, I'm waiting for the completion of testing on the OpenLab so that I can tag the plugin. See #203.

**Comment by boonebgorges** [comment]
Badges are enabled and the feature is ready to test.

**Comment by bree-z** [comment]
I think we can finally close this. :)
