### ISSUE TITLE
CBOX update admin_notice showing on subsites

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#241]
Our admin_notices box is appearing on subsite Dashboards. Tracked back to `cbox_is_setup()` returning false because `cbox_get_setup_step()` is returning `required-plugins`.

**Comment by r-a-y** [comment]
Good catch, @boonebgorges.

Do we want to run the admin notice code throughout all admin dashboards or only on the root site and network admin area? I'm guessing the latter would be fine, but if we find it beneficial to alert the super admin on all admin dashboards, I'm okay with that as well.

**Comment by boonebgorges** [comment]
> I think limiting to the root blog and network admin area would be okay, but let me know what you think.

I agree that this is the best idea. Probably the easiest for you too :)

**Comment by r-a-y** [comment]
Addressed in 1.2.0. Forgot to close this out!
