### ISSUE TITLE
Site Templates on new installs default to Twenty Sixteen Theme even if Twenty Sixteen is not installed.

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#242]
When installing Commons in the Box OpenLab for the first time on a Wordpress 5.4 website, the 4 templates that are autogenerated default to the twenty sixteen theme.

The twenty sixteen theme was recently removed from Wordpress Core and is no longer automatically installed, so it would be better to update to twenty twenty.

**Comment by boonebgorges** [comment]
Hi @beckej13820 - Thanks for the report, and good catch. I'm going with a somewhat more flexible solution, which is:

1. Define a list of preferred themes for site templates (`twentysixteen` followed by `twentytwenty`)
2. During install, check the list of preferred themes, in order. If one is found, use it. If not, fall back on `WP_DEFAULT_THEME`
3. Run this through a filter `cboxol_site_template_default_theme` for additional customization.

**Comment by boonebgorges** [comment]
Fixed in https://github.com/cuny-academic-commons/cbox-openlab-core/commit/3129a8465b00b609c952f98017b785222c1cc28e.
