### ISSUE TITLE
When viewing another user's profile, the active link for course, projects, etc. is not highlighted 

### ISSUE THREAD

**Issue by arto-a** [cuny-academic-commons/commons-in-a-box#247]
For example, when visiting the following URL:  https://openlabdev.commonsinabox.org/members/testfaculty/groups/?group_type=project

notice how "Project' is not highlighted on the right-hand Nav (see attached screenshot).

<img width="1276" alt="Screen Shot 2020-08-04 at 11 01 40 PM" src="https://user-images.githubusercontent.com/68743478/89339289-e4ff4200-d66b-11ea-96c9-724c923b784a.png">

Thanks!

**Comment by boonebgorges** [comment]
This was caused by a typo when rebuilding these menus during this dev cycle. It should now be fixed.

**Comment by arto-a** [comment]
This is fixed. Thanks.
