### ISSUE TITLE
Creating a new even in Calendar: Text entered in Event Description is invisible

### ISSUE THREAD

**Issue by arto-a** [cuny-academic-commons/commons-in-a-box#248]
The text entered in the Event Description seems to be in white font, entered on a white background. The entered text becomes visible when highlighted. See attached screenshot:
<img width="1249" alt="Screen Shot 2020-08-05 at 7 58 11 PM" src="https://user-images.githubusercontent.com/68743478/89444249-6b289080-d71f-11ea-8cf5-06d47be39805.png">

**Comment by boonebgorges** [comment]
This was being triggered by a fatal error due to a typo in a function name. This has been fixed and I believe the styling is working correctly now.

**Comment by arto-a** [comment]
Fixed!
