### ISSUE TITLE
 Adjust badge checkboxes on group directory filters

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#249]
Hi Boone, 

There are some badge checkboxes that appear on group directory filters that don't apply to a particular group type.  E.g. On the Clubs directory, the following badges appear:

- Cool Group
- Extra Super Special Course
- Writing Intensive
- Capstone
- Model Course
- Student Government Association

However, only these apply to clubs:

- Cool Group
- Student Government Association

In case it's helpful, here's the OpenLab ticket for this: http://redmine.citytech.cuny.edu/issues/2787 

Thanks!

**Comment by boonebgorges** [comment]
Thanks for the report. This had to be ported from OpenLab. Now ready to test.

**Comment by bree-z** [comment]
This looks good, thanks!
