### ISSUE TITLE
Shrink size of badges on Group Home pages

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#250]
Hi Boone, 

Compared with the OpenLab, I think the badges on a Group's Home are a little too large:

### CBOX OpenLab:

<img width="897" alt="BadgesCBOXOL" src="https://user-images.githubusercontent.com/7189824/89451123-b34cb080-d729-11ea-8c88-207949eb4adc.png">

### OpenLab:

<img width="898" alt="BadgesOL" src="https://user-images.githubusercontent.com/7189824/89451155-be9fdc00-d729-11ea-8065-0412a22d32b5.png">

Here's the OpenLab ticket: http://redmine.citytech.cuny.edu/issues/2789

It looks like @jennaspevack 's other adjustments are all here, but I'm adding her in case she wants to take a look.

Thanks!

**Comment by boonebgorges** [comment]
Thanks - I'd missed this when backporting changes from the OpenLab. Now ready to test.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good.
