### ISSUE TITLE
testfaculty user's portfolio links are incorrect

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#251]
Hi Boone, 

The same issue with a deleted user portfolio as reported in http://redmine.citytech.cuny.edu/issues/2809 happened for the testfaculty user's Portfolio on openlabdev.commonsinabox.org

On testfaculty Profile, the link for the portfolio site is: https://openlabdev.commonsinabox.org/members/testfaculty/ and the link to the Portfolio Home is: https://openlabdev.commonsinabox.org/groups/

Not sure if this is another fluke, but it happened after going to Portfolio Home > Settings >Delete.  I couldn't reproduce with another user. 

Thanks!

**Comment by boonebgorges** [comment]
Similar issue here: the `portfolio_group_id` usermeta was set for the user as `198`, but the group with the ID `198` had been deleted. This probably only happens in cases where the database is continually reset and user accounts regenerated. We do have logic in CBOX-OL that ensures that `portfolio_group_id` is deleted on group deletion in general; see https://github.com/cuny-academic-commons/cbox-openlab-core/blob/0e1097237cb6b9d2dbca3c989a232cb9de839410/includes/portfolios.php#L555.

If you manage to reproduce the issue in a reliable way in the regular course of events, please open a ticket describing the steps.

**Comment by bree-z** [comment]
I haven't been able to reproduce this issue.
