### ISSUE TITLE
My Profile > Create a [group] link does not appear when user hasn't already joined a [group]

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#252]
Hi Boone, 

I believe this is the same bug as reported in http://redmine.citytech.cuny.edu/issues/2816

- I created a new user, [alicegreen](https://openlabdev.commonsinabox.org/members/alicegreen/). This user was not yet a member of any group.
- I went to My Profile > My Clubs. 
- The main content area was blank, and I didn't see the link to create a new club. 
- I did see the create club link in the Clubs directory. 

Thanks!

<img width="1204" alt="Screen Shot 2020-08-06 at 7 30 29 AM" src="https://user-images.githubusercontent.com/7189824/89527569-8646df00-d7b7-11ea-8f2e-3aa8a6a089a8.png">

**Comment by boonebgorges** [comment]
Not exactly the same issue, but closely related, so thanks for the pointer - you saved me some digging. This should now be fixed.

**Comment by bree-z** [comment]
This looks good, thanks!
