### ISSUE TITLE
Group avatar not populated during clone

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#253]
Sorry, I thought this already had a ticket!  There are a few issues with step 1 of cloning:

1. The group avatar is not copied from the source to the clone
2. On the OpenLab, term is not pre-populated. On CBOX-OL it is prepopulated, but it's populated with the upcoming semester, which is also the case with creating a new course. I don't remember this feature, but if it's intended to populate with the upcoming semester, that's fine! But if the upcoming semester is a fluke, then we should just leave the 'Term' field empty.

Source: https://openlabdev.commonsinabox.org/groups/ancient-political-thought/
Clone: https://openlabdev.commonsinabox.org/groups/ancient-political-thought-clone/

Thanks!

![CloningAvatar](https://user-images.githubusercontent.com/7189824/89559663-fbc8a480-d7e3-11ea-827a-bf5ea763789b.png)

**Comment by bree-z** [comment]
Sorry, one more thing:

Categories are also not being cloned: 

Source: https://openlabdev.commonsinabox.org/groups/faculty-cats-at-rest/ 
Clone: https://openlabdev.commonsinabox.org/groups/faculty-cats-at-rest-clone/ 

Thanks!

**Comment by boonebgorges** [comment]
Renaming this ticket to refer only to the group avatar issue.

I'm not sure whether this was ever a feature on CBOX-OL. I'll try to trace it on the OpenLab.

**Comment by boonebgorges** [comment]
Avatar upload on the OpenLab is its own step, while here we do avatar input on the first step of group creation. So the systems are totally separate as far as avatars are concerned.

It's probably possible to make this work, but it's non-trivial, and wasn't part of the scope for 1.2.0. I'll leave the ticket open in this milestone and have a look at it if there's time before release.

**Comment by bree-z** [comment]
Hi Boone, 

I know this is on hold, but just wanted to add a note to keep this one on hold. We're actually reevaluating whether it makes more sense to not clone avatars as part of the cloning process.

Thanks!

**Comment by boonebgorges** [comment]
Sounds good, thanks!

**Comment by boonebgorges** [comment]
For reference, an older ticket from the openlab-theme repo: https://github.com/cuny-academic-commons/openlab-theme/issues/160
