### ISSUE TITLE
Categories not being cloned

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#255]
From #253:

> Categories are also not being cloned:
> 
> Source: https://openlabdev.commonsinabox.org/groups/faculty-cats-at-rest/
> Clone: https://openlabdev.commonsinabox.org/groups/faculty-cats-at-rest-clone/

@bree-z Can you please be precise about what's happening? I assume you mean that the Category checkboxes are not pre-checked, based on the clone source, during group creation?

**Comment by bree-z** [comment]
Sorry Boone! Yes, I mean that the Category checkboxes are not pre-checked, based on the clone source, during group creation.  

But, I might have given you the wrong examples -- I don't see categories on the source example above. In the example below, the source group has the following categories: Academic, Community, Faculty, Staff, Student. During the cloning process, these category checkboxes were not pre-checked. I didn't check them during the cloning process, and the clone  group had no categories associated with it. 

Source: https://openlabdev.commonsinabox.org/groups/prehistoric-club/
Clone: https://openlabdev.commonsinabox.org/groups/prof-teslas-clone-of-math-club-2/

**Comment by boonebgorges** [comment]
Got it. It looks like this was never implemented, probably because previously, only Courses could be cloned, and Courses don't have categories on the default configuration. I've put it in place and it's ready to test.

**Comment by bree-z** [comment]
Thanks, Boone. This looks good!
