### ISSUE TITLE
Cloning step 2: site privacy settings don't properly reflect privacy setting of source

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#257]
In step 2 of the cloning process, the radio button under 'Associated Site Privacy Settings' does not properly reflect the privacy setting of the source group. 

Once I finish cloning I see that the setting of the source group was saved properly: the setting of the clone reflects the setting of the source.  

This happens with courses via regular or shared cloning. It only happens with projects and clubs via shared cloning. Regular cloning is correct. 

I think this is the same as reported in: http://redmine.citytech.cuny.edu/issues/2818

Thanks!

**Comment by boonebgorges** [comment]
Yes, it's the same issue, though unfortunately the fix is a bit more complex :-/ Ready to test.

**Comment by bree-z** [comment]
Thanks, Boone! 

The site privacy settings during the cloning process now properly reflect the site privacy settings of the source. And the setting is saved properly on the cloned site.

However, if I try to change the settings during the change process, I'm able to choose different settings but those are *not* saved properly. The settings on the clone are the same as the source. 

Source: https://openlabdev.commonsinabox.org/groups/intro-to-political-philosophy/
Clone: https://openlabdev.commonsinabox.org/groups/intro-to-political-philosophy-clone-2/

Thanks!

![ChangeSiteSettings](https://user-images.githubusercontent.com/7189824/89643228-5402b380-d883-11ea-8c48-cb977a53d684.gif)

**Comment by boonebgorges** [comment]
Thanks for the details. This problem is due to some load-order issues in the interaction between the saving of site settings and the way that the site-clone process works. I've made some adjustments and it's ready to test.

**Comment by bree-z** [comment]
This looks good, thanks Boone!
