### ISSUE TITLE
Clone link for projects and clubs doesn't appear

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#258]
The clone link for projects and clubs doesn't appear where it does for courses when an admin is trying to clone their own group.  

As with courses, it should appear:

1. In My Profile > My [Groups] the link should say "Create / Clone" rather than "Create New".

2. In Group Settings there should be a Clone link.

The group directories do have the correct Create / Clone link.

Thanks!

### My Profile > My Projects

<img width="693" alt="Screen Shot 2020-08-06 at 2 46 25 PM" src="https://user-images.githubusercontent.com/7189824/89570741-9af59800-d7f4-11ea-8acc-8a6dcb027c2c.png">

### My Profile > My Courses 

<img width="668" alt="Screen Shot 2020-08-06 at 2 46 18 PM" src="https://user-images.githubusercontent.com/7189824/89570727-9630e400-d7f4-11ea-8712-8e1ae1aa452b.png">

### Project Settings

<img width="942" alt="Screen Shot 2020-08-06 at 2 47 21 PM" src="https://user-images.githubusercontent.com/7189824/89570771-a648c380-d7f4-11ea-93e4-fbcc3f4e0570.png">

### Course Settings

<img width="894" alt="Screen Shot 2020-08-06 at 2 47 10 PM" src="https://user-images.githubusercontent.com/7189824/89570801-b1035880-d7f4-11ea-99e6-a2ceac6782c1.png">

**Comment by boonebgorges** [comment]
I've made the changes so that these links correctly reflect the cloneable status of the group type.

**Comment by bree-z** [comment]
This looks good, thanks!
