### ISSUE TITLE
'Clone' badge doesn't appear on groups with shared cloning enabled

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#259]
The 'Clone' badge isn't appearing on any groups with shared cloning enabled -- in group directories, search results, or on group profiles.

<img width="1201" alt="Screen Shot 2020-08-06 at 3 24 55 PM" src="https://user-images.githubusercontent.com/7189824/89574444-245b9900-d7fa-11ea-91a1-dacb25584bd1.png">

See, for example:

https://openlabdev.commonsinabox.org/groups/prehistoric-club/
https://openlabdev.commonsinabox.org/groups/ancient-political-thought/
https://openlabdev.commonsinabox.org/groups/mt-everest/

When I check the box for 'Cloneable' in group directories, it does return groups with shared cloning enabled.

<img width="1187" alt="Screen Shot 2020-08-06 at 3 30 25 PM" src="https://user-images.githubusercontent.com/7189824/89574502-3fc6a400-d7fa-11ea-915c-d375eedcfd9a.png">

Thanks!

**Comment by boonebgorges** [comment]
Thanks for the detailed report. I'd previously disabled the badge because the 'cloneable' tool wasn't fully finished, and forgot to turn it back on. Now ready to test.

**Comment by bree-z** [comment]
This looks good, thanks!
