### ISSUE TITLE
Credits appear on profile of groups cloned via regular (not shared) cloning

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#260]
Hi Boone, 

I'm not sure if this is new or we just missed it earlier, but when I clone a group as the group admin--not through shared cloning--the credits still appear on the profile of the cloned group. Shared cloning was not enabled on the source groups.

Source: https://openlabdev.commonsinabox.org/groups/intro-to-political-philosophy/
Clone: https://openlabdev.commonsinabox.org/groups/intro-to-political-philosophy-clone/

Source: https://openlabdev.commonsinabox.org/groups/the-lorax-fan-club/
Clone: https://openlabdev.commonsinabox.org/groups/lorax-fan-club-clone/

Thanks!

**Comment by boonebgorges** [comment]
This should now be fixed.

**Comment by bree-z** [comment]
Yes, this looks good, thanks!
