### ISSUE TITLE
Steps 2 and 3 of Project, Club and Portfolio creation/cloning: Heading is for Course creation

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#262]
Hi Boone, 

The headings and instructions in Steps 2 and 3 of Project, Club and Portfolio creation/cloning reference Course creation:

Create/Clone Course
Step Two: Associated Site Creation
Each course can also have an optional associated site. This is a WordPress site that all members of your course can access and contribute to.

Create/Clone Course
Step Three: Invite Members to Course

Step 1 is correct, and all other text in steps 2 and 3 is correct. 

Thanks!

**Comment by boonebgorges** [comment]
Group type was being improperly detected. I've made a change to address this.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
