### ISSUE TITLE
Group categories not checked in Settings

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#264]
Hi Boone, 

When a group has categories, they appear on the Group Home page, but the checkboxes are not checked in the Group Settings > Group Details. If I change something else on that same settings page (like group description) and then save, the categories are removed from the Group Home. 

Here's the group from the screenshots below: https://openlabdev.commonsinabox.org/groups/club-without-a-site/ 

I'm pretty sure this is a new bug. 

Thanks!

<img width="885" alt="Categories_Home" src="https://user-images.githubusercontent.com/7189824/89730804-25661380-da10-11ea-8393-e4ab02f1ef46.png">

![Categories_Settings](https://user-images.githubusercontent.com/7189824/89730807-28610400-da10-11ea-874b-eaea8d7cae79.png)

**Comment by boonebgorges** [comment]
Yes, this was being caused by some recent changes to the way the Group Categories tool works. It should now be fixed.

**Comment by bree-z** [comment]
Fixed, thanks!
