### ISSUE TITLE
Search Results: Can only view first page of results

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#266]
Hi Boone, 

When I do a search that results in more pages than one, when I click on another page number at the bottom, the first page just reloads. After that, nothing happens when I click on any of the subsequent pages: 

![SearchPages](https://user-images.githubusercontent.com/7189824/89739620-30409880-da50-11ea-9dbb-4f4db6dab9f9.gif)

**Comment by boonebgorges** [comment]
This was being caused by the double-encoding of certain URL formats. I've rearranged the logic.

**Comment by bree-z** [comment]
Also failed to close this out yesterday, but it's now fixed, thanks!
