### ISSUE TITLE
Group directories: After a search the active page is not highlighted in nav

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#267]
Hi Boone, 

I think this is a pre-existing issue (I see it on BMCC OL), but just wanted to flag it before I forget.

When I search for something in a group directory, the active page is not highlighted in the main nav:
 
<img width="1212" alt="SearchNoActiveHighlight" src="https://user-images.githubusercontent.com/7189824/89739898-7696f700-da52-11ea-8583-5b8c23734bfc.png">

Thanks!

**Comment by boonebgorges** [comment]
There's no surefire way to detect this across all installation types, but I've put in an attempt that should generally work. If we find there are still problems, they'll have to wait for a future release.

**Comment by bree-z** [comment]
Tested this yesterday but failed to close! This looks good on openlabdev.commonsinabox.org. Thanks!
