### ISSUE TITLE
Search and Directory Pages: Mobile display issues

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#268]
Hi Boone, 

There are a few mobile display issues that we fixed on the OpenLab in http://redmine.citytech.cuny.edu/issues/2794 that I see on openlabdev.commonsinabox.org:

1. In some instances, the badges overlap with the description. 
2. I'm not sure this fits into this release, but: on all Directory and Search Pages on mobile can we shift the "1 to X (of xx)" down?

<img width="436" alt="SearchResults_Mobile" src="https://user-images.githubusercontent.com/7189824/89929574-5f354680-dbd7-11ea-9a12-4770cfbf92c7.png">

There's also an issue with the top search button breaking onto a separate line. And, the search field extends past the end of the screen on the right side. 

Compare CBOX-OL and the OL:

### CBOX-OL

![CBOXOL_TopSearch](https://user-images.githubusercontent.com/7189824/89937139-aecd3f80-dbe2-11ea-97d8-c839a1f0cf9b.png)

### OL

![OpenLabTopSearch](https://user-images.githubusercontent.com/7189824/89937196-c278a600-dbe2-11ea-94eb-147a842fce1c.png)

Thanks!

**Comment by boonebgorges** [comment]
Thanks for the detailed report. I think I've addressed all these issues.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
