### ISSUE TITLE
Mobile > Group Home: Extra '+' icon in top nav

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#269]
Hi Boone, 

On mobile, there's an extra '+' icon appearing in the top nav (grey toolbar) when viewing the Group Home as an admin. Pressing it doesn't do anything.

I think this is new, since it doesn't appear on the BMCC OpenLab. e.g.:

### CBOX OL dev site:

![Extra+Icon](https://user-images.githubusercontent.com/7189824/89937976-ceb13300-dbe3-11ea-90b0-2482d86d7466.png)

### BMCC OL

<img width="407" alt="BMCC_NoPlus" src="https://user-images.githubusercontent.com/7189824/89938030-e38dc680-dbe3-11ea-878d-7c87dd6edc62.png">

Thanks!

**Comment by boonebgorges** [comment]
The + sign is meant for authoring bbPress content. I'm not sure why clicking it does nothing in your case. But I agree that it shouldn't appear, so I've hidden it.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good.
