### ISSUE TITLE
Docs: In groups with no existing Docs 'create one' link renders as HTML

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#270]
Sorry, this never got a ticket. :-/

In a group that does not yet have any docs, the 'Create one' link appears as: 

"Why not <a href="create">create one</a>?

<img width="1201" alt="DocsLink" src="https://user-images.githubusercontent.com/7189824/89992601-7d408c80-dc53-11ea-8043-597552e2f927.png">

**Comment by boonebgorges** [comment]
Oops, sorry about that. I've fixed it, and slightly changed the scope of the anchor tag so as to make internationalization easier.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good.
