### ISSUE TITLE
Docs: 'Read' tab missing grey background

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#272]
Hi Boone, 

When viewing a doc, the 'Read' tab is missing the grey tab background, and the text is not bold. It's also not a link when I'm in 'Edit' or viewing the history, so I can't get back to 'Read' by clicking the tab.

<img width="903" alt="DocsReadTab" src="https://user-images.githubusercontent.com/7189824/90144920-68e0ba80-dd4d-11ea-8067-163aa1c359d0.png">
 
Compare with:

<img width="895" alt="Screen Shot 2020-08-12 at 1 55 26 PM" src="https://user-images.githubusercontent.com/7189824/90144963-772ed680-dd4d-11ea-8cbb-b2067685b613.png">

Thanks!

**Comment by boonebgorges** [comment]
Whoops. Typo was causing malformed markup. Fixed now.

**Comment by bree-z** [comment]
Thank, Boone! Looks good.
