### ISSUE TITLE
new release testing - CBOX Classic

### ISSUE THREAD

**Issue by vothsco** [cuny-academic-commons/commons-in-a-box#276]
When I installed the plugin everything worked fine except for the theme. When I clicked install I got this message: "The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature".

I also tried to install the theme from the zip folder, but that theme has zero bytes.

![cbox theme issue](https://user-images.githubusercontent.com/630806/90421047-ceeb7b80-e086-11ea-90bb-4fb4d4c43c01.png)

**Comment by boonebgorges** [comment]
Dangit. There was a typo in the theme URL. I've fixed it and packaged 1.2.0-beta2. Here's the new zip: https://github.com/cuny-academic-commons/commons-in-a-box/archive/1.2.0-beta2.zip
