### ISSUE TITLE
Not able to make changes to community-wide footer content

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#281]
Hi Boone, 

I was able to reproduce the [issue reported](https://commonsinabox.org/groups/openlab-help-support/forum/topic/open-lab-theme-cant-edit-site-wide-footer/) in the CBOX OpenLab forum.

I can make changes to the heading, but once I try to change anything in the content area, the Publish button is greyed out and I can't save any changes, and they don't appear on the front end in the preview window.

I see the same thing as he showed in his video, which is here: https://www.youtube.com/watch?v=HSzeh11Jb0I 

Also, after I replied to his forum post, I got the following error: Error establishing a database connection. The site still appears to be down.

Thanks!

**Comment by boonebgorges** [comment]
> I can make changes to the heading, but once I try to change anything in the content area, the Publish button is greyed out and I can't save any changes, and they don't appear on the front end in the preview window.

I guess there was a change to the WP Customizer or something that broke this. I rewrote it so that it's working now. You may test this on openlabdev.commonsinabox.org if you'd like.

> Also, after I replied to his forum post, I got the following error: Error establishing a database connection. The site still appears to be down.

The GC had some issues this morning. If you're still having problems, let me know in a separate thread.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good. I'm able to change the left and middle headings and content areas of the footer.

And the cbox.org site is back up, thanks!

**Comment by bree-z** [comment]
Hi Boone, 

We're wondering if it's possible for this change to go in now, given that users are getting ready for the semester to begin? 

Thanks!

**Comment by boonebgorges** [comment]
"Go in" where? It's already merged.

**Comment by boonebgorges** [comment]
Maybe you mean you'd like another release? It takes several hours for me to push out a wordpress.org plugin release, so I'd strongly prefer to wait until we have enough changes to warrant the effort. Affected users may, in the meantime, manually patch their installations: https://github.com/cuny-academic-commons/openlab-theme/commit/05a57d24d0352db2c2937b14b80ca467534f9412

**Comment by bree-z** [comment]
Sorry, it's getting late here! 

I'll pass along the patch info, thanks!
