### ISSUE TITLE
Group types sometimes not appearing in Group Types UI

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#283]
See https://commonsinabox.org/groups/openlab-help-support/forum/topic/openlab-1-2-1-group-type-pages-no-longer-filter#post-8508 and follow-up. The 'Portfolios' type is appearing as expected in the JSON return value, but not in the UI.

**Comment by beckej13820** [comment]
[Javascript Errors.docx](https://github.com/cuny-academic-commons/commons-in-a-box/files/5157744/Javascript.Errors.docx)

Here is a Word Document with the javascript errors cut and paste.

**Comment by boonebgorges** [comment]
Extremely helpful, thanks. I'll review.

**Comment by boonebgorges** [comment]
Thanks for your patience as I tracked down the issue.

There are two overlapping problems here. One is that there's a small number of strings, related to the new Clone widgets in 1.2.0, that were not properly added to the 1.2.0 upgrade routine. As such, they weren't properly filled in for the default group types.

This, in turn, was triggering an obscure bug: When a group type loads its saved labels from the database, if there are certain labels that are registered globally to group types, but are *not* relevant for a given group type, the label type would be erroneously added to the API endpoint's definition of the group type, and these erroneously added label types would have corrupt data (instead of correct data or an empty string). This, in turn, caused failures in the dashboard app that caused the entire group type not to render properly. In the case of 1.2.0, the missing strings described in the previous paragraph triggered this bug for the Portfolio group type, where the Clone widget strings are not defined.

I'll push up fixes for both issues.

**Comment by boonebgorges** [comment]
https://github.com/cuny-academic-commons/cbox-openlab-core/commit/c78b958f7e3b5f4380a4c17a32f77f24f4580ac7 should fix the label type bug described in my long paragraph above.

**Comment by boonebgorges** [comment]
https://github.com/cuny-academic-commons/cbox-openlab-core/commit/4e9aa00777d327e0a95c813c6c650a45a3509e0d introduces the necessary upgrader to fill in the missing strings on the 1.2.3 upgrade.

**Comment by boonebgorges** [comment]
@beckej13820 You or anyone else experiencing the problem of the missing 'Portfolios' on the Group Settings panel by manually applying https://github.com/cuny-academic-commons/cbox-openlab-core/commit/c78b958f7e3b5f4380a4c17a32f77f24f4580ac7 to your installation. You can then manually add/modify the last three strings under the non-Portfolios group types (beginning with 'Clone Credits Widget Description') if you'd like.
