### ISSUE TITLE
OpenLab — membership request success notification glitch

### ISSUE THREAD

**Issue by ajeannette** [cuny-academic-commons/commons-in-a-box#285]
I have been loving my overall experience with OpenLab, but just wanted to bring up a little issue I've noticed:

## Specs

I’m running CBOX OpenLab 1.2.2 on Wordpress 5.5

## Description

When requesting membership to private groups, I noticed that the text goes outside of the success box.

Here's a screenshot of this from my site, geneseo.sunycreate.cloud:

![geneseoissue](https://user-images.githubusercontent.com/36711174/93932372-12707f80-fcee-11ea-8870-3e77d6556e87.jpg)

I'm suspicious that this might be a theme issue, because it can be replicated on another site, oneonta.sunycreate.cloud:

<img width="1298" alt="oneontaissue" src="https://user-images.githubusercontent.com/36711174/93932342-084e8100-fcee-11ea-9f3d-2116b07f6c50.png">

Please let me know if you need any more information from my end. Thank you! 

~Amanda

**Comment by boonebgorges** [comment]
Good catch! Thanks for the thorough report and the screenshots.

**Comment by boonebgorges** [comment]
We'll look at a fix for 1.3.0, but once something has been committed to the repo here on GitHub, you should be able to add the CSS manually to your own installation if you need the problem fixed before the 1.3.0 release.

**Comment by ajeannette** [comment]
This is so great, thank you! :clap:

**Comment by bree-z** [comment]
This looks good, thanks!
