### ISSUE TITLE
Help pages- Title overlaps with print page button and sidebar is displayed below page content

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#287]
OpenLab Theme Version 1.2.2
Wordpress 5.5.1

OpenLab Help Pages has text that overlap. The page Title and the "Print this page" button are overlapping. (see screenshot)
![Screen Shot 2020-10-01 at 1 06 53 PM](https://user-images.githubusercontent.com/29982981/94841479-16845780-03e8-11eb-9d91-0d423423800f.png)

Also, the sidebar for the help pages always appears below the page text instead of to the right. This appears to be a bug and not by design, because this is still true on large devices (tested up to 4K width).
![Screen Shot 2020-10-01 at 1 16 46 PM](https://user-images.githubusercontent.com/29982981/94841666-5ea37a00-03e8-11eb-945b-d0173f9253c1.png)

Both issues can be seen at: https://oneonta.sunycreate.cloud/blog/help/how-to-clone-a-site/
and is the same on all help pages such as: https://oneonta.sunycreate.cloud/blog/help/creating-a-course-faculty-only/

**Comment by Mamaduka** [comment]
@boonebgorges this should be fixed now.

**Comment by boonebgorges** [comment]
Thanks! Deployed for testing.

**Comment by bree-z** [comment]
Hi @boonebgorges - I'm not sure how to test this, since the 'Print this Page' link and help sidebar are customizations that don't appear on https://openlabdev.commonsinabox.org.

Thanks!

**Comment by boonebgorges** [comment]
@bree-z I just imported a bunch of OL help content. Can you have a look? https://openlabdev.commonsinabox.org/blog/help/what-is-openlab/

**Comment by bree-z** [comment]
Thanks Boone! This looks good. There's no overlap, and the sidebar appears in the correct location.
