### ISSUE TITLE
'Faculty' field missing on older courses

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#288]
Hi Boone, 

I was able to reproduce [this user-reported bug](https://commonsinabox.org/groups/openlab-help-support/forum/topic/openlab-1-2-2-course-contact-not-showing-in-courses) on openlabdev.commonsinabox.org. 

See, for example: https://openlabdev.commonsinabox.org/groups/new-course5/ 

This is only an issue for courses created prior to the 1.2.0 updates, where settings weren't updated. The field reappears if I go to Course Home > Settings, and click Save Changes. It's also not an issue for new courses.

Thanks!

**Comment by boonebgorges** [comment]
I've put a fix in place that uses the group creator ID + additional_faculty as fallbacks if the new group_contact is not present. See #214, #207.

**Comment by bree-z** [comment]
Thanks, Boone. This addressed the issue on the course home, but I don't see the faculty name appearing on the directory page for older courses, e.g.: 

course directory: https://openlabdev.commonsinabox.org/groups/type/course/?grpage=4&num=12 
course home: https://openlabdev.commonsinabox.org/groups/political-writing/

Thanks!

**Comment by bree-z** [comment]
Meant to add screenshots:

<img width="1191" alt="FacultyName_Directory" src="https://user-images.githubusercontent.com/7189824/95325291-fa146f00-086e-11eb-81ec-d7e19b1bfb4c.png">


<img width="1197" alt="FacultyName_Home" src="https://user-images.githubusercontent.com/7189824/95325267-f1bc3400-086e-11eb-8fb9-373ad804de47.png">

**Comment by boonebgorges** [comment]
Thanks, Bree. I've made some changes that should address this.

**Comment by bree-z** [comment]
This looks good, thanks!
