### ISSUE TITLE
Changing group type name doesn't change top-level nav item

### ISSUE THREAD

**Issue by agmckinney** [cuny-academic-commons/commons-in-a-box#290]
When attempting to change a group type name, it takes on the back end (Portfolio to ePortfolio in this case: 
![screen shot 2018-07-27 at 10 56 18 am](https://user-images.githubusercontent.com/11300891/43328346-b929b420-918b-11e8-9e01-aca8e1b1f52a.png)

But does not take on the front end in either the top level menu or in the front page directories
![screen shot 2018-07-27 at 10 57 41 am](https://user-images.githubusercontent.com/11300891/43328402-e61d3254-918b-11e8-8b94-104f78c657d3.png)

**Comment by boonebgorges** [comment]
This is now implemented. Note that it only looks at the items in the 'Main Menu' that is automatically created by CBOX-OL at the time of installation. I'm not touching other nav menu items that users may have created manually.

**Comment by bree-z** [comment]
Thanks Boone! The group type name change looks good, however when I made this change, the order of the menu was changed. 

Original menu order:

<img width="984" alt="MenuOrderPrevious" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/336373ab-c784-4251-a1db-b314ec04995a">


Then, I changed Courses > Seminars, Clubs > Communities, Projects > Things.

After saving, the menu had changed to the following:

<img width="1038" alt="MenuOrderChanged" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/115dddf8-6b5e-4c87-928e-7cf38f40e1ce">

**Comment by boonebgorges** [comment]
WP is extremely annoying here, in that you apparently have to pass every property of a nav item when updating that nav item, otherwise the unmentioned properties will be zeroed out. This includes 'position'. I've made the necessary change and it appears that the position overwriting is no longer happening.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
