### ISSUE TITLE
Admin-editable academic terms

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#297]
From @charliemedwards 

> Is it possible to do reverse chronological sort for terms?? 

See cuny-academic-commons/openlab-theme#40. It is not possible to do this, given the fact that Term is a freeform text field.

**Comment by boonebgorges** [comment]
I've begun work on this. 

As part of the work, it seemed clear to me that this feature in particular would be extremely hard to use without easy sorting. So I added a layer of drag-and-drop sorting. Currently I've enabled it only for Academic Terms, but I could turn it on for all other similar interfaces (thereby dropping the Order field) if people like it.

I've still got more work to do to connect all the pieces, but I wanted to share this gif so that people can get a sense of the admin interface, and make suggestions:

![Peek 2022-05-05 17-45](https://user-images.githubusercontent.com/246627/167037944-6ddd7027-8681-496f-b5be-93d6de9dadd1.gif)

**Comment by boonebgorges** [comment]
Adding @bree-z and @jennaspevack to see the comment above.

**Comment by bree-z** [comment]
Thanks Boone! This looks good. I can add, edit, delete, and re-order terms, and those changes appear in the course directory filter dropdown, and can be applied to new and existing courses.

I think it makes sense to keep this as a top-level section in the Dashboard, since courses are the only group type it applies to, and it's more visible this way. 

The only issue I saw is that if I reordered the terms first and then deleted one, the reordering was lost (see below).

Thanks!

![ReorderLost](https://user-images.githubusercontent.com/7189824/180861982-ad05445d-233f-4ad8-ae11-58903eb30050.gif)

**Comment by boonebgorges** [comment]
Thanks, @bree-z !

I couldn't reproduce the issue described above, though I did find an issue that is perhaps related, where the order/names of terms could be somewhat jumbled if you add a bunch of them at once and don't refresh the page. I've just put a fix into place so that the page refreshes every time you add a new term, which should fix this specific problem. Could you give another test to see whether it fixes yours? If not, can you please give precise steps to reproduce?

**Comment by bree-z** [comment]
Thanks Boone!

That fixed the issue. I did notice one more issue though:

When I edit the name of a term (e.g. Winter 2021 > Winter 2021 Session), it is changed in the directory filter dropdown and on the Course Home, but it isn't changed in the directory metadata. 

<img width="1276" alt="Screen Shot 2022-07-26 at 1 27 44 PM" src="https://user-images.githubusercontent.com/7189824/181072964-188de623-1436-4588-97bd-18a97a49bda8.png">

<img width="912" alt="Screen Shot 2022-07-26 at 1 28 03 PM" src="https://user-images.githubusercontent.com/7189824/181072969-0f49db50-7ddb-499a-8c8b-2602c71cd208.png">

**Comment by boonebgorges** [comment]
Thanks, Bree. This last issue should now be fixed.
