### ISSUE TITLE
Issues with member directory filters 

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#309]
Hi Boone, 

BMCC has reported that since they did updates recently, they can no longer sort members by newest, alphabetical, or last active. I can reproduce this on openlabdev.comonsinabox.org.  

Also, when testing this I noticed that the ‘Category’ dropdown, which should only be applicable to groups, is appearing on the members directory page (on both BMCC and openlabdev.comonsinabox.org).

<img width="1191" alt="MemberDirectory" src="https://user-images.githubusercontent.com/7189824/97422336-0b87ee80-18e4-11eb-9919-daab7a5947e9.png">

Thanks!

**Comment by boonebgorges** [comment]
I've pushed up fixes for these issues.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good. I no longer see the category filter, and all other filters are working properly.
