### ISSUE TITLE
Icon missing on 'Clone this [Group]' button

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#310]
Hi Boone, 

The icon that appears on the button for shared cloning of a group is missing on CBOX-OL. See screenshots below from CBOX-OL and the City Tech OpenLab.

Thanks!

<img width="330" alt="CloneIcon_CBOX-OL" src="https://user-images.githubusercontent.com/7189824/97423072-155e2180-18e5-11eb-891e-231a94aa6421.png">

<img width="544" alt="CloneIcon_OL" src="https://user-images.githubusercontent.com/7189824/97423079-18591200-18e5-11eb-8869-1f8e2f3b30b7.png">

**Comment by boonebgorges** [comment]
openlab-theme was using version 4.3.0 of font-awesome, which doesn't have fa-clone. The OpenLab updated to 4.7.0 in order to have this icon. See http://redmine.citytech.cuny.edu/issues/2313#note-7, http://redmine.citytech.cuny.edu/issues/2378. I've made the corresponding update in openlab-theme.

**Comment by bree-z** [comment]
This looks good, thanks!
