### ISSUE TITLE
CBOX-OL Dashboard section: Welcome page display issues in Firefox

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#316]
Hi Boone, 

The welcome/main page in the CBOX-OL Dashboard section (https://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox) has a lot of extra white space in Firefox. It looks like the li height is 357px, vs. in Chrome where it looks fine the height is 132 px. 

**Firefox:**

![CBOX-OLDashboardFirefox](https://user-images.githubusercontent.com/7189824/99371813-65e5f080-288d-11eb-9077-dad7146d3d9b.png)

**Chrome:**

![CBOX-OLDashboardChrome](https://user-images.githubusercontent.com/7189824/99371838-6c746800-288d-11eb-97cf-e8d85b594493.png)

Thanks!

**Comment by boonebgorges** [comment]
@r-a-y I think you built this. Maybe you could have a look in the upcoming weeks. Thank you!

**Comment by r-a-y** [comment]
I rewrote the "Getting Started" section to use a CSS table display instead of trying to set the height of each list item with jQuery (dunno why I chose that solution previously!).

This should fix the problem with Firefox. Squeezed this in for 1.2.3 :)

**Comment by bree-z** [comment]
Thanks so much, @r-a-y !

Is this something I can test on openlabdev.commonsinabox.org? I don't see the changes there.

Thanks!

**Comment by boonebgorges** [comment]
Changes are deployed to openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
