### ISSUE TITLE
Members directory: Move User Type dropdown to the top 

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#317]
Hi Boone, 

Could we move the User Type dropdown to the top of the list on the Members directory? We're thinking this makes more sense to be first when searching for members.

Thanks!

<img width="1209" alt="MoveUserTypeDropdown" src="https://user-images.githubusercontent.com/7189824/99375435-bbbc9780-2891-11eb-817a-616e7a312459.png">

**Comment by boonebgorges** [comment]
Yes, this should not be a problem.

The Portfolios directory also has a User Type dropdown, in the same position as the Members directory. Should it be moved too?

**Comment by bree-z** [comment]
Thanks for catching that, @boonebgorges ! Yes, we'd like to move it in the Portfolios directory too.

**Comment by boonebgorges** [comment]
Excellent, thanks.

**Comment by bree-z** [comment]
This looks good, thanks!
