### ISSUE TITLE
Course Term field can't be saved without a value

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#319]
Hi Boone, 

I was able to reproduce this issue reported in the [forum](https://commonsinabox.org/groups/openlab-help-support/forum/topic/can-course-profiles-have-their-term-field-stay-empty/) on openlabdev.commonsinabox.org. 

* In Course Home > Settings,  I erase the 'Term' field, leaving it blank. 
* After saving it is re-populated with 'Spring 2021.'
* However, nothing appears on the Course Home. 
* If I go back into settings and save again without deleting 'Spring 2021' from the Term field, 'Spring 2021' appears on the Course Home.

Here's a link to the screencast posted in the forum:

https://bmcc-cuny.zoom.us/rec/play/K35PZwYoDmVqhPuYcsMN6Kh04bx74iEZ2hk_SX4yuqbSc5xPiem_IbeXNHwld3OXFdLYxG9TO7dfEIv7.2Fh6CTM_anGm4Cy-?startTime=1607369342000&_x_zm_rtaid=4I6RqtBATxS5IYTGISq1_g.1607431412848.f34bc91e054196748d87ace2459aa155&_x_zm_rhtaid=954 

It reminded me of issue #264 , so just adding here in case it's useful.

Thanks!

**Comment by boonebgorges** [comment]
This feature is meant to provide a sensible default value for the Academic Term field during group creation, but it was mistakenly applied to group editing. I've made a change so that the suggestion should only be filled when creating a group, not editing.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good.
