### ISSUE TITLE
Can't delete messages in My Profile > My Messages

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#320]
Hi Boone, 

The links to delete individual messages don't appear in the UI on CBOX-OL in two places:

1. In My Profile > My Messages > Inbox 
2. in the individual message

Also, there's some text missing in the individual message (although it appears incorrect in a different way on the OpenLab - I'll put in a Redmine ticket for that).  Below the message title, it should say, "Sent between you and [Display name]."

See CBOX-OL compared with the City Tech OpenLab:

**City Tech OpenLab**

<img width="1201" alt="MessagesInbox_OL" src="https://user-images.githubusercontent.com/7189824/101490293-22cce980-3930-11eb-9523-48db876f62e9.png">

<img width="1213" alt="MessageIndividual_OL" src="https://user-images.githubusercontent.com/7189824/101490404-4abc4d00-3930-11eb-8f0a-322e7891d5c6.png">

**CBOX-OL**

<img width="1204" alt="MessagesInbox_CBOXOL" src="https://user-images.githubusercontent.com/7189824/101490258-19dc1800-3930-11eb-99e4-3d5863d39dca.png">

<img width="1215" alt="MessageIndividual_CBOXOL" src="https://user-images.githubusercontent.com/7189824/101490421-51e35b00-3930-11eb-9898-72bf6caf297a.png">

**Comment by boonebgorges** [comment]
The incorrect string "Sent between %s" was the result of an incorrect escaping function. This has been fixed.

Message delete buttons were added to the OpenLab in http://redmine.citytech.cuny.edu/issues/2080 and never ported to openlab-theme. Our team will have to slot this into a release based on available resources.

**Comment by bree-z** [comment]
Thanks, Boone. The incorrect string is fixed. Should I open up another ticket for the message deletion buttons?

**Comment by boonebgorges** [comment]
Yes, let's open a separate ticket for the deletion buttons. This is a non-trivial task and we'll need to slot it alongside other features.

**Comment by bree-z** [comment]
Thanks Boone! I added #328 so will close this one out.
