### ISSUE TITLE
WP 5.6 update breaks front page

### ISSUE THREAD

**Issue by patriclougheed** [cuny-academic-commons/commons-in-a-box#326]
Only error I can find:

vendor.js:1097 Uncaught TypeError: Cannot set property 'touchstart' of undefined
    at String.<anonymous> (vendor.js:1097)
    at Function.each (jquery.min.js:2)
    at vendor.js:1097
    at vendor.js:1097
    at window.define (vendor.js:1097)
    at vendor.js:1097
(anonymous) @ vendor.js:1097
each @ jquery.min.js:2
(anonymous) @ vendor.js:1097
(anonymous) @ vendor.js:1097
window.define @ vendor.js:1097
(anonymous) @ vendor.js:1097

utility.js:45 Uncaught ReferenceError: detectZoom is not defined
    at Object.detectZoom (utility.js:45)
    at utility.js:782
    at dispatch (jquery.min.js:2)
    at v.handle (jquery.min.js:2)
detectZoom @ utility.js:45
(anonymous) @ utility.js:782
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
load (async)
add @ jquery.min.js:2
s.event.add @ jquery-migrate.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
ke @ jquery.min.js:2
on @ jquery.min.js:2
(anonymous) @ vendor.js:6
(anonymous) @ vendor.js:6

**Comment by patriclougheed** [comment]
That works, thanks. Reported issues:

2020-12-15 13:16:30 | jQuery.attrFn is deprecated | Theme: OpenLab | wp-content/themes/openlab-theme/js/dist/vendor.js 

2020-12-15 13:16:30 | jQuery.fn.load() is deprecated | Theme: OpenLab |wp-content/themes/openlab-theme/js/utility.js

**Comment by boonebgorges** [comment]
Thanks for confirming. We'll work on jQuery compatibility in upcoming releases.

**Comment by boonebgorges** [comment]
I've done a review of jQuery functionality through openlab-theme and cbox-openlab-core.

The main fix - what was causing the cascade of failures on the home page - is to remove the jquery-mobile library. This library is incompatible with jQuery v3.x. It's not clear to me what role it played in openlab-theme at all - I don't see any references to the selectors used by jquery-mobile. In my tests, there are no changes in behavior with the removal.

There were a number of other places throughout the packages where it was necessary to swap out deprecated method calls.

Looking around openlabdev.commonsinabox.org and my own installations, I don't see any broken functionality.

**Comment by bree-z** [comment]
Hi @boonebgorges , 

Do you have some suggestions for how we should test this?

Thanks!

**Comment by boonebgorges** [comment]
First, make sure that the front page loads :-D

Beyond that, it's just a question of looking for other jQuery-related breakage through the rest of the site. I've already done an audit of the handful of interfaces that came to mind (directory filters; academic unit selectors; etc) and didn't identify any problems. But if anything suspect comes up during your regular testing, it's worth keeping this ticket in mind, as there may be a connection.

**Comment by patriclougheed** [comment]
Just applied fix with no errors and front page now loads.

**Comment by bree-z** [comment]
Hi Boone, 

We didn't find anything strange in our testing, so I think we're OK to close this.
