### ISSUE TITLE
Add message delete buttons to openlab-theme

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#328]
From #320 :

Message delete buttons were added to the OpenLab in http://redmine.citytech.cuny.edu/issues/2080 and never ported to openlab-theme. Our team will have to slot this into a release based on available resources.

The links to delete individual messages don't appear in the UI on CBOX-OL in two places:

1. In My Profile > My Messages > Inbox 
2. in the individual message

See CBOX-OL compared with the City Tech OpenLab:

**City Tech OpenLab**

<img width="1201" alt="MessagesInbox_OL" src="https://user-images.githubusercontent.com/7189824/101490293-22cce980-3930-11eb-9523-48db876f62e9.png">

<img width="1213" alt="MessageIndividual_OL" src="https://user-images.githubusercontent.com/7189824/101490404-4abc4d00-3930-11eb-8f0a-322e7891d5c6.png">

**CBOX-OL**

<img width="1204" alt="MessagesInbox_CBOXOL" src="https://user-images.githubusercontent.com/7189824/101490258-19dc1800-3930-11eb-99e4-3d5863d39dca.png">

<img width="1215" alt="MessageIndividual_CBOXOL" src="https://user-images.githubusercontent.com/7189824/101490421-51e35b00-3930-11eb-9898-72bf6caf297a.png">

**Comment by boonebgorges** [comment]
Ported and ready to test. Note that this port also includes the 'Unread' text when looking at the Inbox or Sent screen.

**Comment by bree-z** [comment]
This looks good, thanks! 

The 'Unread' text generates a WAVE error. I added a new ticket for that: https://github.com/cuny-academic-commons/commons-in-a-box/issues/360
