### ISSUE TITLE
Calendar "Week" view does not display event

### ISSUE THREAD

**Issue by arto-a** [cuny-academic-commons/commons-in-a-box#329]
I created a recurring event that repeats every week, for a period of four weeks.  The events appear on the "Month" view, but not on the "Week" view. 

URL:  https://openlabdev.commonsinabox.org/groups/studying-american-social-patterns/events/

<img width="894" alt="Screen Shot 2021-01-17 at 8 00 51 PM" src="https://user-images.githubusercontent.com/68743478/104861767-25433b80-58ff-11eb-8371-b3c334300093.png">

<img width="872" alt="Screen Shot 2021-01-17 at 8 01 13 PM" src="https://user-images.githubusercontent.com/68743478/104861777-2c6a4980-58ff-11eb-9d23-e4c94172dcae.png">

**Comment by boonebgorges** [comment]
Thanks for the detailed report. This is an upstream issue. https://github.com/stephenharris/Event-Organiser/issues/499 That ticket says it's fixed in 3.10.3, but that comment is incorrect, as you see in the follow-ups. We'll have to wait for the fix there.

**Comment by boonebgorges** [comment]
Looks like this has been merged in event-organiser. I've pinned version 3.10.5 and it's ready to test on openlabdev.commonsinabox.org.

**Comment by arto-a** [comment]
Thanks, Boone, this issue is fixed.

**Comment by boonebgorges** [comment]
Thanks!
