### ISSUE TITLE
"Open" and "Cloneable" badges need to be modifiable by admin

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#334]
"Open" and "Cloneable" aren't badges in the sense that they can be awarded to groups, but they do look like badges on the front end, which means that they have a label like "Clone" and they have an associated link. Currently, these names and links are hardcoded: https://github.com/cuny-academic-commons/openlab-theme/blob/da7a8119ab4e031850456cc2d2782814a615a8d0/lib/group-funcs.php#L3065 (They are hardcoded on the OpenLab as well.)

A few problems here:
1. The 'someotherlink' and 'somelink' links obviously are placeholder content, and will never result in a correct link. This is the most serious issue.
2. The labels are not translatable.

An admin interface for editing the fields would make it easy to fix these issues. The 'link' field would be empty by default, while the 'name' fields would be prefilled with translatable values. The admin could then modify as they see fit.

It's somewhat confusing no matter where we put it, but I guess it makes the most sense to throw these on the same panel as the Badges. Maybe a separate section near the bottom 'Special Badges' with some helper text explaining that they cannot be deleted and cannot be explicitly awarded? @bree-z

**Comment by boonebgorges** [comment]
In the short term, anyone wanting to make changes to these badges can use the following as a template:

https://gist.github.com/boonebgorges/95d1ec1c291e7c63cdeb0391780b6d51

The first block changes the 'Open' link to '#', which effectively makes it a non-link. (Actually removing the anchor tag will cause problems for the tooltip and for styling.) You can change it to some other URL if you'd like. The second block changes the 'Clone' link to read 'Cloneable'. You can mix and match as you see fit.

**Comment by profstein** [comment]
I agree that it makes sense to put this in the Badges panel. Perhaps "Automatic Badges" is a name for them? 

On a related note, there are some visual changes to the badges that were suggested by the BMCC team. In general, I think that most of these are probably better (or more easily) addressed through the theme but they could potentially be other additions to the Badges admin:

- Color: ability to change the text and background color of the badges
- location: ability to change the location of the badges. For example, right now they start in the top left. There could be options for the admin to pick which of the four corners they started in.

**Other potential Badge Admin mods**
- Should there be an option to show badges somewhere other than on top of the group avatar? 
- Option to not show one or more of the automatic badges

**Comment by profstein** [comment]
I forgot to mention, thanks for the short term way of modifying the badges. I will consult with the other team members and we may implement this.

**Comment by boonebgorges** [comment]
I've had a first go at fixing this.

I decided to integrate into the Badge system more deeply, so that we could inherit the existing tools for editing badge labels, links, etc. This required an Updater that added the new Open and Cloneable badges. On the openlab-badges end, I added a `can_be_deleted` flag, and then ensured that the new Open and Cloneable badges have the flag set.

I did *not* fully integrate into the "award" system. Obviously, it should not be possible to manually grant the Cloneable and Open badges - they are determined automatically. So I was faced with the option of either (a) trying to set the taxonomy relationships that tie groups to badges every time a group's Open or  Cloneable status changes, or (b) bypassing the term-relationship system for Open and Cloneable and tricking openlab-badges into thinking that the group objects were associated with the `openlab_badge` terms. Because of the potential syncing problems introduced by (a), I opted for (b).

Here's a screenshot of the new badges on the admin panel. Note that there's no 'delete badge' link:

![Screenshot_2021-04-20_16-46-12](https://user-images.githubusercontent.com/246627/115434719-89c0b000-a1f8-11eb-9139-485a49b22629.png)

We may decide that these auto-generated badges should have some helper text in place of the 'Delete' link, to explain where they came from and why they cannot be deleted. I'll defer to @bree-z on this point. See also https://openlabdev.commonsinabox.org/wp-admin/network/admin.php?page=openlab-badges

**Comment by bree-z** [comment]
Thanks, Boone! Just a few things:

1. Can we make Open and Cloneable the top two badges by default, rather than the last two?  And are users supposed to be able to change the order? Currently, if I move Open and Cloneable to the first and second places, they remain last in the list of badges on a group avatar or in the group directories. See, for example: https://openlabdev.commonsinabox.org/groups/language-culture-and-society/

2. I do think that some helper text would be useful. Could we add the following text at the top, beneath the ‘Badges’ heading, and above ‘Mange existing badges’? 

Custom badges can be created and modified below, and assigned to individual groups by network administrators. These badges are displayed in group directories and on group home pages, and can be used to find and filter groups in the directories. ‘Open’ and ‘Cloneable’ badges, which can be edited below, cannot be deleted or manually added to groups. They are automatically applied to groups with open privacy settings and/or groups with shared cloning enabled. 

3. Can we eliminate the Portfolios checkbox from beneath the ‘Cloneable’ badge since portfolios can’t be cloned?

4. There are now extra ‘Open’ and ‘Cloneable' checkboxes added to directory pages. Can we keep the two that were always there, and remove the extras added to the list with the other badges? (See screenshot)

Thanks!

<img width="478" alt="OpenCloneableExtraCheckboxes" src="https://user-images.githubusercontent.com/7189824/126047913-2923a2d2-1f2e-4375-aefb-5feccf5d183a.png">

**Comment by boonebgorges** [comment]
> Can we make Open and Cloneable the top two badges by default, rather than the last two?

I have made this change, both on installation and on upgrade. In the case of upgrade, it means bumping the admin-defined position of all existing badges by 2 in order to allow for Open and Cloneable to appear in the first two positions. As a rule I don't like to mess with admin-provided values, but it was necessary in this case.

>  And are users supposed to be able to change the order? 

Yes, I just hadn't made the change apply to the way that the badges are shown in some interfaces. This should now be fixed.

> Could we add the following text at the top, beneath the ‘Badges’ heading, and above ‘Mange existing badges’?

I've made this change. Because openlab-badges is ostensibly supposed to be usable outside of CBOX-OL, there are technical limitations that forced me to break the language into two separate paragraphs.

> Can we eliminate the Portfolios checkbox from beneath the ‘Cloneable’ badge since portfolios can’t be cloned?

A large amount of futzing around is required to do this, so I'd rather not. More broadly, in the case of 'Open' and 'Cloneable', the checkboxes on the Network Admin panel do nothing, since the badges cannot be manually granted. My recommendation is to leave it as-is, since only super admins will ever see this interface, and they'll be able to discern the 'automatic' nature of these badges. But if you fear confusion, I'd suggest greying these checkboxes out (or removing them) in the case of the automatic badges, perhaps along with some helper text explaining why the Group Types option is inoperable for these badges.

**Comment by boonebgorges** [comment]
A brief follow-up that I did not make any changes to the order of Open and Cloneable badges on the openlabdev.commonsinabox.org testing site. The position changes do take effect on upgrade or on installation.

**Comment by boonebgorges** [comment]
Sorry about that - I forgot that the openlab-badges repo needed to be deployed differently to openlabdev.commonsinabox.org. Please have another look now.

**Comment by bree-z** [comment]
Great, thanks Boone! This looks good.
