### ISSUE TITLE
Dynamic 'disabled' fields broken on jQuery 3

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#335]
Our technique `removeProp( 'disabled' )` no longer works in jQuery 3. See https://stackoverflow.com/questions/6169826/propchecked-false-or-removeattrchecked#6170016

This breaks certain interfaces, most importantly the interface where you select site type during group creation.

**Comment by boonebgorges** [comment]
Confirmed working on openlabdev.commonsinabox.org.

**Comment by profstein** [comment]
confirmed working on openlab.bmcc.cuny.edu

**Comment by boonebgorges** [comment]
Thanks for confirming!
