### ISSUE TITLE
Portfolio metadata can be corrupted when edited by non-owner group admins

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#336]
If user A has a Portfolio group+site, and promotes user B to be an admin of that group, then any changes that B applies to the group's Site settings will incorrectly be applied to B's user settings, rather than A's. We assume that the user changing Portfolio settings is always the Portfolio owner.

**Comment by boonebgorges** [comment]
This should now be fixed. If we want to test it, here's the setup:

1. As user A, create a portfolio group+site PA
2. As user B, create a portfolio group+site PB
3. As user B, join PA
4. As user A, promote B to admin of PA
5. As user B, go to PA's settings and change the title or other settings, then save
6. Visit the profile of A and B and ensure that the Portfolio links point to the correct place

**Comment by bree-z** [comment]
Thanks Boone!

I followed the steps above with this portfolio: https://openlabdev.commonsinabox.org/groups/marva-chavez-as-portfolio/ (User A: studenttest, User B: theodoreloughlin)

All portfolio links on both users' profiles and both Portfolio Homes are correct.
