### ISSUE TITLE
Better control over toolbar display on subsites

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#337]
The OpenLab toolbar can cause issues with various themes. See #324. In the absence of a broader rewrite, we might consider allowing admins some control over how and when the toolbar is shown (instead of forcing it on everywhere, as we do now).

**Comment by bree-z** [comment]
Thanks Boone. @charliemedwards and I discussed and think this is a good solution for now. I'll also put in a placeholder ticket for a broader rewrite, which we might want to consider in the future.

One question: Is it possible to apply this to the footer as well? While usually not as problematic as the toolbar, it can have minor issues in some themes, and we've also had a few users on the OpenLab requesting a way to remove it from group sites.

Thanks!

**Comment by boonebgorges** [comment]
Thanks for chiming in, @bree-z. Can you clarify what you mean by "this", when you say "this is a good solution for now"? Do we want to simply hide the toolbar for non-logged-in users across subsites? This is easy. Or do we want to introduce a UI that allows individual site admins control over whether logged-out users see the toolbar? If so, where will this setting live, and what will it look like (a simple checkmark toggle, or something more complex)?

**Comment by bree-z** [comment]
Sorry to be vague. We don't want to hide the toolbar across sub-sites, but would like to introduce a UI that allows individual site admins control over whether logged-out users see the toolbar. 

We were thinking this would just be an on/off toggle -- a checkmark would work, with a default setting of checked = toolbar is visible; uncheck to hide.  And that this could perhaps appear in Group Home > Settings > Site?

However, that said, we're going to discuss some more in our meeting on Thursday. We're wondering whether it's worth considering prioritizing a broader rewrite, if we can shuffle around some of the other things on our list. 

Thanks!

cc: @charliemedwards

**Comment by boonebgorges** [comment]
Thanks for the clarification. For context, a small UI toggle like this could be fitted into the existing scope for the 1.3.0 release. A broader rewrite of how the toolbar works is a much larger task, which would almost certainly displace some of the items that we've already committed to for 1.3.0. In addition, that kind of rewrite would require considerable design thought and conversation, which is tricky with Jenna on sabbatical.

**Comment by bree-z** [comment]
Thanks, Boone. We'll wait on the broader rewrite, but go ahead with the UI toggle for 1.3.0.

**Comment by boonebgorges** [comment]
I've built a first version of this. It's hard to come up with a setting that is clear enough. Here's my attempt:

![Screenshot_2021-03-22_16-33-54](https://user-images.githubusercontent.com/246627/112024805-76a0be80-8b2c-11eb-9f84-a8fbfe414050.png)

**Comment by bree-z** [comment]
Thanks, Boone! I think this is the best place for the setting. Perhaps we could make it a little more clear by changing the instructional text that appears below the checkbox, as follows:

The admin bar appears at the top of your site. Logged-in visitors will always see it but you can hide it for site visitors who are not logged in.

Could we also change the color to #757575? The current color is not accessible.

Thanks!

Thanks!

**Comment by boonebgorges** [comment]
I've made these changes. Note that the contrast change affects all similar elements (italic text below input labels) throughout the group admin UI.

**Comment by bree-z** [comment]
Thanks Boone! I didn't see this change after clearing my cache.

**Comment by boonebgorges** [comment]
Looking OK to me - maybe it hadn't been deployed properly when you tested? See screenshot

![Screenshot_2021-07-22_11-25-41](https://user-images.githubusercontent.com/246627/126674310-935b3b7e-4a94-44f6-9965-0df32fec714a.png)

**Comment by bree-z** [comment]
Whoops, sorry about that Boone! For some reason I was looking for non-italicized text. 

Your change looks good, thanks!
