### ISSUE TITLE
Port fix for "banned" display in group list

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#338]
Currently, there’s nowhere in the interface to "unban" a member who has been banned. On the City Tech OpenLab we fixed this to allow group admins to "unban" members: 

http://redmine.citytech.cuny.edu/issues/2438

**Comment by boonebgorges** [comment]
Looks like this fix was already ported: https://github.com/cuny-academic-commons/openlab-theme/commit/ca6b107dc258525d7d7c2091afa442a77617bc54

**Comment by bree-z** [comment]
This looks good, thanks!
