### ISSUE TITLE
Port mute/silent options for content types

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#340]
On the City Tech OpenLab we added mute/silent checkboxes for discussion forums, docs, files, or calendar, allowing users to choose whether or not to generate email notifications for specific actions:

http://redmine.citytech.cuny.edu/issues/2448
http://redmine.citytech.cuny.edu/issues/2523

**Comment by boonebgorges** [comment]
These toggles have been ported and are ready to test when we get to that point.

**Comment by bree-z** [comment]
Thanks Boone, this looks good!
