### ISSUE TITLE
Prepare Creative Commons plugin for release and include in CBOX OpenLab

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#342]
Here are the relevant tickets from the City Tech OpenLab:

Original ticket for creating the plugin: http://redmine.citytech.cuny.edu/issues/2440
Ticket for addition of 'Site Author' field: http://redmine.citytech.cuny.edu/issues/2642

**Comment by boonebgorges** [comment]
I was just looking through the milestone and I realized we have an existing ticket for this task: #229. Let's move discussion there.
