### ISSUE TITLE
Port changes to feature toggles behavior on clone

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#345]
In http://redmine.citytech.cuny.edu/issues/2865 we changed the behavior of feature toggles (Discussion, Docs, etc) in cloning so that settings for the cloned group would match the source group.

**Comment by boonebgorges** [comment]
The way this is implemented is based on the changes introduced in http://redmine.citytech.cuny.edu/issues/2745 - namely, that the default toggle states depend on whether the new group has a site. Do we want to port these changes to CBOX-OL as well? @bree-z

**Comment by bree-z** [comment]
Sorry, @boonebgorges, to miss this question!

I don't think we want to port the changes introduced in http://redmine.citytech.cuny.edu/issues/2745 to CBOX-OL since they might not apply to usage at other institutions, but I should  double check with Charlie in our meeting on Monday. 

Or, if it's too late for this port, let me know.

Thanks!

**Comment by boonebgorges** [comment]
Thanks for the clarification. I've made a change so that, after a clone, the source group's feature toggle settings are copied over to the new group.

**Comment by bree-z** [comment]
Thanks, Boone! 

I also confirmed with Charlie that we don't want want to port the changes introduced in http://redmine.citytech.cuny.edu/issues/2745 - just copy the feature toggle settings to the new group after cloning.

**Comment by bree-z** [comment]
This looks good, thanks!
