### ISSUE TITLE
Remove extra 'Individual Group Email Settings'

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#348]
This was reported in the CBOX-OL user forum, and I have confirmed on openlabdev.commonsinabox.org:

* I navigate to My Profile > My Settings > Email Notifications 
* In the very bottom section, Individual Group Email Settings, there is the following text: "To change the email notification settings for your groups, go to My Groups and click "Change" for each group."
* When I click the link for My Groups, I end up here: https://openlabdev.commonsinabox.org/members/testfaculty/groups/ 

Since we don't have a "My Groups" page, I believe we replaced that text with our own (here, I think? http://redmine.citytech.cuny.edu/issues/902). However, there are now two sections called "Individual Group Email Settings". Can we remove the bottom one?

<img width="1017" alt="IndividualGroupEmailSettings" src="https://user-images.githubusercontent.com/7189824/114270306-a0d1f780-99d9-11eb-8632-8ac923d0693f.png">

Thanks!

**Comment by boonebgorges** [comment]
The fix is now ready to test.

**Comment by bree-z** [comment]
Thanks Boone! This looks good!
