### ISSUE TITLE
Email settings are not consistent across all views

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#349]
I was just creating a help page on email settings in OpenLab, and I noticed that there are 5 email settings that users can select, but on the group notifications page, there are only 4 possibilities shown to the admin. 

Just wanted to open a ticket to show there was a discrepancy:

<img width="284" alt="Screen Shot 2021-05-24 at 5 22 23 PM" src="https://user-images.githubusercontent.com/29982981/119409366-35a46200-bcb5-11eb-90b6-505aaf218a3c.png">
In the screenshot above, an Admin can see email settings, but is only shown 4 of the possible 5 email settings. 

In the email subscription options there are 5 possibilities:
<img width="849" alt="Screen Shot 2021-05-24 at 5 28 00 PM" src="https://user-images.githubusercontent.com/29982981/119409541-713f2c00-bcb5-11eb-848f-06c3a5778908.png">

**Comment by r-a-y** [comment]
Hi @beckej13820 - I can confirm the discrepency. I've added a PR to the `openlab-theme` repo, but until then you can temporarily fix things with this commit - https://github.com/cuny-academic-commons/openlab-theme/commit/1591ac61cbe2d9c013ea6e36b3347f48b98c1a38.

**Comment by r-a-y** [comment]
Fix has been merged. I'll leave this open until the next version of CBOX is released.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
