### ISSUE TITLE
Group cloning > Source group settings should not be pre-filled: Port from OpenLab

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#357]
OpenLab ticket is here: http://redmine.citytech.cuny.edu/issues/2862

This is to port changes we made for all types of cloning, where privacy and member role settings from the source group are not pre-filled when creating the cloned group. Instead, the usual group creation defaults are suggested instead.

**Comment by bree-z** [comment]
This looks good, thanks!

**Comment by bree-z** [comment]
Sorry, Boone. I shouldn't have closed this.

Both sets of privacy settings are reset correctly, but Member Role settings are not. 

See, for example:

Source: https://openlabdev.commonsinabox.org/groups/summer-2021-course/
Clone: https://openlabdev.commonsinabox.org/groups/test-faculty-clone2-of-summer-2021-course/

Thanks!

**Comment by boonebgorges** [comment]
I've made a change such that the default Member Role settings during group creation are always Contributor/Author/Administrator, regardless of the clone source's settings.

**Comment by bree-z** [comment]
Thanks, Boone! This is fixed.
