### ISSUE TITLE
New BuddyPress 8.0 features

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/commons-in-a-box#359]
Our last pinned version for BuddyPress is v6.4.0.

Since then, ~two~ three main features have been added to BP v8.0.0 that affect CBOX:
* Native site invite capability - https://bpdevel.wordpress.com/2021/05/26/bp-8-0-introduces-site-membership-invitations/. Built-in feature is lacking compared to the Invite Anyone plugin, which we use in CBOX. The good thing is the feature is disabled by default. @boonebgorges - Do we want to hide the admin option to turn this on to avoid confusion with Invite Anyone or maybe do nothing here?
* Selectable signup fields on registration page in BP 8.0 - https://bpdevel.wordpress.com/2021/05/06/selectable-xprofile-sign-up-fields-in-8-0-0/. This requires a change to our custom registration templates for both Classic and OpenLab themes. I've done this for Classic here: https://github.com/cuny-academic-commons/cbox-theme/commit/d87757c22a49273120a464a9b7c29f61b5411b36.
* Welcome email is sent to a newly-activated user - https://buddypress.trac.wordpress.org/ticket/8428

**Comment by boonebgorges** [comment]
Thanks, @r-a-y !

In ac77af8 I've implemented the selectable signup fields for openlab-theme.

Regarding the Invitations, I think we should do nothing. If an admin turns it on, it's likely to interfere with IA, and in the case of openlab-theme, it may not fully appear anyway. Either way, the admin is likely to realize the incompatibility and disable themselves, and if they decide they want to forge forward with it, that seems fine too.

**Comment by r-a-y** [comment]
> Either way, the admin is likely to realize the incompatibility and disable themselves, and if they decide they want to forge forward with it, that seems fine too.

I'm okay with this.

----

I just discovered another new feature in BP 8.0.0. A welcome email is sent to newly-activated user accounts. See https://buddypress.trac.wordpress.org/ticket/8428.

The default email content is as follows:

> Welcome to {{site.name}}!
> 
> Visit your profile, where you can tell us more about yourself, change your preferences, or make new connections, to get started: {{{profile.url}}}
> 
> Forgot your password? Don't worry, you can reset it with your email address from this page of our site: {{{lostpassword.url}}}

Does the copy need to be modified to suit CBOX better?

**Comment by boonebgorges** [comment]
> Does the copy need to be modified to suit CBOX better?

Thanks for pointing this out. The copy seems OK to me, but let's see if anyone else chimes in.
