### ISSUE TITLE
Group template issues

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#362]
Hi Boone, 

I've been able to reproduce two group template site issues reported in the [forum](https://commonsinabox.org/groups/openlab-help-support/forum/topic/bugs-in-template/):

1. If I change the tagline in the course template site, new courses created after the change still have the old tagline.

Course template site: https://openlabdev.commonsinabox.org/site-template-course-1596809801/
New course: https://openlabdev.commonsinabox.org/more-course-template-testing/

2. The template site contains posts in the following categories: 
https://openlabdev.commonsinabox.org/site-template-course-1596809801/category/announcements/
https://openlabdev.commonsinabox.org/site-template-course-1596809801/category/assignments/

But on new course sites, those category archives give me a 404 error:
https://openlabdev.commonsinabox.org/more-course-template-testing/category/announcements/
https://openlabdev.commonsinabox.org/more-course-template-testing/category/assignments/

If I switch the theme, as I did here, I no longer get the 404: https://openlabdev.commonsinabox.org/course-template-test-3/

Thanks!

**Comment by boonebgorges** [comment]
Neither of these are new bugs, and let's be cautious about what we shove into the milestone at this late date. But I have made changes that should fix both.

**Comment by bree-z** [comment]
Thanks Boone! Both issues are fixed.
