### ISSUE TITLE
Group home page feeds: No space between post excerpt and 'See More' link

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#365]
Hi Boone, 

I think this is an old bug because I see it on the BMCC OpenLab as well. 

On group home page feeds, there's no space between the post, comment, discussion, and doc excerpt and the 'See more' link. 

<img width="900" alt="NoSpaceBeforeSeeMore" src="https://user-images.githubusercontent.com/7189824/126691557-6f8d5d63-7e69-4358-85e4-c98af7a669b1.png"> 

Thanks!

**Comment by boonebgorges** [comment]
I've added a space.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
