### ISSUE TITLE
Dashboard link missing on Portfolio Home

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#367]
When a user is viewing their Portfolio Home page (e.g. https://openlabdev.commonsinabox.org/groups/professor-teslas-portfolio/), there's a link to the Portfolio Site, but there should also be a link to the Portfolio Dashboard. 

The Dashboard link does appear when logged in with a superadmin account (https://openlabdev.commonsinabox.org/groups/tegan-adrianis-portfolio/). 

**Non-admin view:**

<img width="1229" alt="PortfolioDashboardLinkMissing" src="https://user-images.githubusercontent.com/7189824/133749121-012bfac7-f48d-448c-bbce-7ed7ba9f420a.png">

**Super admin view:**

<img width="1310" alt="PortfolioDashboardLinkSuperAdmin" src="https://user-images.githubusercontent.com/7189824/133749163-428d9add-45de-4abf-b004-4644ddf955f9.png">

Thanks!

**Comment by boonebgorges** [comment]
This was due to some sloppiness in the data type returned by an internal function. It should now be fixed.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
