### ISSUE TITLE
Overlap issues in directories when groups have a lot of metadata

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#369]
There are overlap and wrapping issues caused when groups have a lot of metadata. For example:

https://openlabdev.commonsinabox.org/groups/self-clone-of-summer-2021-course/

This has never come up in testing because we never set up a test group with so many departments. We noticed this on the BMCC OpenLab, where some courses are associated with many different programs. Courses also have long titles. I've attached some example screenshots.

<img width="1277" alt="CBOXOLdevOverlap" src="https://user-images.githubusercontent.com/7189824/135814993-a204b495-5e29-4750-bbf0-c806be35d00c.png">

---

<img width="870" alt="DirectoryOverlap2" src="https://user-images.githubusercontent.com/7189824/135815059-ce5c42fb-dc68-4919-9b94-6aff8957532b.png">

--- 

<img width="915" alt="DirectoryOverlap1" src="https://user-images.githubusercontent.com/7189824/135815048-883a7072-98b2-4db8-ac03-86bf37d2dabe.png">

**Comment by boonebgorges** [comment]
The techniques used to build the directory grid were developed in ~2013, and include tricks like absolute positioning and max-height that make it nearly impossible to fix this problem within the current framework. The best way forward is to rewrite them to use modern grid techniques.

**Comment by bree-z** [comment]
Thanks, Boone. In the meantime, is there anything we could do with truncation that would help? Thanks!

**Comment by bree-z** [comment]
> We could try to mitigate the problem by truncating a bit more aggressively than we currently do. This might help by, for example, ensuring that group names don't extend to a third row. This would address the problem in at least some of your screenshots.

Let's go ahead and try the more aggressive truncation to see if that helps. Thanks!

**Comment by boonebgorges** [comment]
I've reduced the truncation target to 50 characters rather than 60 for the group name in directories. Please see whether this makes a difference.

**Comment by bree-z** [comment]
Thanks Boone. This is a little better. I tried replicating the amount of metadata for a few of the courses in the BMCC directory, and while some will still overlap, others no longer do (or, do so less). It also depends on how various groups are ordered in the directory at any one time. 

I think we can try this to see how it works out, and go from there.
