### ISSUE TITLE
Block Widgets: Site-wide footer appears with legacy widgets

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#376]
I'm not quite sure how to explain this -- seeing it might make more sense.

When I go to edit widgets, all the existing widgets appear as legacy widgets, but the sitewide footer shows up beneath each legacy widget. If I add new blocks (e.g. paragraph, image, etc), the sitewide footer doesn't appear with those. The footer doesn't appear on the front end of the site -- just when editing widgets in the Dashboard.

For example, see this site: https://openlabdev.commonsinabox.org/january-22-blah-course/wp-admin/widgets.php 

![BlockWidgetsWithFooter](https://user-images.githubusercontent.com/7189824/148910148-a7292468-f2e1-4e97-afe3-358d3f22c23a.png)

Thanks!

**Comment by bree-z** [comment]
One more thing -- if I add a new legacy widget, the footer does not appear.

**Comment by boonebgorges** [comment]
Thanks for the report. This should now be fixed.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
