### ISSUE TITLE
WP toolbar: Too many items can cause wrapping issues

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#381]
Hi Boone, 

When there are too many items in the WP toolbar (usually extra items added by plugins), the toolbar wraps to a second line and can obscure parts of the Dashboard. See, for example: https://openlabdev.commonsinabox.org/parvi-enim-primo/wp-admin/ 

In the example above nothing is obscured, but we discussed this with @profstein in a recent meeting where he showed us an example on one of his course sites, where it was difficult to access certain parts of the Dashboard.

We addressed this on the OpenLab, I believe in the following tickets:

http://redmine.citytech.cuny.edu/issues/2643 
http://redmine.citytech.cuny.edu/issues/2646

And for reference, these were also part of the larger ticket with a number of changes to the WP toolbar:

http://redmine.citytech.cuny.edu/issues/2545

<img width="1422" alt="Screen Shot 2022-04-11 at 12 14 20 PM" src="https://user-images.githubusercontent.com/7189824/162786690-62fc698c-2b59-48ee-b967-4c5a676a7372.png">

**Comment by boonebgorges** [comment]
To clarify the specific feature request: we want to allow toolbar items to span the full window width.

I've ported this change from the OL.

**Comment by bree-z** [comment]
Thanks Boone! The toolbar items are now spanning the full width, and I don't see any other issues on subsites.

The only thing that looks a little bit off is on other parts of the site (Homepage, My Profile, Group directories, etc), where after logging in, there's a gap between "Hi, Display Name" and "Log Out." See comparison below between openlabdev.commonsinabox.org and cboxopenlab.org.

I tested with a few different user types (faculty, student, admin) and browsers (Firefox, Chrome, Safari). 

Thanks!

<img width="1238" alt="devsite_toolbar" src="https://user-images.githubusercontent.com/7189824/166637075-d0ddca0f-cff8-4fbe-893f-9c70bed73153.png">

<img width="1194" alt="cboxopenlab_toolbar" src="https://user-images.githubusercontent.com/7189824/166637089-663481f7-170d-45a3-a053-1fcf61431064.png">

**Comment by boonebgorges** [comment]
That space is being caused by an extra element being inserted into the toolbar:

```
<li id="wp-admin-bar-pm_search"><a class="ab-item" href="#" title="Jump to a project"><span class="ab-icon icon-pm-switch-project" style="padding: 6px 0;"></span></a></li>
```

Searching the codebase on openlabdev.commonsinabox.org, it appears that this element is created by the wedevs-project-manager plugin. So it's not an issue with CBOX.

**Comment by bree-z** [comment]
This looks good, thanks!
