### ISSUE TITLE
OpenLab Attribution plugin: Icon missing from block editor toolbar

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#382]
We fixed this on the OpenLab, but I see that it's an issue on CBOX OpenLab. 

Redmine ticket: : http://redmine.citytech.cuny.edu/issues/3009 

Test site, where plugin is activated but the icon doesn't appear: https://openlabdev.commonsinabox.org/parvi-enim-primo/ 

Thanks!

<img width="660" alt="Screen Shot 2022-04-21 at 7 18 48 AM" src="https://user-images.githubusercontent.com/7189824/164447372-c0139219-3adb-46da-8cd5-9c68ced9455d.png">

<img width="958" alt="Screen Shot 2022-04-21 at 7 19 29 AM" src="https://user-images.githubusercontent.com/7189824/164447391-3289d10a-0f57-40d8-b81f-9b8acc59c292.png">

**Comment by boonebgorges** [comment]
I've ported the changes to the openlab-attributions distribution plugin, which will receive a release in advance of the next CBOX release. This is ready to test on openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
