### ISSUE TITLE
OpenLab Homepage: Headings should only increase by 1

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#385]
I've been looking at the OpenLab theme with an accessibility checker called [Axe Dev Tools](https://www.deque.com/axe/devtools/).

The OpenLab has 5 places where the heading level jumps by more than 1.

The primary place where this is happening is in the Display Area for Courses, Projects, Organizations, and Portfolios.

The words Courses, Projects, Organization and Portfolios or "activity-titles" are an H2, but the group names skip all the way to H4. 

It would be more appropriate for the group titles to be an H3, and that would elminate the error that we "skipped a heading level."

-
The other location on the homepage that we skip a heading level is when a logged in user is looking at the page "Welcome, (user name)" is an H1, but the "Need Help" directly below that is an H4.

-

Requirement(s)
Best Practice
WCAG Success Criteria
Not specified, or not applicable

**Comment by boonebgorges** [comment]
Thanks for the report. I've made the changes.
