### ISSUE TITLE
CBOX dashboard improperly inheriting styles from core

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#387]
Recent changes in core styling for the "welcome" screen have made the CBOX splash page look bad:

![Screenshot_2022-04-27_08-57-05](https://user-images.githubusercontent.com/246627/165535648-8cc28130-a80a-44c9-a53e-d1ec81fd0a83.png)

I think we were trying to be good citizens by using as much core infrastructure as possible (like `.welcome-panel`), but if they're going to make big changes like this, then we should probably have our own selectors and styles.

**Comment by r-a-y** [comment]
Ugh, good catch, Boone!

In commit 73569c7, I'm using new CSS classes for the CBOX admin dashboard, which should fix the display. Here's a screenshot:

![Screenshot of CBOX admin dashboard in WP 5.9.3](https://user-images.githubusercontent.com/505921/166586652-1eb947e6-74c6-4f53-8970-cdd5d6f9c891.png)

**Comment by boonebgorges** [comment]
This looks great - thanks, Ray!
