### ISSUE TITLE
OpenLab Homepage is missing H1 when not logged in

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#388]
If you visit the OpenLab Homepage, but don't log in, the page is missing a heading 1.

There is a discussion going on currently in WordPress about what best practice would look like for WordPress pages and templates.

https://github.com/WordPress/twentytwentytwo/issues/233

From the thread above, the suggestion is

> On single post and pages having the post/page title as h1
> On archive pages having the archive title as h1
> On the home page having the site title as h1
> 
> This is also the defalut behavior for the latest Defalut WordPress themes.

So my suggestion is the same, make the site title the H1 for the homepage, and if that content is reused elsewhere, don't mark as H1 in the footer. (That was an unintentional consequence of their first fix, and is also mentioned in the linked thread.)

If that fix is accepted, it might be worth looking at the structure of the logged-in page, to make sure it is still logical and follows best practices. Currently, the H1 on the logged-in homepage is "Hello, (first name last name)". That might be more appropriate as an H2.

**Comment by boonebgorges** [comment]
A single H1 on the homepage, with the site title, for logged-in or logged-out users, seems reasonable to me. However, it would be nice for the City Tech team to chime in, as they made a decision once upon a time to make the "Hello..." text into an H1, and the proposed change would reverse that decision.

**Comment by beckej13820** [comment]
Thanks! I don't have much of a horse in the race about whether hello.... should be an H1. There are some people who believe that there should only be one H1 on a page, and there are other people that say as long as your page has a recognizable outline structure that lets the user understand some of the structure on your page, then having multiple H1s is appropriate. 

As long as the first H1 is the site title (or another equivalent that is recognizable and describes the purpose of the page), I am very pleased.

**Comment by boonebgorges** [comment]
I've made the change.

**Comment by bree-z** [comment]
This looks good, thanks!
