### ISSUE TITLE
Port from City Tech OpenLab: Include ‘Sort’ dropdown on My Profile group lists

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#389]
Hi Boone, 

Can we port the sort dropdown that we added here: http://redmine.citytech.cuny.edu/issues/2922

Thanks!

**Comment by boonebgorges** [comment]
This will likely be a straightforward port and should be possible if funding allows.

**Comment by boonebgorges** [comment]
I've ported this feature and it's available to test.

**Comment by bree-z** [comment]
Thanks Boone! 

The functionality is working correctly, but is it possible to make the same layout adjustments you made in http://redmine.citytech.cuny.edu/issues/2922#note-5? 

Thanks!

<img width="1221" alt="CBOXOL" src="https://user-images.githubusercontent.com/7189824/181087222-45776f81-8baf-449d-9e74-ce22fcc4056b.png">

<img width="1182" alt="CTOL" src="https://user-images.githubusercontent.com/7189824/181087246-012dd4d0-eaf7-4ff3-8f96-9dd46f23edb4.png">

**Comment by boonebgorges** [comment]
Thanks, Bree. I've made the adjustment.

**Comment by bree-z** [comment]
This looks good, thanks!
