### ISSUE TITLE
Port from City Tech OpenLab: Improvements to attribution plugin from City Tech OpenLab

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#392]
Hi Boone, 

Can we port the following improvements we’ve made to the attribution plugin to CBOX OpenLab?

* Attributions modal should be movable: http://redmine.citytech.cuny.edu/issues/3026
* Mobile approach for Attribution plugin: http://redmine.citytech.cuny.edu/issues/3020
* Minor changes to attribution statement format: http://redmine.citytech.cuny.edu/issues/3061

Thanks!

**Comment by boonebgorges** [comment]
This is done.

**Comment by bree-z** [comment]
Hi Boone -  

When the plugin is activated, the icon for adding an attribution doesn't appear in the block toolbar. 

See, for example: https://openlabdev.commonsinabox.org/first-test-course-for-jan-2023-testing/wp-admin/post.php?post=25&action=edit 

Not sure if it's related, but we saw something similar on the City Tech OpenLab: http://redmine.citytech.cuny.edu/issues/3009 

Thanks!

<img width="1476" alt="Screen Shot 2022-12-27 at 8 00 53 AM" src="https://user-images.githubusercontent.com/7189824/209670440-2e5f6b29-74cd-4ede-8564-c750a24417f4.png">

**Comment by boonebgorges** [comment]
The `build` directory hadn't been synced. Please try again.

**Comment by bree-z** [comment]
Thanks Boone. This looks good! The only issue I see is the one reported (but not yet fixed) in http://redmine.citytech.cuny.edu/issues/3127

**Comment by boonebgorges** [comment]
I ported all recent openlab-attributions changes from the OpenLab and they will be part of the 1.4.0 release.
