### ISSUE TITLE
Port from City Tech OpenLab: Changes to email notifications

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#394]
Hi Boone, 

Can we port the changes we're making to email notifications to CBOX OpenLab? 

* Don't strip embedded media from outgoing email: http://redmine.citytech.cuny.edu/issues/3028
* Email Notifications > Links removed: http://redmine.citytech.cuny.edu/issues/3025

Thanks!

**Comment by boonebgorges** [comment]
We're still some way from deciding what will happen on the OpenLab for 3028. We'll need to build it there before we can decide whether it's easy and/or wise to include in CBOX.

For 3025, the OpenLab-specific fix is not very good, and not appropriate for CBOX. Ideally we'd fix the problem in BPGES https://github.com/boonebgorges/buddypress-group-email-subscription/issues/220, and our ability to do so will depend on summer funding. Let's hold off for a few weeks while this shakes out.

**Comment by boonebgorges** [comment]
For item 1, I've added openlab-email-embedded-media as a required plugin for the OpenLab package. 

I've set this up to test on openlabdev.commonsinabox.org. However, I can't get any emails to be sent by that site at the moment. @bree-z When you start testing, perhaps you could see if this is a problem specific to my account. If outgoing email is busted, I may instead need to switch to an SMTP sender for that site so that we can test features like this.

**Comment by bree-z** [comment]
I'm getting email notifications  on openlabdev.commonsinabox.org, but I don't see any media embeds or links in those notifications. 

When I check in https://openlabdev.commonsinabox.org/wp-admin/network/admin.php?page=cbox-plugins I see that 'Email Embedded Media' is active. 

See screenshots below of the email notifications for these two posts:

https://openlabdev.commonsinabox.org/omnia-peccata-paria-dicitis/2023/07/12/testing-media/
https://openlabdev.commonsinabox.org/omnia-peccata-paria-dicitis/2023/07/12/links/

<img width="687" alt="PostWithMedia" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/39e59dad-3dd9-4e3b-9c8e-769940a29c25">

<img width="724" alt="PostWithLinks" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/a03e8ad8-adcb-49cf-a301-90ede8117891">

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
