### ISSUE TITLE
Port from City Tech OpenLab: Search for bbPress

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#395]
Hi Boone, 

Can we port the addition of search for bbPress forums?

http://redmine.citytech.cuny.edu/issues/3060

Thanks!

**Comment by boonebgorges** [comment]
This is a moderate-sized port but it should be possible if funds are available.

**Comment by r-a-y** [comment]
For the Commons, I wrote a bbPress search plugin that shows up on the main forum listing page: https://github.com/r-a-y/bbp-single-forum-search. Not sure of the approach that CBOX-OL has taken, but thought I'd mention it.

**Comment by r-a-y** [comment]
> but I don't have all the access checks

My plugin also supports vanilla bbPress without BuddyPress integration.

Searching in non-BuddyPress forums requires the use of the the `?bbp_forum_id` URL parameter so the access checks are necessary there, so you probably do not have to duplicate those checks at all.

**Comment by boonebgorges** [comment]
Aha! My assumption was that bbPress handled the access stuff, and it sounds like my hunch was probably good. Thanks for chiming in! When I go to merge this, I'll review side-by-side with your plugin for other possible questions.

**Comment by r-a-y** [comment]
Was just taking a look at my commits and it looks like it might be necessary to do some access checks on the BuddyPress side for private and hidden group forums. See https://github.com/r-a-y/bbp-single-forum-search/compare/b6cd859...255d626.

**Comment by r-a-y** [comment]
> Was just taking a look at my commits and it looks like it might be necessary to do some access checks on the BuddyPress side for private and hidden group forums. See https://github.com/r-a-y/bbp-single-forum-search/compare/b6cd859...255d626.

Just did some testing. Looks like these commits are no longer necessary. I've updated `bbp-single-forum-search` to reflect this: https://github.com/r-a-y/bbp-single-forum-search/commit/a8e9f50af47697f58af767dbbb338620193ed7d8

**Comment by boonebgorges** [comment]
Awesome, thanks!

**Comment by boonebgorges** [comment]
I've done a direct port of the OpenLab implementation. Note that this also includes a few other small visual changes in http://redmine.citytech.cuny.edu/issues/3060 (see especially comment 4).

**Comment by bree-z** [comment]
Thanks Boone! This looks good. 

Just noting here that there are a number of visual differences between CBOX OL and City Tech OL, but all of those were from a different ticket: http://redmine.citytech.cuny.edu/issues/3079.
