### ISSUE TITLE
Template chooser: Change highlight color when selecting the template icon

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#396]
Hi Boone, 

I'll let @jennaspevack add more detail here. She wanted to make this adjustment to the front end of the template chooser.

Thanks!

**Comment by bree-z** [comment]
Hi Boone, 

We met with Jenna today and talked about this. Can we change the highlight color so that it matches the blue highlight color (I think #77ADE4) and style (blurred) of the category dropdown in the highlighted state?

Thanks!

<img width="873" alt="TemplateChooserOutlineStyle" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/2d7f8239-4a8e-46aa-984d-ea37e8be10a6">

**Comment by boonebgorges** [comment]
I've made the change.

**Comment by bree-z** [comment]
We're thinking the lighter blue with feathering is too subtle. Could we try the previous style (solid outline, no feathering) with the same lighter blue color?

Thanks!

**Comment by boonebgorges** [comment]
I've made the change.

![Screenshot_2023-07-12_11-28-32](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/7a9365e4-a774-4842-8e06-7fa31a2648df)

**Comment by bree-z** [comment]
I think this looks good, thanks! I'll just double check with @jennaspevack before closing the ticket.

**Comment by bree-z** [comment]
This looks good!
