### ISSUE TITLE
Add interface for selecting a group type's default template

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#398]
Here's a mockup from the City Tech team:

![image2](https://user-images.githubusercontent.com/246627/168146190-209e861d-cbf8-44f7-ba48-7590242e19e8.png)

Let's move the Template interface up above the custom strings, to make it easier to find.

We should also have some sort of logic that prevents conflicts between group-type-category settings and default templates for a group type. Specifically, if Template T is associated with Category C, and C is associated with Group Type GT, and you make T the default for GT, but then unassociate C from GT, things should not break. I'll investigate this a bit after I've done the initial integration, and I'll make suggestions for the best path forward.

**Comment by bree-z** [comment]
Thanks for all the detail in describing how this works! 

There's something odd I'm seeing but I can't figure out why:

When I look at the list of template sites for all group types except Courses ([in Dashboard > Group Settings > Types](https://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox-ol-group-settings&cboxol-section=types)), I see a line where there's a radio button, but there's no template name, and the links to dashboard and view template are for the main site (https://openlabdev.commonsinabox.org/wp-admin | https://openlabdev.commonsinabox.org/)

For example: 

<img width="1683" alt="Screen Shot 2022-07-21 at 5 17 29 PM" src="https://user-images.githubusercontent.com/7189824/180317533-c2c13b27-6496-41d3-8b32-9e9f5a5f9581.png">

Thanks!

**Comment by boonebgorges** [comment]
I've put a fix in place that should prevent invalid templates from appearing in the list. I have a feeling that this is an artifact of the weird nature of openlabdev.commonsinabox.org - having being built and rebuilt so many times. But if it crops up again, let me know so that I can do some deeper investigation.

**Comment by bree-z** [comment]
Thanks, Boone! 

I no longer see the issue with invalid templates, but when I create a new group and choose a site template, there is no site created. This is the case whether I choose "Site Template - Group" or another template.

For example: 
https://openlabdev.commonsinabox.org/groups/course-template-testing-1/
https://openlabdev.commonsinabox.org/groups/course-template-testing-2-english-template/

Here, I chose "Site Template - Courses":

<img width="1212" alt="CourseTemplateGeneralChosen" src="https://user-images.githubusercontent.com/7189824/180880547-8d909ad3-b53c-4845-bed9-7fcd4f52e203.png">

The [course](https://openlabdev.commonsinabox.org/groups/course-template-testing-1/) was created without an associated site:

<img width="1233" alt="CourseWithNoSite" src="https://user-images.githubusercontent.com/7189824/180881365-8066c215-5bd1-47de-adf5-280ee2c1d540.png">

**Comment by boonebgorges** [comment]
I believe I tracked down the source. Ready to test on openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
I believe I've tested this exhaustively enough, including a few scenarios where a template was set as the default for a group type and then the category was unassociated with that group type. Everything worked as expected.

I do have one question though. Now that we've moved up the templates, one potential issue with the UI is that if users change the default template, it may not be apparent that, they have to scroll down to the bottom to click the 'Save' button. Could we indicate in some way that users need to do this after making their selection? Not sure if this could be an additional 'Save' button that appears beneath the list of sites, or some text?

Thanks!

<img width="1732" alt="ListOfTemplates" src="https://user-images.githubusercontent.com/7189824/183725259-cb6f3409-de5b-4512-9899-9a80101e3c22.png">

**Comment by boonebgorges** [comment]
In a future release, we could think about how to improve the interface here. There are lots of possibilities:
- A Save control below each section
- A visual indicator (like a different color outline, or perhaps extra text in the accordion handle, near the word 'Courses') indicating "dirty" unsaved states
- Accordions/collapsibles for long subsections like 'Labels'

I don't think any of this is feasible for the current release.

For what it's worth, changing the default template does trigger the browser's internal "dirty" state, so that if you try navigating away from the page without saving, you'll get an 'Are you sure?' notice from the browser. Not perfect, but hopefully it helps to avoid unintended data loss until we have a better solution.

**Comment by bree-z** [comment]
Thanks Boone! 

I opened up #405 for exploring interface improvements.
