### ISSUE TITLE
Move Site Template and Template Categories to Group Settings subnavs

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#399]
Here's how it looks with Badges:

![image6](https://user-images.githubusercontent.com/246627/168146834-7090dcdf-c097-45c9-943d-697965c26cd5.png)

We should do something similar for Site Templates, and probably also provide a link to Template Categories on the same tab.

**Comment by boonebgorges** [comment]
Here's a first pass:

![Screenshot_2022-05-12_13-59-02](https://user-images.githubusercontent.com/246627/168148914-4fb0b727-9f53-4a8d-9541-7037a65d61b0.png)

I created a single tab 'Site Templates', with links to both 'Site Templates' and 'Site Template Categories'. The wording could probably use some work here - Categories are the mechanism by which Site Templates are linked to Group Types, which is kind of a complex concept.

**Comment by bree-z** [comment]
Everything looks good here. Just wondering whether this seems OK for the initial paragraph:

The Site Templates admin page allows the network administrator to create new site templates that can be assigned to different group types. Site Template Categories serve as the method for linking Site Templates to Group Types. When users create a new group with an associated site, they will see options to choose any of the site templates that have associated categories linked with that group type.

Thanks!

**Comment by boonebgorges** [comment]
I've made the change to the intro paragraph.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
