### ISSUE TITLE
OpenLab: Fix messages pagination

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/commons-in-a-box#401]
Reported here:
https://cboxopenlab.org/groups/help-forum/forum/topic/users-cannot-access-any-page-of-paginated-ol-messages-except-the-first-page/

PR opened for the `openlab-theme` repo here: https://github.com/cuny-academic-commons/openlab-theme/pull/311

**Comment by boonebgorges** [comment]
https://github.com/cuny-academic-commons/openlab-theme/pull/311 has been merged. Thanks, @r-a-y !
