### ISSUE TITLE
OpenLab Export/Import plugin enhancements

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#403]
Hi Boone, 

We realized that there was no ticket for this yet, and also that there were many unresolved questions in the doc. Jenna and I worked on this together today, and hopefully it's clear! Let us know if you have any questions. Thanks!

https://docs.google.com/document/d/15RJmK8Qz2WaCwoqayw4qI_e9279XNpQGvSW7rfQydUM/edit#

**Comment by bree-z** [comment]
Thanks Boone, this is looking good so far! Just wondering if we can increase the size allowed for file uploads a bit just so I can test some larger files? It doesn't have to be too much, but I think it's only 1mb right now.

Thanks!

**Comment by boonebgorges** [comment]
Sounds good. I've bumped it to 15MB on openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
Thanks Boone! 

After doing some more testing, I think there's an issue with attachments and possibly menus.

I exported a site including all content, with attachments. Some of the images are appearing broken on the import site, and the menu doesn't appear to have imported correctly. It includes the menu items on the export site, but also the menu items that were included in the import site menu. I'm not sure if that happened because both sites had menus with the same name ("Main menu"). And, the custom links that were imported from the old site still point to the old site. Is that correct functionality?

Export site: https://openlabdev.commonsinabox.org/rationis-enim-perfectio/
Import site: https://openlabdev.commonsinabox.org/blank-project-2/

Examples:
import: https://openlabdev.commonsinabox.org/blank-project-2/2022/07/29/more-testing/
export: https://openlabdev.commonsinabox.org/rationis-enim-perfectio/2022/07/29/more-testing/
import: https://openlabdev.commonsinabox.org/blank-project-2/resources/
export: https://openlabdev.commonsinabox.org/rationis-enim-perfectio/resources/

I also did an export of all content without attachments. None of the attachments were imported, even though the export site was public:

Export site: https://openlabdev.commonsinabox.org/rationis-enim-perfectio/
Import site: https://openlabdev.commonsinabox.org/blank-project-4/

I also have one more question about exporting from sites on openlabdev.commonsinbox.org. The content type checkboxes that appear beneath 'All Content' include a lot of content types that seem specific to CBOX OL more generally, but I'm not sure why they would be included in the checklist for subsites.  The screenshot below is from [this site](https://openlabdev.commonsinabox.org/template-course-728-1/wp-admin/tools.php?page=openlab_site_export) but they appear on all sites. Nothing actually seems to be included for any of these items in any exports or imports.

Thanks!

<img width="1423" alt="ContentTypes" src="https://user-images.githubusercontent.com/7189824/181650292-6c394d71-f5b6-45cb-81a1-b4b622726bef.png">

**Comment by boonebgorges** [comment]
Hi Bree,

Thanks for the testing. You've reported many things in this comment - I'll try to reply to them all, but please make a note if I miss something.

> I exported a site including all content, with attachments. Some of the images are appearing broken on the import site,

I'm not sure how this didn't come up before, including on the OpenLab, but WordPress has some odd behavior that causes imported thumbnails to have a suffix appended to their filenames, even if they weren't suffixed on the original site. See https://core.trac.wordpress.org/changeset/46822. As such, there was a mismatch between the filenames as they existed on the import site (suffixed) and the way the corresponding metadata was stored along with the Media Library items (unsuffixed). I've added a change that should address this https://github.com/openlab-at-city-tech/openlab-import-export/commit/9c6bd382ef8493fc3315d15fb8f4c23b9f36c015

> the menu doesn't appear to have imported correctly. It includes the menu items on the export site, but also the menu items that were included in the import site menu. I'm not sure if that happened because both sites had menus with the same name ("Main menu").

Yes, this is the issue. If you have similarly named menus, they'll be "merged". I don't know if this is desired behavior - I can see it going any number of ways (merge; never overwrite the existing menu; always overwrite the existing menu).

> And, the custom links that were imported from the old site still point to the old site. Is that correct functionality?

Yes. For certain kinds of links - `post_type` and `taxonomy`, ie those that are internally linked to a post, a term, or an archive - we detect that they're internal, and we do the swap-outs. For custom links, we can't reliably know what the user intends to point to. It's easy to imagine cases where you'd want a custom link to point to the same URL as the parent site (say, sub-sections of a larger course, pointing to the Syllabus page on the parent). If you want this behavior changed, we should have a separate thread about it.

> I also did an export of all content without attachments. None of the attachments were imported, even though the export site was public:

I'm not sure I follow. If you export "all content without attachments", then it's expected behavior that none of the contents would be imported.

> The content type checkboxes that appear beneath 'All Content' include a lot of content types that seem specific to CBOX OL more generally, but I'm not sure why they would be included in the checklist for subsites. 

I've added logic that excludes these post types from appearing in the list.

**Comment by bree-z** [comment]
Thanks Boone! 

> there was a mismatch between the filenames as they existed on the import site (suffixed) and the way the corresponding metadata was stored along with the Media Library items (unsuffixed). I've added a change that should address this

I'm now seeing more images embedding correctly, but it's inconsistent.  For example:

Export site: https://openlabdev.commonsinabox.org/rationis-enim-perfectio/

1. I exported 'All Content' and downloaded the archive with attachments. I imported into [this site](https://openlabdev.commonsinabox.org/blank-project-8/).
* In Firefox and Safari, most images appear correctly, except the one in [this post](https://openlabdev.commonsinabox.org/blank-project-8/2021/07/22/assignment-1/), one in the gallery on [this page](https://openlabdev.commonsinabox.org/blank-project-8/syllabus/), and the same image from the gallery doesn't appear on [this page](https://openlabdev.commonsinabox.org/blank-project-8/resources/). I noticed that on the source site, the image name is "IMG0579-scaled.jpg", if that's helpful.
* In Chrome, images don't appear in [this post](https://openlabdev.commonsinabox.org/blank-project-8/2022/07/29/more-testing/) or [this post](https://openlabdev.commonsinabox.org/blank-project-8/2021/07/22/assignment-1/), or [this page](https://openlabdev.commonsinabox.org/blank-project-8/resources/), and two images don't appear in [the gallery](https://openlabdev.commonsinabox.org/blank-project-8/syllabus/)

2. I exported all posts, pages, media, and menus created by the testfaculty user. When I imported this archive, images didn't appear in any posts (https://openlabdev.commonsinabox.org/blank-project-10/). However, all images (except the same one from above) did appear in the gallery on [this page](https://openlabdev.commonsinabox.org/blank-project-10/syllabus/). The image did appear in [this page](https://openlabdev.commonsinabox.org/blank-project-10/resources/), which is the same page where it did not appear in the example above. This is the same in all browsers.

> If you have similarly named menus, they'll be "merged". I don't know if this is desired behavior - I can see it going any number of ways (merge; never overwrite the existing menu; always overwrite the existing menu).

I think the merged behavior is fine, thanks!

> For custom links, we can't reliably know what the user intends to point to. It's easy to imagine cases where you'd want a custom link to point to the same URL as the parent site

This is also makes sense.

> If you export "all content without attachments", then it's expected behavior that none of the contents would be imported.

Sorry if I misunderstood. In the [comment above](https://github.com/cuny-academic-commons/commons-in-a-box/issues/403#issuecomment-1159143415) it says: 

> When the archive does not contain attachments, the importer attempts to fetch the items via their original URL. If the original URL is inaccessible - item is deleted, site is private, site is unavailable - that specific item is skipped. (This is the way the WP tool works.)

I thought this meant that if the export site was public, the attachments should be pulled from that site into the importing site.

> I've added logic that excludes these post types from appearing in the list.

I still see Academic Term, Academic Units, etc. I tried refreshing and clearing my cache.

Thanks!

**Comment by boonebgorges** [comment]
> I thought this meant that if the export site was public, the attachments should be pulled from that site into the importing site.

Right, sorry, I think I lost the thread of the conversation a bit. You're correct that this is what ought to happen. I found one or two logic errors that were preventing remote items from being reliably pulled over. These issues should now be resolved - please give another test.

As for the other missing images, I'm afraid that I might have failed to update openlabdev.commonsinabox.org properly before your last round of testing. I'd neglected that openlab-import-export is a separate repo, and my deployment script didn't account for it. I've fixed this, and it seems that these missing images are no longer missing. Please let me know what you find.

**Comment by bree-z** [comment]
Thanks Boone!

> I found one or two logic errors that were preventing remote items from being reliably pulled over. These issues should now be resolved - please give another test.

This looks good -- all images are being pulled correctly from public source sites. 

> As for the other missing images....I've fixed this, and it seems that these missing images are no longer missing. Please let me know what you find.

All images are being imported correctly, except for one: IMG0579.jpg, which appears on these two pages:

https://openlabdev.commonsinabox.org/blank-project-12/resources/
https://openlabdev.commonsinabox.org/blank-project-12/syllabus/

Thanks!

**Comment by boonebgorges** [comment]
> All images are being imported correctly, except for one: IMG0579.jpg, which appears on these two pages:

There were two separate issues here, both having to do with the way that URL replacements take place after post content import. I've pushed another attempt to fix this - please have a look.

**Comment by bree-z** [comment]
Thanks Boone! All images are being imported correctly.

**Comment by bree-z** [comment]
Hi Boone, 

Sorry -- one more question. Will this be included as an official part of CBOX OpenLab, or is it a standalone plugin that people can download?

Thanks!

**Comment by boonebgorges** [comment]
From a technical point of view, `openlab-import-export` is a separate plugin.

I hadn't planned to make it available on wordpress.org at this time. So, while the plugin would be available for download from GitHub, it won't be possible to install it via the normal WP plugin installation mechanisms. That said, the plugin is written in such a way that it should be possible to use it outside of CBOX, and we could decide to make it available on wordpress.org at some point in the future.

I'd intended to pull the plugin into the commons-in-a-box package, at the time that I build the commons-in-a-box release. This is similar to how we handle openlab-attributions, openlab-private-comments, and openlab-badges - they're standalone plugins living in their own GitHub repositories, but we ship them along with commons-in-a-box.

When we ship a plugin with commons-in-a-box, we must put it into one of the following categories:
1. Required - plugins that cannot be turned off when using CBOX-OL
2. Recommended - plugins that can be turned off when using CBOX-OL. The only plugin currently in this category is BP Event Organiser.
3. Optional - This generally refers to plugins that require some outside software that isn't turnkey, so we are wary of "recommending" it. This category includes BP Reply By Email and BP Braille.
4. Install-only - These are generally plugins that we like and that work well with CBOX-OL, but which are meant to be used on specific sites. We allow them to be installed, but we don't activate them - they can be turned on by the individual site admins, or the super admin can network activate. Anthologize, OpenLab Private Comments, and PressForward are examples of this.

I think we would probably put openlab-import-export into category 4, though I think there's an argument for making it Required instead (mainly that the import/export tools are only useful if they're activated broadly). I guess this is a question for the team.

**Comment by bree-z** [comment]
Hi Boone, 

Small thing, but on the export page, there's too much space between the buttons for exporting with/without media and the explanatory text. 

Thanks!

<img width="2077" alt="Screen Shot 2022-12-30 at 5 57 37 AM" src="https://user-images.githubusercontent.com/7189824/210101499-c1c6df8a-35ed-4706-b741-46cc1b815522.png">

**Comment by boonebgorges** [comment]
Small indeed :-D This only arises on very wide screens.

The only way to create equal-width columns without having a bunch of empty space (given the different length of the button text in different languages and for different zoom sizes) is to convert the markup to a table, and I don't feel like doing that. So I've mitigated with a change that should make it mostly align in English at normal zoom levels; in other locales, the explanatory text for the two buttons may not be in perfect alignment. https://github.com/openlab-at-city-tech/openlab-import-export/commit/5e2aef256bde5de9e6abc0883df60aa26577fc39

**Comment by bree-z** [comment]
Whoops, I recently upgraded my monitor to postpone moving to the next level of reading glasses strength. :)

This now looks good on the wide screen, and narrower sizes. And I didn't find any other issues in testing, so I think we can close this. 

Thanks!
