### ISSUE TITLE
Replace or remove icon16 icons

### ISSUE THREAD

**Issue by sabernhardt** [cuny-academic-commons/commons-in-a-box#404]
If WordPress Core removes the `.icon16` styles (see [Trac 35717](https://core.trac.wordpress.org/ticket/35717)), this plugin could break a little because of the negative left margin.

https://github.com/cuny-academic-commons/commons-in-a-box/blob/81a51b8dbf6f1c5ecf4bf67a513c9e1832e9ba47/admin/admin-loader.php#L1256

**Option 1:** Replace the two `span` elements in the [classic welcome panel](https://github.com/cuny-academic-commons/commons-in-a-box/blob/81a51b8dbf6f1c5ecf4bf67a513c9e1832e9ba47/admin/templates/classic/getting-started.php#L11) with dashicons.

`<span class="dashicons-before dashicons-admin-settings" aria-hidden="true"></span>`
`<span class="dashicons-before dashicons-admin-appearance" aria-hidden="true"></span>`

Then those icons could be positioned to the side:

```
.getting-started-cbox-classic h4 {
    position: relative;
}
.getting-started-cbox-classic h4 .dashicons-before {
    position: absolute;
    top: 0;
    left: -26px;
    color: #8c8f94;
}
```

**Option 2:** Simply remove the icons.

And if you disagree with removing the styles from Core, please comment on the ticket.

**Comment by r-a-y** [comment]
Thanks @sabernhardt for letting us know about the proposed WP core change. Option 1 works well. See commit f354c67.
