### ISSUE TITLE
OpenLab: Wrong count on "Academic Units" admin page

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/commons-in-a-box#407]
Reported here: https://cboxopenlab.org/groups/help-forum/forum/topic/buddypress-profile-types-categories-show-zero-counts-and-disallow-parent-chil/

Screenshot:
![Image](https://cboxopenlab.org/?get_group_doc=2/1659446834-ScreenShot2022-08-01at3.22.12PM.png)

The counts listed under the "Academic Units" admin page do not update when a member or group is updated with a specific Academic Unit.

The issue is Academic Units are added as post types, but when a member or group is categorized with an Academic Unit, this uses separate taxonomies: https://github.com/cuny-academic-commons/cbox-openlab-core/blob/2fa4ef1a1c1857b0badd8f3ba3cd002c658493ff/includes/academic-units.php#L48-L63

If we wanted to display the counts, we would probably need two separate Count columns for members and groups respectively and to calculate those counts ourselves.

**Comment by boonebgorges** [comment]
I think that for now I'll just hide the Parent and Count columns.
