### ISSUE TITLE
'Create New' link appears on Portfolios directory 

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#415]
Hi Boone, 

There's a 'Create New' link that appears on the Portfolios directory. It only appears when I'm not logged in, or logged in as a user without a portfolio.

I'm not sure if this is small enough to fit into the release, but if not it can wait. 

Thanks!

<img width="1207" alt="CreateNewLinkPortfolios" src="https://user-images.githubusercontent.com/7189824/200499078-fd7d8403-5d1f-4c15-91db-d55b71b8fb8e.png">

**Comment by boonebgorges** [comment]
Looking at the code, it appears that the intended behavior is for the link to show to logged-in users without a portfolio, and it's a bug that it shows to non-authenticated users. I've corrected this bug in cuny-academic-commons/openlab-theme@87c72e90292768265a5807116b76daa3eaa1fba9
