### ISSUE TITLE
Log In Button Overflows on Subsites on OpenLab when not logged in

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#416]
Here's a screenshot/example:

<img width="1431" alt="Screenshot 2022-11-09 at 1 52 52 PM" src="https://user-images.githubusercontent.com/29982981/200916817-692fe971-0690-48c6-b4f0-bb45e355c468.png">

On some subsites, specifically when not logged in, the log in button is overflowing the log in button container, so it just looks like "Log"

This screenshot was taken on a laptop computer, in full-screen mode on chrome, with 100% zoom, so not a particularly unusual screen size.

**Comment by boonebgorges** [comment]
Are you able to share the URL of a public site that exhibits the problem? I suspect that a CSS declaration in the theme is causing the issue.

**Comment by beckej13820** [comment]
Yes,

URL: https://spillmagazine.oneonta.sunycreate.cloud/

That would make sense if it was a theme specific problem, because I only noticed it on one site. Uses the Gutenix theme.

**Comment by boonebgorges** [comment]
Thanks, @beckej13820 . It is indeed theme-specific. The theme says the following:

```css
a {
  font-weight: 700;
}
```

which causes the text to expand beyond the available space. A short-term fix would be:

```css
.oplb-bs a {
  font-weight: normal;
}
```

That being said, the way that CBOX OpenLab styles these buttons is not good. We place a max-width on the bp-login button https://github.com/cuny-academic-commons/openlab-theme/blob/2216c96640c023bc0056c00fb8c8f05851d57e29/less/openlab-toolbar.less#L522. This is likely to cause problems not just with typographical variations like the one on your site, but also with languages where the 'Log In' string is a bit longer. We'll adjust this for a future release.

**Comment by boonebgorges** [comment]
This should be fixed by https://github.com/cuny-academic-commons/openlab-theme/commit/4e86a7810aa38a50407fce3f9b522bc571841a78
