### ISSUE TITLE
Updates to text on CBOX OpenLab Dashboard splash page

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#418]
Hi Boone, 

The blurb describing the project on the splash page for the CBOX OpenLab Dashboard (/wp-admin/admin.php?page=cbox) is a bit out of date. Could we change it to the following:

> Commons In A Box OpenLab is designed for teaching, learning, and collaboration. It allows faculty members, departments, and entire institutions to create commons spaces for open learning.  
> 
> It was created through a collaboration between [The Graduate Center, CUNY](http://www.gc.cuny.edu/) and [New York City College of Technology, CUNY](http://www.citytech.cuny.edu/) with funding from the National Endowment for the Humanities’[ Office of Digital Humanities](https://www.neh.gov/divisions/odh). Funding for continued development of new features has been provided by the[ CUNY Open Educational Resources Initiative](https://www.cuny.edu/libraries/open-educational-resources/) and our partners at the [BMCC OpenLab](https://openlab.bmcc.cuny.edu/).

Thanks!

**Comment by bree-z** [comment]
Thanks Boone! This looks good, except for a typo in the GC URL: http.://www.gc.cuny.edu/

**Comment by boonebgorges** [comment]
Thanks for the review. This should now be fixed.

**Comment by bree-z** [comment]
This looks good, thanks!
