### ISSUE TITLE
CBOX OpenLab dev site update error

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#419]
Hi Boone, 

I went to the dashboard on openlabdev.commonsinabox.org to check something for the ticket I just added, and it started automatically updating plugins. All updated successfully except OpenLab Attributions. I got the following error (just part of the text):

> An error occurred while updating OpenLab Attributions: The update cannot be installed because some files could not be copied. This is usually due to inconsistent file permissions. .git, .git/branches, .git/hooks, .git/hooks/applypatch-msg.sample, .git/hooks/commit-msg.sample, .git/hooks/fsmonitor-watchman.sample, .git/hooks/post-update.sample, .git/hooks/pre-applypatch.sample, .git/hooks/pre-commit.sample, .git/hooks/pre-merge-commit.sample, .git/hooks/pre-push.sample, .git/hooks/pre-rebase.sample, .git/hooks/pre-receive.sample, .git/hooks/prepare-commit-msg.sample, .git/hooks/push-to-checkout.sample, .git/hooks/update.sample, .git/info, .git/info/exclude, .git/logs, .git/logs/refs, .git/logs/refs/heads, .git/logs/refs/heads/2.0.x, .git/logs/refs/heads/build, .git/logs/refs/heads/main, .git/logs/refs/remotes, .git/logs/refs/remotes/origin, .git/logs/refs/remotes/origin/2.0.x, .git/logs/refs/remotes/origin/HEAD, .git/logs/refs/remotes/origin/build, .git/logs/refs/remotes/origin/main, .git/logs/HEAD, .git/objects, .git/objects/00, .git/objects/00/076cbd4bdf997556290319639cd3ce1c351b18, .git/objects/00/07e039b524a7b7afd95b0d4c72483b11bee999, .git/objects/00/885ff7c66f32a3fe209732f1c8c93d062236a7...

Now when I try to get back to the Dashboard, it keeps attempting to update that plugin so I just logged out. I'm not testing anything, so no rush, but just fyi .

Thanks!

**Comment by boonebgorges** [comment]
The copy of openlab-attributions that had been running on openlabdev.commonsinabox.org was a Git checkout, and as such the WP application was unable to overwrite it. For the time being, I've removed the Git checkout and let CBOX install its own copy of the plugin. I'll have to swap this again when the time comes to test changes to openlab-attributions before the 1.4.0 release.

**Comment by bree-z** [comment]
Thanks, Boone. Something is still off here, because I can't get to the main page of the CBOX OpenLab Dashboard. I see that OpenLab Attributions is being updated. Then it says it was successfully updated, but if I click 'Continue to CBOX Dashboard', it just does the same thing.

Thanks!

<img width="816" alt="Screen Shot 2022-12-12 at 2 48 47 AM" src="https://user-images.githubusercontent.com/7189824/206990483-9e678e25-98b3-4228-aabd-b478284ea70d.png">

**Comment by boonebgorges** [comment]
There was a version mismatch causing the upgrader to enter a loop. This should now be fixed. (Again, an artifact of the testing site, nothing that needs fixing in the software.)

**Comment by bree-z** [comment]
Thanks Boone! This is no longer an issue.
