### ISSUE TITLE
Comments don't appear in group home feed

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#420]
Hi Boone, 

I'm seeing the same issue we found on the OpenLab in [3125](http://redmine.citytech.cuny.edu/issues/3125).

For example, there are a few comments on the course site that don't appear in the course home comments feed: https://openlabdev.commonsinabox.org/groups/rationis-enim-perfectio/

Thanks!

**Comment by boonebgorges** [comment]
I've ported the fix to the 1.4.x branch.

**Comment by bree-z** [comment]
This looks good, thanks!
