### ISSUE TITLE
Template chooser: Templates appearing in Group Settings > Site

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#423]
Hi Boone, 

When I go to Group Settings > Site, the template chooser interface appears beneath 'Associated Site Details'. I'm thinking it shouldn't appear here -- is that correct? See the screenshot below, from this group:

https://openlabdev.commonsinabox.org/groups/rationis-enim-perfectio/admin/site-details/

<img width="1203" alt="Screen Shot 2022-12-29 at 9 03 55 AM" src="https://user-images.githubusercontent.com/7189824/209964587-f54f1b21-42f9-46f1-9390-20b1acf4dc49.png">

However, if you unlink the associated site and then create a new one, should it appear then?  See, for example: 

<img width="1208" alt="Screen Shot 2022-12-29 at 9 12 28 AM" src="https://user-images.githubusercontent.com/7189824/209965558-8c70e051-cea3-4573-b399-41fe16628edc.png">

Thanks!

**Comment by boonebgorges** [comment]
I would say: It *should not* appear in the first screenshot (ie when editing an existing site), but it *should* appear when creating a new site on a group with no associated site. Does that seem correct to you?

**Comment by bree-z** [comment]
Yes, that makes sense, thanks!

**Comment by boonebgorges** [comment]
Thanks, I've made the change. I did a quick test and it appears that the Associated Site Template setting works properly when creating a new site on an existing group, but you may want to verify this.

**Comment by bree-z** [comment]
Thanks Boone! This looks good to me.
