### ISSUE TITLE
Site post activity doesn't appear in 'What's Happening' activity feed

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#424]
Hi Boone, 

When I publish a post on the site of a public group, it doesn't appear in the 'What's Happening' activity feed on the homepage. 

In the screenshot below, there are two posts that should have appeared in the feed but didn't:

* https://openlabdev.commonsinabox.org/first-test-course-for-jan-2023-testing/2022/12/29/eam-si-varietatem/
* https://openlabdev.commonsinabox.org/cosmo-ortiz-portfolio-3/2022/12/29/eam-si-varietatem/

Thanks!

<img width="405" alt="Screen Shot 2022-12-29 at 11 47 54 AM" src="https://user-images.githubusercontent.com/7189824/209985977-cd17ab5b-c301-4157-8720-2b82b4a60d72.png">

**Comment by boonebgorges** [comment]
The site in question has the privacy setting 'Discourage search engines...' (`blog_public=0`). In these cases, BuddyPress marks the activity items as `hide_sitewide=1`, which means that they don't show up in  public feeds like 'What's Happening'. See https://openlabdev.commonsinabox.org/cosmo-ortiz-portfolio-3/wp-admin/options-reading.php, redmine.citytech.cuny.edu/issues/2297

You could verify this by creating posts from fully-public sites.

**Comment by bree-z** [comment]
Thanks Boone! Sorry about that. When I create a post from a fully-public site it appears in the feed. 

One question though: Is it correct behavior that comments from sites with the 'Discourage search engines' privacy setting *do* appear in the public feed? See, for example, this post where the post didn't appear in the feed but the comment did:

https://openlabdev.commonsinabox.org/first-test-course-for-jan-2023-testing/2022/12/30/ask-search-engines-not-to-index/

Thanks!

**Comment by boonebgorges** [comment]
Yes, that seems incorrect. I reviewed and found that the discrepancy is due to 18dc292a5270511698f4994e16a7fdbd3fd4e02d https://github.com/cuny-academic-commons/openlab-theme/issues/167. The modification in that commit was limited to 'new_blog_post'. I've changed it to apply to 'new_blog_comment' as well.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
