### ISSUE TITLE
Braille plugin still maintained?

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#425]
Hi Boone, 

I don't think this has been tested on openlabdev.commonsinabox.org in a while but before I go much further testing this I just wanted to check whether it's still supported. 

When I activate it on https://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox-plugins&type=optional, it says: Requires: Braille (>=0.0.3) (disabled).

<img width="755" alt="Screen Shot 2022-12-31 at 6 52 30 AM" src="https://user-images.githubusercontent.com/7189824/210135870-e7f020ab-f323-41b8-a4b0-112551ee9fef.png">

Thanks!

**Comment by boonebgorges** [comment]
> When I activate it on https://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox-plugins&type=optional, it says: Requires: Braille (>=0.0.3) (disabled).

The "disabled" text just means that the Braille WP plugin is not active on the main site. It's a quirk of the way our messaging works alongside our logic for required plugins. In the case of "Member Site Plugins", it's not necessary to have the prerequisite plugins active on the main site - just on the secondary sites. I wonder if @r-a-y has thoughts about whether we should use different text in this context.

As for the Braille plugin, it's not receiving regular attention, but I don't think it's abandoned in the sense that it should be taken out of CBOX-OL at this time.

**Comment by bree-z** [comment]
Thanks, Boone. 

Last time this was tested it was already set up on the main site, and to test on a subsite I just copied the settings from the main site. Looking at the plugin [instructions](https://wordpress.org/plugins/braille/), it looks like I need the URL for a remote LibLouis service. Is this something I can test, or should I not worry about it?

Thanks!

**Comment by r-a-y** [comment]
> I wonder if @r-a-y has thoughts about whether we should use different text in this context.

We can remove the `(disabled)` label on the "Community Features" plugins page if we feel that is confusing or use a different label instead? Or maybe we just allow the `(disabled)` label for Recommend plugins only?

**Comment by r-a-y** [comment]
In commit aa307ff, I've decided to hide the `(disabled)` label if the required plugin is an install-only plugin to avoid confusion.

Instead of hiding the `(disabled)` label, we could add a different label if desired. Let me know if we want to do that instead.

**Comment by boonebgorges** [comment]
I like this fix, @r-a-y - thank you! I think it resolves the current issue sufficiently for this release.
