### ISSUE TITLE
Site-wide footer appears when editing widgets on a sub-site

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#426]
Hi Boone, 

I think I'm seeing the same issue as reported in #376 . 

See, for example: https://openlabdev.commonsinabox.org/first-test-course-for-jan-2023-testing/wp-admin/widgets.php

![WidgetsFooter](https://user-images.githubusercontent.com/7189824/210136218-9c209133-2776-416e-86b6-c6b71008f236.png)

Thanks!

**Comment by boonebgorges** [comment]
It appears that WP changed the way these legacy widget previews are rendered. A new fix is in place.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
