### ISSUE TITLE
Member Settings > Types: Singular/Plural labels for new type not pre-filled

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#427]
When I create a new member type, the fields for the singular and plural labels are pre-filled with '[object Object]' rather than the new member type name. 

I can delete that and replace it with the correct label and successfully save the correct labels. It's only the initial state that's incorrect. 

Thanks!

<img width="1140" alt="Screen Shot 2023-01-02 at 11 29 56 AM" src="https://user-images.githubusercontent.com/7189824/210260298-47fc3ecb-0419-4f79-b361-c3ab71f46b03.png">

**Comment by boonebgorges** [comment]
The fields ought to be empty. When you start typing the 'Name' field, that value will be copied into the Singular and Plural fields. I have pushed up a fix to test.

**Comment by bree-z** [comment]
Thanks Boone! Functionality now matches what you describe.
