### ISSUE TITLE
Port buddypress-docs-in-group plugin pagination fix

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#429]
Hi Boone - This is for porting over the fix for the pagination issue in [3080](http://redmine.citytech.cuny.edu/issues/3080).

I verified that it's also an issue on CBOX OpenLab, e.g.: https://openlabdev.commonsinabox.org/groups/ancient-political-thought/docs/page/2/ 

Thanks!

**Comment by boonebgorges** [comment]
Thanks - I've pushed a fix.

**Comment by bree-z** [comment]
This looks good, thanks!
