### ISSUE TITLE
Typo in 'Add to Portfolio' Citation text

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#431]
There's a small typo in the Citation text in the 'Add to Portfolio' functionality. The word "originally" is spelled "originaly".

It appears in two places: the modal window that appears after clicking 'Add to Portfolio', and the citation text that appears at the top of the post added to the portfolio site.

City Tech OpenLab ticket: http://redmine.citytech.cuny.edu/issues/3135 

<img width="629" alt="Screen Shot 2023-03-07 at 3 37 44 AM" src="https://user-images.githubusercontent.com/7189824/223369633-47ebd267-801d-4b0f-9df2-55f81e624f9d.png">

<img width="649" alt="Screen Shot 2023-03-07 at 3 39 06 AM" src="https://user-images.githubusercontent.com/7189824/223369650-8ceabba0-0ed7-48d5-91fb-566de525f270.png">

**Comment by boonebgorges** [comment]
You've noted two places where the text appears, but it comes from a single location, which is fixed in https://github.com/openlab-at-city-tech/openlab-portfolio/commit/7a015b59e308d3fd09545ed755d3307b7bc41484. This will only apply to newly-created citations.

**Comment by bree-z** [comment]
This looks good, thanks!
