### ISSUE TITLE
Hide Settings for Docs

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#434]
The Settings section that appears when creating or editing a Doc should be hidden.

See: http://redmine.citytech.cuny.edu/issues/3174

> These settings are hidden by design. The OpenLab uses a plugin called buddypress-docs-in-group, which forces all Docs interfaces to be located inside of wrapper of a single group. With this plugin active, permissions are inherited from the parent group. It's a bug that it shows on CBOX-OL.

**Comment by boonebgorges** [comment]
The proper fix has been ported in 1224174.

**Comment by bree-z** [comment]
This looks good, thanks!
