### ISSUE TITLE
Feature Request: Link to visit templates from Admin Site Templates Screen.

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#435]
Hi Everyone,

I was playing with new site templates last week, and one of the usability things that I found was there wasn't an easy way to actually get to a template if you were editing them.

We have the nice admin screen at /wp-admin/edit.php?post_type=cboxol_site_template

<img width="999" alt="Screenshot 2023-04-05 at 8 14 07 AM" src="https://user-images.githubusercontent.com/29982981/230077042-30d67ace-2f0a-47bb-a74a-8bab9f4ff6ac.png">
While you can see your templates, and modify the about information or the featured image, there is no link to actually go to the template so you can modify it.

Same from any of the template edit screens- 
<img width="1021" alt="Screenshot 2023-04-05 at 8 15 57 AM" src="https://user-images.githubusercontent.com/29982981/230077504-cf0a9e42-6a1d-4972-87ef-a8bc572113ea.png">
Even from here, you can't get to your site to edit it.

It would be nice to have a "View" link so that you could visit a specific template.

**Comment by boonebgorges** [comment]
Thanks for the suggestion. We'll add something.

**Comment by boonebgorges** [comment]
I'm going to add a line in the 'Template Site' metabox, which will have View and Dashboard links:

![Screenshot_2023-06-02_12-40-31](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/b832b973-1bd9-4f4f-9bce-d7064c01102c)

**Comment by bree-z** [comment]
This looks good, thanks!
