### ISSUE TITLE
Change privacy status text for hidden groups

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#438]
From http://redmine.citytech.cuny.edu/issues/3074:

> We'd like to change the privacy status text for hidden groups that appears on a group's profile. Currently, if a group is hidden, the text says: "This [Group] is PRIVATE."
>
> Could we change this to: "This [Group] is HIDDEN."

https://github.com/openlab-at-city-tech/openlab/commit/956f2ded64355e7afcae955928aee5ccd897dccf

**Comment by boonebgorges** [comment]
I've made the change. But recall that, unlike on the City Tech OpenLab, these strings are at the time of installation and saved to the database. This is what makes it possible to translate and also to customize for different group type names. As such, making the change in https://github.com/cuny-academic-commons/cbox-openlab-core/commit/140f1ee8f47bb0e462e500158dcd4a16529ea933 won't affect existing installations. You will be able to test only by running a fresh installation.

**Comment by bree-z** [comment]
Thanks Boone. I'll see if I can test on a fresh install after the release.
