### ISSUE TITLE
Port External Files feature from OpenLab

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#440]
See http://redmine.citytech.cuny.edu/issues/3053

**Comment by boonebgorges** [comment]
This has been ported and is ready to test on openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
Hi Boone, 

There are a few issues on the page when there are no files yet added to the group. Can we also make two text changes, to match the CT OL? Please also see the screenshots below.

1. Text changes:
a. Change "There are no files to view." to "No files have been added yet. Add a new file below."
b. Change button text "Upload a New Document" to "Add new file"
2. The 'Add New File' section should only appear after users click 'Add new file'.
3. The sidebar appears at the bottom of the page. Once I've added a new file, it appears in the correct place again. 

Thanks!

![FileLibrary_NoFiles](https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/0cbad829-11d8-4853-b07f-d8dcc90b4729)

CT OL: 

<img width="1237" alt="FileLibrary_NoFiles_CTOL" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/7e2b2e91-6a8e-4c68-a707-92b93ca76f0b">

**Comment by boonebgorges** [comment]
Changes are ready to test.

**Comment by bree-z** [comment]
Thanks Boone! These changes all look good.
