### ISSUE TITLE
Rename 'Files' to 'File Library'

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#441]
In conjunction with #440 

See http://redmine.citytech.cuny.edu/issues/3057, https://github.com/openlab-at-city-tech/openlab/commit/bc5d1da8e801664221874e8ac8afed21af2e018a, https://github.com/openlab-at-city-tech/openlab/commit/9d8598994d9963e7e451d40f1919d396f1352ae2

**Comment by bree-z** [comment]
This looks good, thanks!
