### ISSUE TITLE
Port 'Recent Comments' link behavior changes from OpenLab

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#442]
From http://redmine.citytech.cuny.edu/issues/3042:

> In the Group Profile, the link to view a recent comment, post, discussion, etc is not obvious (to be addressed in another ticket), but navigating to a recent comment doesn't seem to work at all.
> 
> When you click on See More... it takes you to the top of the post, not the comment. Is this a bug or expected functionality? I believe a user would expect to navigate to the comment, not the top of the post.
> 
> Also, should the post title appear above the recent comment listed, indicating which post the comment is in response to?

See https://github.com/openlab-at-city-tech/openlab/commit/be6e5a972b32584617213ae8310cdb59ec8be846, https://github.com/openlab-at-city-tech/openlab/commit/e4516066edfb7bd2210938963ab7492c3f52e30c

**Comment by bree-z** [comment]
This looks good, thanks!
