### ISSUE TITLE
Port from City Tech OpenLab: Add 'Add to Portfolio' in Portfolio Creation

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#449]
From http://redmine.citytech.cuny.edu/issues/3204, we'd like to add the 'Add to Portfolio' settings to Portfolio creation. The other changes in the ticket are specific to City Tech.

Does the placement make a difference on your end? If not, let's add to the bottom of the second step, with the site settings.

Thanks!

**Comment by boonebgorges** [comment]
This should now be ready to test.
