### ISSUE TITLE
Template Chooser > Site templates don't appear during course and creation

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#450]
Hi Boone, 

The template chooser doesn't appear during course or portfolio creation. It does appear during project and club creation. 

In the template chooser dashboard interface I see that there are four templates for courses, in three different categories. For portfolios there are two templates in two categories.

If I go to course settings of an existing course, unlink it from the site, and then create a new site I see the template chooser with all the available templates.

If I do the same for portfolios, I don't see the template chooser.

Thanks!

**Comment by boonebgorges** [comment]
I think this is linked to changes in #447, which changed the logic determining when the panel should show.

I've made a change in 5f45a61b4f5d2b6eb3e07b04085f3d1781bcc55a that seems to fix the issue in my testing.

**Comment by bree-z** [comment]
Thanks Boone! The template chooser panel now appears during course and portfolio creation. It's also still there during project and club creation. 

However, for projects and clubs that don't include an associated site by default, the panel appears before before I click 'Set up a Site'. Previously it would appear after clicking 'Set up a Site'. The same happens for groups that don't have an associated site when I go to Group Settings > Site.

**Comment by boonebgorges** [comment]
Thanks for pointing this out. It should now be fixed.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.

**Comment by bree-z** [comment]
Hi Boone, 

I'm not sure if I missed this earlier or if it's something new, but I'm not seeing the template chooser panel during portfolio creation, or in settings.

There were two templates associated with portfolios when I noticed this. I added a third, but still didn't see the panel. 

Thanks!

**Comment by boonebgorges** [comment]
There was a problem in my last change that caused the picker not to appear properly for group types where associated sites are required. This should now be fixed.

**Comment by bree-z** [comment]
This looks good, thanks!

I see it on all group types at creation and in settings, if I unlink the site.
