### ISSUE TITLE
Search combining Department with Category returns results in all Depts

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#452]
Hi Boone, 

I'm not sure if this is a new issue. I tried to compare with BMCC, but had a hard time reproducing a similar search.

In the Courses directory, when I combine School/Dept with a category, e.g. [Engineering + Mechanical Engineering + Writing Intensive](https://openlabdev.commonsinabox.org/groups/type/course/?search=&academic-unit-schools=engineering-2&academic-unit-departments=engineering&cat=writing-intensive&term=&sort=active#), I get courses with the 'Writing Intensive' category, but in all departments. 

Thanks!

**Comment by boonebgorges** [comment]
No, I don't think it's new. The problem is that the internals responsible for the 'category' filter was overwriting the 'academic unit' filter. I've changed the order in which they're applied so that the 'category' filter runs first.

**Comment by boonebgorges** [comment]
I should note that results on https://openlabdev.commonsinabox.org/groups/type/course/?search=&academic-unit-schools=engineering-2&academic-unit-departments=&cat=&term=&sort=active# are still a bit odd. There appear to be a few different 'Engineering' academic units, some of which are legacy and/or orphaned. So the filtered view doesn't appear to show everything you'd expect. But I think that this is an artifact of the old data on openlabdev.commonsinabox.org, not a bug.

**Comment by bree-z** [comment]
This looks good, thanks!
