### ISSUE TITLE
PressForward plugin isn't updated to latest version

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#453]
Hi Boone, 

I'm not sure if this is just the setup of the dev site, but the version of the PressForward plugin available for activation on subsites is 5.2.10 rather than 5.5.0. 

If I go to Dashboard > Plugins > Member Site Plugins, I don't see that there's an available update. 

Thanks!

<img width="1152" alt="Screenshot 2023-07-28 at 10 19 27 AM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/f15ab03e-2a56-4982-9e78-0cac93e326ef">

**Comment by boonebgorges** [comment]
Yes, this is specific to openlabdev.commonsinabox.org. I've fixed it.

**Comment by bree-z** [comment]
Thanks Boone!
