### ISSUE TITLE
OpenLab Mobile Menus overflow container

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#454]
On OpenLab, the mobile menu texts overflow the background container. I've confirmed on a site running the latest version of OpenLab and also cboxopenlab.org

Here's a screenshot of cboxopenlab.org

![IMG_2145](https://github.com/cuny-academic-commons/openlab-theme/assets/29982981/bf3d4703-1acd-4c8b-8552-e2eeccf94762)

I think the cause is an !important rule that sets the width at 101%

@media (max-width: 767px)
.oplb-bs #wpadminbar #wp-toolbar .ab-sub-wrapper {
    background: transparent;
    left: -1%;
    right: 0;
    top: 1px;
    **width: 101% !important;**
    border: none;
    border-radius: 0;
    margin: 0;

When we remove that rule, or set it to 200%, it looks better.

<img width="884" alt="Screenshot 2023-08-16 at 7 47 16 AM" src="https://github.com/cuny-academic-commons/openlab-theme/assets/29982981/8a51ca60-2b40-40c0-aca1-a2e78f98a43d">

**Comment by bree-z** [comment]
This looks good to me, thanks!
