### ISSUE TITLE
New sites created with incorrect menu items

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#462]
Hi Boone, 

This is probably for a later release, but I was able to reproduce one of the menu issues I noticed on my own test site:

* I created a new template, [Dec 23 New Template](https://openlabdev.commonsinabox.org/site-template-dec-23-new-template-1702894203). 
* I changed the theme from Twenty Twenty Three to Twenty Seventeen.
* I created a [new course site](https://openlabdev.commonsinabox.org/more-course-template-testing-2/) using the new template.
* Instead of having '[Course Home]' in the menu, site has a menu item called 'Group Home' which links to: https://openlabdev.commonsinabox.org/site-template-dec-23-new-template-1702894203/group-profile. The 'Home' link also links to the template: https://openlabdev.commonsinabox.org/site-template-dec-23-new-template-1702894203/
<img width="1296" alt="Screen Shot 2023-12-18 at 5 40 51 AM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/069899de-2172-4cab-ad5d-643cb901c257">

At first I thought it was just an issue with newly created templates, but I got the same issue when I created new group sites using a few existing templates, e.g.:
* I created [this club](https://openlabdev.commonsinabox.org/more-club-template-testing/) using the existing template [SGA Clubs](https://openlabdev.commonsinabox.org/site-template-sga-clubs-1660057404/).
* https://openlabdev.commonsinabox.org/more-project-template-testing-3/ creating using the [Department Site Template](https://openlabdev.commonsinabox.org/site-template-project-site-template-3-1672324197/).

Thanks!

**Comment by boonebgorges** [comment]
It's possible that this is being caused by a small change I'd put in place while we were working on #459. As we decided to "do nothing" on that ticket, I've reverted that small change. Perhaps you could try again to see if this reverted commit fixes the behavior you've described here. If not, we'll have to handle in a future release.

**Comment by bree-z** [comment]
Thanks Boone. I still see the same behavior.

**Comment by boonebgorges** [comment]
Sounds good. We'll review this in the future.

**Comment by boonebgorges** [comment]
I finally got around to looking at this. The specific issue is that Twenty Seventeen doesn't have a nav location called 'primary', which meant that the swap-outs during template copying were not working properly.

To accommodate themes that may use different naming conventions for nav locations, I introduced a heuristic that tries to determine the "primary" location, and then uses that when generating sites from templates. This works well for the themes I've tested. There will likely be themes that don't conform, but I think that my change will cover the default WP themes as well as many other popular ones.

**Comment by bree-z** [comment]
Thanks Boone!

I think this looks good. To test, I created a new template, changed the theme, then created a new site and checked the menus. I tested with Twenty Seventeen, Twenty Sixteen, Neve, and Astra. I'd already had one with Hemingway, and those site menus were fine.
