### ISSUE TITLE
Remove default group name when creating portfolio

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#465]
Currently, when you create a portfolio, the 'Name' field is pre-filled with '[Display Name]'s Portfolio'. To underscore the possibility of pseudonymity and encourage user privacy, we will leave it blank instead.

The "helper" text reads:

![Screenshot_2024-02-06_19-29-14](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/d78de38a-792e-4014-80f2-d352b7339df8)

This will need to be updated, since there will no longer be any 'suggested' text. Here's a proposal for the new text:

```
Choose a name for your Portfolio. You may use your name ("Jane Smith's Portfolio"), or any descriptive title you'd like.
```

**Comment by boonebgorges** [comment]
This is ready to test. I've updated the language as suggested above. This requires an upgrade routine, since the text 'The suggested Portfolio name...' is saved to the database on installation. In some cases, an admin may have changed this language, and we'll be overwriting it, but I think this is necessary because the 'suggested' text no longer makes any sense.

**Comment by bree-z** [comment]
Thanks Boone! The group profile part looks good. We may want to adjust the helper text, but we'll discuss. 

However, in the second step, the site URL isn't pre-populated with the Portfolio Name. It seems to use the display name. In the screenshot below, the Portfolio Name is Student Portfolio Testing (https://openlabdev.commonsinabox.org/groups/student-portfolio-testing/)

<img width="913" alt="Screen Shot 2024-05-29 at 5 28 17 AM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/1258eca8-1566-4d4c-8671-2e1ad19f9016">

**Comment by boonebgorges** [comment]
I've made a change so that the 'Associated Site Details' suggested URL is handled in the same way as other group types, ie by using the group slug.

**Comment by bree-z** [comment]
This looks good, thanks!
