### ISSUE TITLE
"More visibility options" for site posts

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#466]
See http://redmine.citytech.cuny.edu/issues/3281

The City Tech OpenLab has built a feature that adds a 'More visibility options' to the block editor. This feature allows a specific post on a public site to be limited to group members only, or to network members only. Here's what it looks like on that site:

![Screenshot_2024-02-06_19-36-50](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/09ae1839-50c0-4d02-8d99-f12a8d751ab6)

We should add this to CBOX OpenLab. The language will likely need small changes:
- The screenshot says "Only logged-in members of this Course can see this post. This will override the Public visibility setting above.". It's difficult to build a sentence like this with variable group-type names and between languages. So instead we'll need something like "Only logged-in members of this site can see this post...". On CBOX OpenLab, site and group membership is linked.
- Instead of "Only logged-in OpenLab members can see this post", better to say "Only logged-in members of the network can see this post", or simply "Only logged-in users can see this post".

**Comment by boonebgorges** [comment]
This is mostly ported over. The missing piece is the blocking that happens in the activity stream. On the City Tech OpenLab, this piggy-backs on how activity-stream blocking works for private group memberships. So I'll wrap this ticket when I've ported #469.

**Comment by bree-z** [comment]
We would also like to include functionality added in http://redmine.citytech.cuny.edu/issues/3382:

* The 'More visibility options' section of the block editor ([#3281](http://redmine.citytech.cuny.edu/issues/3281)) should appear on sites with visibility "Visible only to registered users of this network" (value 1; it currently appears only for values 0 and 1)
* The 'Everyone' option should not be available on sites with blog_public=-1
* 'OL members only' should be the default for new posts, again only on those sites with blog_public=-1

Thanks!

**Comment by boonebgorges** [comment]
This is ready to test.

**Comment by bree-z** [comment]
Thanks Boone!

> The screenshot says "Only logged-in members of this Course can see this post. This will override the Public visibility setting above.". It's difficult to build a sentence like this with variable group-type names and between languages. So instead we'll need something like "Only logged-in members of this site can see this post...". On CBOX OpenLab, site and group membership is linked.

This sounds good.

> Instead of "Only logged-in OpenLab members can see this post", better to say "Only logged-in members of the network can see this post", or simply "Only logged-in users can see this post".

We'd like the text to be: "Only logged-in members of the community can see this post."

For sites set to "Visible only to registered users of this network", could we change the text for the the second radio button:

**Logged-in community members only**
Only logged-in members of the community can see this post. 

Posts are visible or not, as expected, depending on privacy settings. 

But comments are visible in a few places:

- Public site: Comments on posts visible to site members only and logged-in OpenLab members only are visible to non-logged in users on the group Home, under Recent Comments. E.g.: https://unwavering-vole-0e3fea.instawp.xyz/groups/tf-course-2/
- Site visible only to registered users of this network: Comments on posts visible to site members only are visible to logged in OpenLab members who are not group members on the group Home, under Recent Comments.  E.g.: https://unwavering-vole-0e3fea.instawp.xyz/groups/tf-project-1/ where comments in this post are visible: https://unwavering-vole-0e3fea.instawp.xyz/tf-project-1/2024/07/16/site-members/#comment-4

**Comment by boonebgorges** [comment]
I've made the text change, and I've pushed up a change that should address the 'Recent Comments' section on the group home.

**Comment by bree-z** [comment]
Thanks Boone. This looks good!

Can we make one more change to the radio button text for "Logged-in community members only" to: "Community members only"?

Thanks!

<img width="308" alt="Screenshot 2024-07-17 at 7 24 27 PM" src="https://github.com/user-attachments/assets/e3157667-6d1b-4b1d-bfbd-7bfd9a3ffe86">

**Comment by boonebgorges** [comment]
I've made the change.

**Comment by bree-z** [comment]
This looks good, thanks!
