### ISSUE TITLE
"Hidden" group memberships

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#469]
See http://redmine.citytech.cuny.edu/issues/3055, http://redmine.citytech.cuny.edu/issues/3062

The City Tech OpenLab has a new feature that allows group members to "hide" their memberships. 

![Screenshot_2024-02-06_19-58-49](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/ca73c824-952c-4fd5-8417-cb8d0c2a0639)

When a membership is hidden, the following changes take place:
1. The member is not shown in the group's Members list (except when you're a site admin, or a member of the group)
2. The group is not shown in the user's My Groups listings (except when viewing your own profile)
3. The member's activity in the group is marked `hide_sitewide`, which means it's only visible to admins and group members.

Let's port this to CBOX OpenLab.

**Comment by bree-z** [comment]
Hi Boone, I'd started testing this on openlabdev.commonsinabox.org but stopped. I did enough initial testing to see that  checking the 'Hide my membership' checkbox resulted in the membership being hidden. 

I've started testing again in the new environment and while I'm able to check the 'Hide my membership' checkbox, if I navigate away from the page or reload, the state of the checkbox is reset to unchecked. It doesn't seem to be a browser issue.

![HideMembership](https://github.com/user-attachments/assets/139e7152-4ff1-430b-8858-1b51757ebc7d)

**Comment by boonebgorges** [comment]
You have to run through the CBOX upgrade routine that adds the database table. See Dashboard > CBOX OpenLab > Upgrades.

**Comment by bree-z** [comment]
Ah, got it, thanks!

**Comment by bree-z** [comment]
I missed that [3062](http://redmine.citytech.cuny.edu/issues/3062) wasn't part of this ticket. This is where in Group > Membership, non-admin view, we changed the text "joined X time ago" to "joined Month, day, year" so that the 'Hide my membership' checkbox wasn't pushed down below the border of the card. Is this something we can still do?

There are just a few other issues: 

- In the Portfolio List tool, portfolios of hidden members are visible to other group members (but not to non-members)
- Hidden member activity in Docs appears in the content boxes on the group home for non-admins. Other types of content are hidden. 
- When viewing the member count as an admin, it doesn't include hidden members. 
- Screenshots below are from https://unwavering-vole-0e3fea.instawp.xyz/groups/tf-project-1/ where teststaff's membership is hidden.

Thanks!

**Portfolios List**

<img width="1235" alt="MemberPortfoliosNotHidden" src="https://github.com/user-attachments/assets/2d0c8959-5dfd-40c7-ad3d-9668f29557e5">



**Docs**

<img width="1261" alt="DocsNotHidden" src="https://github.com/user-attachments/assets/b8c5469c-3b84-476b-9965-415f3ca789bb">



**Admin Member Count**

<img width="1236" alt="AdminMemberCount" src="https://github.com/user-attachments/assets/6ed0d3f5-a4dd-47cc-a823-f6ed30e35125">

**Comment by boonebgorges** [comment]
> I missed that [3062](http://redmine.citytech.cuny.edu/issues/3062) wasn't part of this ticket. This is where in Group > Membership, non-admin view, we changed the text "joined X time ago" to "joined Month, day, year" so that the 'Hide my membership' checkbox wasn't pushed down below the border of the card. Is this something we can still do?

I've made the change.

> In the Portfolio List tool, portfolios of hidden members are visible to other group members (but not to non-members)

That's how it works on the City Tech OpenLab. See redmine.citytech.cuny.edu/issues/3055#note-36, https://github.com/openlab-at-city-tech/openlab/commit/681687d1da78084e32672f850922ffdab2dbedf1 Elsewhere in the interface, "hidden membership" always means "hide my membership from non-group-members"


> Hidden member activity in Docs appears in the content boxes on the group home for non-admins. Other types of content are hidden.

I've made a change so that Docs created by members whose group membership is public appear only to members (as opposed to admins - see above).

> When viewing the member count as an admin, it doesn't include hidden members.

I've made a change so that the count is sensitive to whether you're an admin.

I have a feeling that there may be some future wrangling over the intended consequences of hidden-membership; here and elsewhere, I've defined it as visible-to-other-group-members, but you've suggested a number of times that it should be limited to admins. To prepare for this wrangling, I've removed hardcoded permission checks in favor of a custom capability 'view_private_members_of_group'. This way, if you decide you want it to work differently, I only need to make the change in one place.

**Comment by bree-z** [comment]
Thanks Boone!

The changes look good.

The membership count is now correct for admins and members, but not non-members. For non-members the count is one less than it should be -- see screenshot below from https://unwavering-vole-0e3fea.instawp.xyz/groups/faculty-test-course-1/members/ where there are four visible members but the member count is three.

> I have a feeling that there may be some future wrangling over the intended consequences of hidden-membership; here and elsewhere, I've defined it as visible-to-other-group-members, but you've suggested a number of times that it should be limited to admins. To prepare for this wrangling, I've removed hardcoded permission checks in favor of a custom capability 'view_private_members_of_group'. This way, if you decide you want it to work differently, I only need to make the change in one place.

I was actually unsure about limiting visibility to admins but not group members. Looking back at [3055](http://redmine.citytech.cuny.edu/issues/3055), it looks like this was how we built it (and current functionality on openlabdev.org), but Charlie and I couldn't remember why. In any case, you're correct that we may want to change this at some point. Thanks!

Member count, non-member view:

<img width="1249" alt="Screenshot 2024-07-16 at 12 30 45 PM" src="https://github.com/user-attachments/assets/dda41a2f-34d0-4dd5-9599-48d368b89d1b">

**Comment by boonebgorges** [comment]
You found a bug where a user joins a group, marks membership private, then leaves the group; later, when calculating the member count for display in the menu, that defunct group membership is mistakenly included in the number of private members. I've fixed this.

**Comment by bree-z** [comment]
This looks good, thanks!
