### ISSUE TITLE
Allow admins to determine order for site templates

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#471]
After some discussion with the City Tech team, we think the most obvious place to do this by making the elements on Dashboard > Site Templates sortable via drag-and-drop.

**Comment by boonebgorges** [comment]
I've built a version of this. I wanted to avoid using a secondary plugin for drag-and-drop: too much overhead, too many features, too much potential for breakage. So I built my own drag-and-drop implementation. It's not extremely polished, but I added a few little transition effects that I think make it usable. See gif:

![Peek 2024-05-02 14-57](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/1453f988-bae6-4580-bb5a-f6b30bc6bfbf)

**Comment by bree-z** [comment]
Thanks Boone! Drag-and-drop looks good, and the order that templates appear on the front end are changed based on the order determined in the Dashboard. 

There's just one minor quirk I've found. Sometimes after I drag a template, the title of the template remains light blue. I can't reliably reproduce it, and it goes away after I reload the page.

<img width="412" alt="Screen Shot 2024-05-29 at 4 12 40 AM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/f6f75a0f-01e6-415f-b92d-be71be34b8ce">

**Comment by boonebgorges** [comment]
The light-blue issue appears to happen when you grab by the link text rather than elsewhere in the row. I've just pushed up a fix.

**Comment by bree-z** [comment]
Thanks Boone. Currently, I'm not able to grab the title or any other part of an element. I tested using Chrome and Firefox.

![2024-06-18_14-33-28 (1)](https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/f7c76c57-9957-4fea-ad1b-e70fecd3048d)

**Comment by boonebgorges** [comment]
This was caused by some interference caused by #472. It should now be fixed.

**Comment by bree-z** [comment]
This looks good, thanks!
