### ISSUE TITLE
Allow site templates to be limited based on member type, academic unit of associated group

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#472]
See http://redmine.citytech.cuny.edu/issues/3247 for internal discussion.

**Comment by boonebgorges** [comment]
I've built a first pass at the functionality for member type. 

I've added a new 'Template Visibility' metabox when editing a template:

![Screenshot_2024-05-02_20-19-45](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/40c93fec-acb6-4681-90d9-ef7685686d53)

There's some interactivity when toggling between the radio buttons:

![Peek 2024-05-02 20-20](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/0e1e804a-0636-4cdb-b9df-1fa437f127ab)

I played with a couple different ways of phrasing the setting - "visibility", "access", positive vs negative, etc - and settled on what you see here. Happy to consider a different way of thinking about it.

I've also added a 'Visibility' column when viewing the list of templates:

![Screenshot_2024-05-02_20-19-18](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/7cebe023-c16b-4230-aa97-fd3a3637576c)

I think we may want to add some dropdown filters to Dashboard > Site Templates for improved findability and navigation, though I haven't done this yet.

None of this is running on openlabdev.commonsinabox.org yet, as I wanted to get feedback from the team before merging into our main branch.

Academic unit integration will use a similar interface, though the checkbox layout will be more complex; see the City Tech ticket for more details.

**Comment by bree-z** [comment]
This looks great, thanks!

I think it makes sense to move ahead unless @jennaspevack and @charliemedwards have any additional thoughts.

**Comment by boonebgorges** [comment]
Thanks for the feedback. I've expanded the feature to academic types:

![Screenshot_2024-05-13_21-19-12](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/d4750f97-f207-4e43-ada6-bd6ccc3acbdc)

Here's a gif of how the scrollable box works, as well as the dynamic interlinked checkboxes:

![Peek 2024-05-13 21-19](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/e50b1860-3a0c-410c-99c8-e309142ba279)

I've also added 'Academic Units' to the new Visibility column:

![Screenshot_2024-05-13_21-18-56](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/7cdbc8ea-8765-48a0-ac9e-151aafc987dc)

Because you can connect to a lot of academic units, this list could get quite long. Not sure how/if we want to handle this.

I'll work in the upcoming days on filters for Dashboard > Site Templates.

**Comment by boonebgorges** [comment]
I did some thinking about dropdown filters, and I don't think we should implement them at this time.

There are some conceptual and semantic issue with introducing dropdown filters in this context:

- It's confusing how they will work together. From a technical point of view, they combine with each other, so if you select A from 'Academic Units' and B from 'Member Type', it'll show you only those items that meet *both* A and B. This is OK for some cases (drilling down) but not for others (birds-eye-view filtering).
- The options for each "visibility" setting, as I've designed them, are two-tiered: There's an on/off toggle. And then, if you select "on", you are presented with some checkboxes. There's no easy way to represent this in a dropdown.
- Related: Let's say you've set the Member Type setting for template A to 'Allow for all member types'. Then, you have a dropdown that has different member types, eg 'Faculty'. When you select 'Faculty', it will obviously show items where you've explicitly selected Faculty as one of the allowed member types. But should it also show A? Probably yes, but this is technically hard, and what if you *don't* want to see A?
- Academic Units are nested in child-parent relationships, which is hard to represent in a dropdown.
- The Visibility settings allow multiple selections. So a template can be associated with, say, member types 'Faculty' and 'Staff'. This is hard to reproduce in a dropdown. We could use a multiselect, or a library like Select2. But this is a departure from the conventions of these dropdowns as they're used by WordPress. It also introduces more of the confusion discussed above with filter combinations: will filtering by 'Faculty' + 'Staff' show you only those templates that are linked to *both* F + S, or *either* F + S? The most straightforward logic technically is "either", but this is difficult to show to the user.
- The presence of the Visibility column means that people can do their own visual "filtering" by simply scanning the list. This makes it less urgent that we introduce any sort of technical filters. This is especially true because it's unlikely in most cases that a site will have the many pages' worth of templates that would necessitate filters.

So, I think the case is pretty compelling for *not* doing any sort of dropdown filters. We can always revisit in the future if we get complaints.

**Comment by bree-z** [comment]
Thanks Boone!

Agreed that your case for not implementing dropdown filters is compelling. 

This looks good so far in my testing. I'm seeing the correct templates based on the various user type and academic unit restrictions I've set up.  Just a few things:

### Dashboard

**Create new template > Template Visibility section**

*By Member Type*

Restricting by member type doesn't make much sense for courses, and I guess the same could apply to other group types, depending on the installation. Does it make more sense to hide this option if only one member type has permissions to create a particular group type?

Or, when 'Restrict by member type' is selected, only show checkboxes for member types with permission to create that group type?

*By Academic Unit*

Can we change the heading to "Schools and Departments"? I know this can vary depending on how academic units are set up, but if there are parents and children, seems like those should be included.

### Front end

When creating a group where I've set limits on template visibility for academic units, there are previous/next buttons that appear at the bottom of the template chooser panel.

<img width="893" alt="Screen Shot 2024-05-28 at 5 48 29 AM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/87acf021-6224-4909-8dac-5ce33f986809">

**Comment by boonebgorges** [comment]
> Or, when 'Restrict by member type' is selected, only show checkboxes for member types with permission to create that group type?

This ended up being extremely complicated. See 6608dce. Here are some considerations:
-  This is only relevant for the "course" group type. Internally, one and only one group has the "is_course" group flag (regardless of what you call it). 
- By extension, we only control group membership creation by member type in the case of courses - there's an internal `can_create_courses` flag.
- So, this consideration is only relevant when looking at templates that are associated with courses.
- Moreover, it's only relevant when looking at templates that are *only* associated with courses, since if a template can be associated with (say) a Club, the creation of which is not restricted by member type, then the 'By Member Type' restriction *does* make sense.
- What it means for a template to be "associated with courses" is that it belongs to one or more categories that are associated with the "course" group type.
- This category association can be changed while looking at the template edit panel, which means that this hiding needs to be dynamic.
- This all needs to be compatible with internationalization and customizable group/member type names.

So the method I settled on is: When I detect that the currently edited template is associated only with categories that are associated only with the course group type, I disable the checkboxes associated with member types that do not have the `can_create_courses` flag. I also add a little message that explains why some of these checkboxes have been disabled. IMO this is less opaque than simply hiding the box altogether. This is obviously quite hard to explain, so here's a gif:

![Peek 2024-05-29 20-58](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/2474b3e4-8b83-41b9-9b08-1d5506d06457)

> Can we change the heading to "Schools and Departments"? I know this can vary depending on how academic units are set up, but if there are parents and children, seems like those should be included.

I'm going to decline to do this at the moment. It's complicated because academic unit types can be nested arbitrarily, so that you can have, say, Schools > Departments > Subdepartments, Schools > Departments > Specializations, Schools > Programs > Subprograms, etc. I would have to build a tool that walks through the tree and builds some sort of string that makes sense in all cases (and across all languages). This is very hard, for what I see as a limited benefit. Maybe this is something we can circle back around on in the future if it seems important to the users and to the team.

> When creating a group where I've set limits on template visibility for academic units, there are previous/next buttons that appear at the bottom of the template chooser panel.

Pagination appears when there's more than 6 items to show. Were there, in fact, more than 6 available templates? I briefly tried to recreate on openlabdev.commonsinabox.org, but I didn't see it, so I'm probably not testing with the right combination of member type + group type.

**Comment by bree-z** [comment]
Thanks Boone.

> When I detect that the currently edited template is associated only with categories that are associated only with the course group type, I disable the checkboxes associated with member types that do not have the can_create_courses flag. I also add a little message that explains why some of these checkboxes have been disabled. IMO this is less opaque than simply hiding the box altogether.

This looks good, thanks! 

> I'm going to decline to do this at the moment. It's complicated because academic unit types can be nested arbitrarily, so that you can have, say, Schools > Departments > Subdepartments, Schools > Departments > Specializations, Schools > Programs > Subprograms, etc. I would have to build a tool that walks through the tree and builds some sort of string that makes sense in all cases (and across all languages). This is very hard, for what I see as a limited benefit. Maybe this is something we can circle back around on in the future if it seems important to the users and to the team.

Totally understood. 

> Pagination appears when there's more than 6 items to show. Were there, in fact, more than 6 available templates? I briefly tried to recreate on openlabdev.commonsinabox.org, but I didn't see it, so I'm probably not testing with the right combination of member type + group type.

Ah, this was my mistake - there were more than 6 items to show. When there are 6 or fewer the buttons don't appear.

I found one additional issue:

I created a [portfolio](https://openlabdev.commonsinabox.org/staff-portfolio-123) as the staff user [breestaff](https://openlabdev.commonsinabox.org/members/breestaff/) in the academic units Arts & Sciences > Economics. I didn't see any available templates, which seems correct, but based on the [current template configurations](https://openlabdev.commonsinabox.org/wp-admin/edit.php?post_type=cboxol_site_template), I think the portfolio site was created with the wrong template. It looks like it used was [Site Template - Student Portfolios 1](https://openlabdev.commonsinabox.org/wp-admin/post.php?post=69165&action=edit), which is restricted to students, but should have used [Faculty and Staff Professional Portfolio 5 May 2024](https://openlabdev.commonsinabox.org/wp-admin/post.php?post=69810&action=edit) because it's the only portfolio template available for a staff user creating a portfolio in any discipline. The [other template for staff users](https://openlabdev.commonsinabox.org/wp-admin/post.php?post=69826&action=edit) is restricted to Nursing.  

In case it's relevant, the [Site Template - Student Portfolios 1](https://openlabdev.commonsinabox.org/wp-admin/post.php?post=69165&action=edit) template that was used is set as the default template in Group Settings > Portfolios.

I created [another portfolio](https://openlabdev.commonsinabox.org/groups/staff-nursing-portfolio/) with the staff user [kermitgreen](https://openlabdev.commonsinabox.org/members/kermitgreen/) in Professional Studies > Nursing. For this one I did see the correct two templates ([Staff Nursing](https://openlabdev.commonsinabox.org/wp-admin/post.php?post=69826&action=edit) (for staff users in Nursing) and [Faculty and Staff Professional Portfolio 5 May 2024](https://openlabdev.commonsinabox.org/wp-admin/post.php?post=69810&action=edit) (for faculty and staff users in any academic unit)). My choice was applied correctly.

I also created a student portfolio in Math, where [Site Template - Student Portfolios 1](https://openlabdev.commonsinabox.org/wp-admin/post.php?post=69165&action=edit) was the only template for that user type/academic unit configuration, and the [site created](https://openlabdev.commonsinabox.org/student-math-pf/) was using the correct template.

**Comment by boonebgorges** [comment]
> In case it's relevant, the [Site Template - Student Portfolios 1](https://openlabdev.commonsinabox.org/wp-admin/post.php?post=69165&action=edit) template that was used is set as the default template in Group Settings > Portfolios.

I think this is the reason why. There has to be *something* used as a fallback when the user doesn't select something. The fact that the admin (in this case, you) has selected a fallback option that is not selectable by Staff isn't taken into account. The logic of site templates is currently handled in separate places, and in certain cases it's possible to configure them in such a way that you get unexpected results. I don't have a clear sense of how to change this. But I also think it's not a super important point, since in most cases the administrator will use a very general template as the group-type fallback.

**Comment by bree-z** [comment]
Thanks Boone. I see what you mean. We've done some more testing of this and I think it's ready to port to the City Tech OpenLab.

**Comment by bree-z** [comment]
I think we've done enough testing that we can close this.
