### ISSUE TITLE
BP "nav" functions should be more easily extended

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#473]
Currently, we have functions like `openlab_group_membership_tabs()`, which certain BP subnavs. These functions are then called across multiple single-group templates. This makes it hard to customize or extend the nav items: you can fork `openlab_group_membership_tabs()`, but then you have to override each of the functions that call the tabs.

Let's make this easier. In an ideal world, we'd use BP functions to register and spit out nav menus in a proper way. This would require a pretty extensive rewrite. But we can make the more modest improvement of moving the markup into a template file. Maybe something like this:

1. Move the guts of `openlab_group_membership_tabs()` into a file `openlab-theme/buddypress/groups/single/tabs-membership.php`
2. In `openlab_group_membership_tabs()`, use `bp_get_template_part()` to load the new template
3. Do something similar for other similar functions

It'd be more transparent to call `bp_get_template_part()` directly from the template files, but this would require changes across lots of theme templates, which increases the chances that the change won't be picked up by custom child themes. The approach sketched above should be 100% backward-compatible.

**Comment by boonebgorges** [comment]
I've made the suggested changes.

@bree-z The only thing to test here is that subnav links are looking OK in various parts of the single group UI. This means:

- under Membership ('Membership', 'Invite New Members', etc)
- under Discussion ('Discussion', topic name)
- under Settings ('Course Details', etc)
- under Docs ('View Docs', 'New Doc')

**Comment by bree-z** [comment]
Thanks Boone! This looks good for Membership, Discussion, Settings, Docs, and File Library. 

I'm not sure if Calendar is part of this ticket, but I see an issue where when I click on 'Manage' in the subnav, the subnav links change from the Calendar to the subnav for Settings (Course Details, etc).

<img width="1217" alt="Screenshot 2024-07-12 at 1 06 54 PM" src="https://github.com/user-attachments/assets/fac36ca6-4826-4033-b21a-b9ea0780c304">

**Comment by boonebgorges** [comment]
The behavior you describe is not related to this ticket.

I'm also not sure it's straightforwardly a bug. The Manage link goes to /groups/[groupname]/admin/events, which is under the Settings tab. So showing the 'Settings' subnav seems correct. The issue, perhaps, is the OpenLab has a highly customized way of showing group settings, while what you're seeing on Calendar > Manage is the default BP behavior of each plugin having it's own /admin/ panel.

The only viable short-term fix, if you think it's important enough to pursue at the moment, is to remove the link altogether. For context, it's not visible on the City Tech OpenLab (though it's not immediately clear why).

**Comment by bree-z** [comment]
Thanks, Boone! I think we can leave this as is.
