### ISSUE TITLE
Clone process cannot complete when group File Library is non-empty

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#474]
The External Link feature added in #440 includes a post-save callback that involves a nonce check. However, this callback is also called during clone operations (and presumably other document-save routines outside the regular user interface). Because the nonce fields are not present in those non-UI situations, the nonce check necessarily fails, and the group clone process dies.

**Comment by bree-z** [comment]
Hi Boone, 

I added items to the File Library of a course (an external link and an uploaded file) and cloned the course successfully. I did the same with a project.

If I was testing for the correct thing, I think we can close this. 

Thanks!

**Comment by boonebgorges** [comment]
Sounds right. Thanks!
