### ISSUE TITLE
When editing a cloned group, you should see all options for creating/linking sites

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#475]
When creating a group via clone, we hide certain options on the Site panel. See #356.

However, the logic introduced here doesn't distinguish between the creation flow and the edit flow. This means it's impossible to make the full range of Site modifications to an existing group that happens to have been created as a clone. This is incorrect. We should only be hiding these options during clone *creation*.

**Comment by bree-z** [comment]
This looks good, thanks! When I edit a clone and unlink the associated site, I'm able to create a new site, use an existing site, or use an external site. 

The options for creating a new clone are still limited to creating a new site or using an external site.
