### ISSUE TITLE
Add toggle to show/hide portfolio link on user profile

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#476]
Port from the City Tech OpenLab: http://redmine.citytech.cuny.edu/issues/3397

**Comment by boonebgorges** [comment]
The port is ready to test on openlabdev.commonsinabox.org

**Comment by bree-z** [comment]
Thanks Boone. 

I'm seeing an issue with the setting I chose during creation not being applied properly after creation:

* I created a portfolio with a new user account: https://unwavering-vole-0e3fea.instawp.xyz/members/testfaculty/. This was the first portfolio created with this account -- I hadn't deleted any previously.
* I left the box to show the portfolio link unchecked, but after creating the portfolio the box was checked and the link is visible to other users. 

**Box unchecked during creation:**

<img width="1258" alt="Screenshot 2024-07-10 at 9 34 45 AM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/5a0cff23-1389-4d6f-af2c-b5ae9483ec58">


We'd also like to make a few text changes to remove OpenLab references, and some of the more City Tech-specific text in portfolio creation, settings, and the checkbox on the user profile:

**Heading**: Portfolio Link on my Profile

**Instructional text**: You can choose to show a link to your Portfolio on your Profile page by checking the box below. 

**Checkbox text**: Show link to my Portfolio on my public profile

Thanks!

**Comment by boonebgorges** [comment]
I've fixed the bug related to portfolio creation.

I made the text changes. For 'Instructional text', I assume that you are only correcting the first sentence, and you want the second sentence ("If your Display Name..") to remain.

**Comment by bree-z** [comment]
No, sorry to not be clear. 

For 'Instructional text', we want to eliminate the second sentence, since installations may use different terms than "Display Name". Also, not everyone may want to state the case as strongly.

**Comment by boonebgorges** [comment]
Sounds good. I've removed the second sentence.

**Comment by bree-z** [comment]
Thanks Boone!

The portfolio creation bug is fixed. When I create a portfolio with the box checked or unchecked, the settings are saved correctly after creation. Checking and unchecking the checkbox on my profile and in Portfolio > Settings also works as expected.

The text changes look good for Portfolio creation. Sorry though, I realize I made an error in my editing, and should have capitalized "Profile" in the checkbox text, for consistency: Show link to my Portfolio on my public Profile

I don't see the text changes in the checkbox text on the member profile or in Portfolio Home > Settings.

Thanks!

<img width="1228" alt="CheckboxOnProfile" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/c65645df-880d-4b2b-8667-5525eb2b872b">

<img width="1192" alt="TextInSettings" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/bebe9066-dfbf-4525-bbca-cf063e0d4d72">

**Comment by boonebgorges** [comment]
I've made the changes.

**Comment by bree-z** [comment]
Thanks Boone! There's still one remaining reference to OpenLab, in the heading in Portfolio Settings: Portfolio Link on my OpenLab Profile, but everything else looks good.

<img width="892" alt="OpenLabInHeading" src="https://github.com/user-attachments/assets/8b4e648b-f0c2-4bf4-bc54-3aa376fe73f6">

**Comment by boonebgorges** [comment]
I've pushed up a change.

**Comment by bree-z** [comment]
Thanks Boone! The change looks good, but I wonder if it affected the styling of other text throughout the site. See for example group settings:

<img width="1293" alt="Screenshot 2024-07-12 at 12 21 17 PM" src="https://github.com/user-attachments/assets/401125ae-f490-41f4-9063-738938640aa2">



Or the [Courses directory](https://unwavering-vole-0e3fea.instawp.xyz/groups/type/course/):



<img width="1243" alt="Screenshot 2024-07-12 at 12 17 58 PM" src="https://github.com/user-attachments/assets/9d31f228-e40e-4714-99b2-dd2f00dd0f56">

**Comment by boonebgorges** [comment]
For some reason you weren't running the bp-classic plugin, which is part of the CBOX 1.6.0 upgrade routine. I've fix that for you.

**Comment by bree-z** [comment]
Thanks Boone! Sorry about that. 

I'm not sure how that happened, but I've been seeing a prompt in the CBOX OpenLab Dashboard that there are upgrades available. I haven't clicked on it, but when I was doing something else in the Dashboard an upgrade seemed to be triggered automatically.
