### ISSUE TITLE
Display 'Member Portfolios' widget to group members only in courses

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#478]
Port from City Tech OpenLab: http://redmine.citytech.cuny.edu/issues/3390

**Comment by boonebgorges** [comment]
I've made the change for the group profile sidebar widget.

As far as I can see, we don't have a regular WP widget for this purpose in CBOX-OL.

**Comment by bree-z** [comment]
This looks good, thanks!
