### ISSUE TITLE
OpenLab Theme- default WordPress Toolbar has reordered to the top and is covering OpenLab Header

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#481]
Hi everyone,

I'm not exactly sure when this change happened, but I suspect the cause was when my multisite auto upgraded to WordPress 6.4.5

On my main OpenLab site, the WordPress toolbar has reordered itself to the top and is appearing over the Logo and the Menus.

<img width="1407" alt="Screenshot 2024-06-26 at 12 26 25 PM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/29982981/a4c4bbac-1fb0-41cc-9349-d81ec5e423b9">

This only seems to effect logged in viewers. When logged out, the toolbar is in the correct position:

<img width="1346" alt="Screenshot 2024-06-26 at 12 47 08 PM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/29982981/fa572a61-185a-43c0-88fa-43e14e6c3167">

**Comment by boonebgorges** [comment]
What version of Commons In A Box are you running?

Do you have a test login whose credentials you can send to me?

**Comment by beckej13820** [comment]
Hi Boone,

Currently running WordPress 6.4.5
CBOX OpenLab 1.5.1
Server Linux 3.10.0 x86_64
Web server LiteSpeed
PHP version 8.0.28

**Comment by boonebgorges** [comment]
Hm, I've set up an installation like this and I can't reproduce. If you're able to share login credentials over email, it may help. Or you could look to see if there are obvious markup (improperly closed tags, maybe?) or CSS issues using the Inspector.

**Comment by beckej13820** [comment]
Hi Boone, I sent you an invitation to create an account. You will have to login through: https://openlab.oneonta.edu/wp-login.php?normal

**Comment by boonebgorges** [comment]
Hm, I'm not seeing an invitation in any email account. Perhaps you can try [my github user name] at gmail.

**Comment by beckej13820** [comment]
Boone,

I think I solved this problem by disabling the plugin WordPress Multisite Enhancements. It was causing some chaos throughout the site, and the Reclaim crew remembered that there was some interactions with CBOX and showed me your comments from a couple weeks ago.

**Comment by boonebgorges** [comment]
Aha, thanks for reporting back. What you're seeing is, in fact, a symptom of a serious bug in the latest version of multisite-enhancements. I described it and recommended a fix in https://github.com/bueltge/wordpress-multisite-enhancements/issues/81, which the authors haven't yet responded to.
