### ISSUE TITLE
The admin bar disappears when a user has a new message notification

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#483]
Logged in as teststudent, I sent a message to teststaff. When I logged in as teststaff, the admin bar was gone, on the homepage, My Profile, etc. After I went to My Messages and opened the new message, the admin bar appeared again. 

Unread message:

<img width="1291" alt="Screenshot 2024-07-11 at 2 20 50 PM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/82ad29a7-97b0-4d59-acbc-673acc6675d3">

After opening:

<img width="1246" alt="Screenshot 2024-07-11 at 2 21 12 PM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/faa26fe8-c087-44ec-901f-833b7e89d42c">

**Comment by boonebgorges** [comment]
As happened in https://github.com/cuny-academic-commons/commons-in-a-box/issues/484#issuecomment-2225428919, this appears to be due to a bug that was fixed between the time when you last pulled changes to your testing site, and when you created the ticket. Can you test again against the latest?

**Comment by bree-z** [comment]
This is also fixed, thanks!
