### ISSUE TITLE
Docs list page doesn't display properly

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#484]
See, for example: https://unwavering-vole-0e3fea.instawp.xyz/groups/tf-course-1/docs/ where the sidebar is missing, as well as metadata like author, date created, and last edited.

When I navigate to a doc, the sidebar appears correctly.

Thanks!

**Comment by boonebgorges** [comment]
This was caused by work on #458. I fixed it before you posted this ticket, but the version of the plugin you were testing must have been pulled to the server before this fix. I've updated https://unwavering-vole-0e3fea.instawp.xyz/ and it appears to be working properly now.

**Comment by bree-z** [comment]
Sorry about that. This looks good!
