### ISSUE TITLE
Links to My Friends, My Messages, My Invitations are incorrect

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#485]
Hi Boone, 

When I'm on My Profile, the links in the sidebar for My Friends, My Messages, and My Invitations are correct. 

However, if I'm on a subpage of My Profile (e.g. My Settings, My Courses, etc), the links in the sidebar for My Friends, My Messages, and My Invitations are incorrect. 

E.g., https://unwavering-vole-0e3fea.instawp.xyz/members/testfaculty/settings/friends/ from My Settings rather than https://unwavering-vole-0e3fea.instawp.xyz/members/testfaculty/friends/ from My Profile.

Thanks!

**Comment by boonebgorges** [comment]
This is related to #458 and should be fixed by cbca722

**Comment by bree-z** [comment]
This is fixed, thanks!
