### ISSUE TITLE
Posts and Comments don't appear in homepage 'What's Happening' activity feed

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#486]
For example, this post and comment should appear in the feed (screenshot below), since they're on a public site, and post visibility settings are 'Everyone': https://unwavering-vole-0e3fea.instawp.xyz/tf-course-2/2024/07/16/public-site-visibility-everyone/

I do see posts appearing on BMCC's feed. I'm not sure about comments.

<img width="441" alt="Screenshot 2024-07-16 at 3 26 10 PM" src="https://github.com/user-attachments/assets/2892bc0a-0449-4a10-961c-ecd684e1b340">

**Comment by boonebgorges** [comment]
The activity item associated with this blog post is marked hide_sitewide=1. This suggests that the site was not fully public when you created the post. Could you please test again, double-checking that the site is public at the time of posting? (I was not able to reproduce the behavior locally.)

**Comment by bree-z** [comment]
Sorry about that. The site was public, but set to ask search engine not to index. After changing that to allow search engines, posts and comments appeared in the feed.
