### ISSUE TITLE
Change the order of the privacy options for avatar and other profile fields 

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#487]
Hi Boone, 

We can move this to another release if it can't go into this one. 

We'd like to change the order of the privacy options for the avatar and other profile fields so the order makes more sense going from most open to least: Everyone, All Members, My Friends, Only Me.

We'd also like to change "All Members" to "All Community Members"?

Thanks!

<img width="913" alt="Screenshot 2024-07-17 at 8 09 34 PM" src="https://github.com/user-attachments/assets/d19a8a51-f364-4966-8ed9-fa7a8fe122ae">

<img width="879" alt="Screenshot 2024-07-17 at 8 10 10 PM" src="https://github.com/user-attachments/assets/8397f782-bbbf-4377-b90a-c48c8e9803b2">

**Comment by boonebgorges** [comment]
I've made the change.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
