### ISSUE TITLE
Members directory heading is "Hello World!" 

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#488]
See: https://unwavering-vole-0e3fea.instawp.xyz/members/

<img width="1221" alt="Screenshot 2024-07-17 at 8 41 38 PM" src="https://github.com/user-attachments/assets/ca43e61f-d60e-4a10-a2b4-fd6c380b7c19">

**Comment by boonebgorges** [comment]
This is due to a change in how BuddyPress 12+ builds directory pages. I've made a change that should address it.

**Comment by bree-z** [comment]
This looks good, thanks!
