### ISSUE TITLE
My Profile > My Settings: Subnav links to 'Export Data' are incorrect

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#489]
In My Profile > My Settings, the subnav links to 'Export Data' are incorrect:

**My Settings** (https://unwavering-vole-0e3fea.instawp.xyz/members/facultytest/settings/)

All links are correct, except 'Export Data'. I get a 404. The URL is: https://unwavering-vole-0e3fea.instawp.xyz/members/facultytest/settings/settings/data/

**My Settings > Edit Profile** (URL: https://unwavering-vole-0e3fea.instawp.xyz/members/facultytest/profile/edit/group/1/)

All links are correct, except 'Export Data'. The URL is is: https://unwavering-vole-0e3fea.instawp.xyz/members/facultytest/profile/edit/group/1/settings/data/ But 'Edit Profile' is what loads.

**My Settings > Change Avatar**

All links are correct, except 'Export Data'. I get a 404. The URL is: https://unwavering-vole-0e3fea.instawp.xyz/members/facultytest/profile/change-avatar/settings/data/

**My Settings > Email Notifications**

All links are correct, except 'Export Data'. I get a 404. The URL is: https://unwavering-vole-0e3fea.instawp.xyz/members/facultytest/settings/notifications/settings/data/

**Comment by boonebgorges** [comment]
Related to #458. Should be fixed by ac761fefd168f3c5d465962a2742e5fcde4cf164

**Comment by bree-z** [comment]
This looks good, thanks!
