### ISSUE TITLE
Group Settings > Creator(s) section has extra row of fields

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#491]
On the dev site, there's an extra row of fields that doesn't appear on cboxopenlab.org:

**unwavering-vole:**

<img width="883" alt="CreatorsDev" src="https://github.com/user-attachments/assets/1c402373-d039-4a99-a8b9-de4b5e851ca6">

**cboxopenlab.org:**

<img width="916" alt="CreatorsCommunityHub" src="https://github.com/user-attachments/assets/ab84260a-4a12-49d6-91fc-9d8d349b6263">

**Comment by boonebgorges** [comment]
It must be the case that previous versions of BP added the 'js' body class. I've added it.

**Comment by bree-z** [comment]
This looks good, thanks!
