### ISSUE TITLE
File Library > Non-members see 'Add new file' button

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#492]
This is not a new issue:

Non-group members see the 'Add new file' button, 'Add new file' link in the subnav, and the text "No files have been added yet. Add a new file below."

The button and link should be hidden, and the text should just say "No files have been added yet."

Thanks!

**Comment by boonebgorges** [comment]
This has been fixed.

**Comment by bree-z** [comment]
This looks good, thanks!
