### ISSUE TITLE
Shared cloning > 'Credits' widget on site doesn't show any credits text

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#493]
When a site is cloned via shared cloning, the 'Credits' widget appears on the site, but doesn't display any text. 

See, for example: https://unwavering-vole-0e3fea.instawp.xyz/shared-clone-of-ft-course-2/ 

The course home does show credits: https://unwavering-vole-0e3fea.instawp.xyz/groups/shared-clone-of-ft-course-2/

**Comment by boonebgorges** [comment]
This should now be fixed

**Comment by bree-z** [comment]
This looks good, thanks!
