### ISSUE TITLE
Group Details subnav style doesn't match other pages

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#495]
This is a pre-existing issue: When a user is on one of the pages in Group > Settings, the style in the subnav is bold with no underline, except for Course Details. 

**Course Details**

<img width="600" alt="SubnavCourseDetails" src="https://github.com/user-attachments/assets/ae734f29-90ca-45ec-8300-3e24c2531473">

**Site**

<img width="718" alt="SubnavSite" src="https://github.com/user-attachments/assets/dbe48d5e-7ce7-414a-a461-6cb13c0d0b43">

**Comment by boonebgorges** [comment]
This should now be fixed.

**Comment by bree-z** [comment]
This looks good, thanks!
