### ISSUE TITLE
Broken Links to Group Docs and Wiki pages

### ISSUE THREAD

**Issue by vothsco** [cuny-academic-commons/commons-in-a-box#89]
Two users are reporting issues with broken links to group docs.  They receive 404 - "Darn it.. Nothing found Sorry, but nothing matched your search criteria. Please try again with some different keywords."  Also, one user reports that the wiki pages are all redirecting to the home page after upgrading to the new version of WordPress.

Here is a link to the forum thread:http://commonsinabox.org/groups/help-support/forum/topic/doc-read-is-not-showing/#post-3835

**Comment by r-a-y** [comment]
This was fixed awhile ago in BP Docs.  Closing!
