### ISSUE TITLE
Install & Activate Default CBOX Theme on Installation

### ISSUE THREAD

**Issue by BoweFrankema** [cuny-academic-commons/commons-in-a-box#98]
Hi guys,

How does everyone feel about installing and activating the CBOX Theme by default on new installations? I've been going through the installation steps and I think not installing and activating the CBOX theme by default is not the best experience. I think it's fair to assume 99% of our users will be using CBOX with our default theme or a child theme (I have not really noticed any other use cases) and I think we might lose some people by having to manually install the default theme.

I forgot why we chose to not do this by default, but I think it had something to do with lots of people having the BuddyPress Default theme activated and configured.

Maybe we could extend the set-up wizard with a new screen (after the plugin installation) and give them a simple choice:

Step 3: Theme Selection:

CBOX comes with a unique theme that completely integrates with all the CBOX functionality. We strongly recommend to use this theme to build your community.

_Screenshot of theme_
Button: Use the CBOX Theme

Small text hyperlink: No thanks, I'd like to keep my current theme
## 

I think this would make setup easier for most people, what do you guys think?

**Comment by r-a-y** [comment]
Should be fixed in 01fbc75, scheduled for v1.1.0.
